### ISSUE TITLE
Module 'BleClientManager' not found when using `yarn add react-native-ble-plx`

### ISSUE THREAD

**Issue by tomdaniel0x01** [Polidea/react-native-ble-plx#105]
The Carthage folder does not show up in $(SRCROOT)/../node_modules/react-native-ble-plx/ios/BleClientManager/ when using yarn.

I don't think the following is happening:
> react-native-ble-plx@0.6.0 postinstall /Users/tomchi/informu/informu_mobile_app/node_modules/react-native-ble-plx
> bash build_ios_frameworks.sh

**Comment by Cierpliwy** [comment]
Probably yarn is not calling postinstall script...

**Comment by watadarkstar** [comment]
Are you an expo detached app? Not sure if this is related but you should:

Add Header Build search paths in BLEClient.xcodeproj:
```
${SRCROOT}/../../../ios/Pods/Headers/Public
$(SRCROOT)/../../react-native/React
```

**Comment by wkoutre** [comment]
This happens to me sometimes when I `yarn add` a new module. To fix, I simply uninstall a module, which forces the BleClientManager to rebuild itself, after which things return to normal.

**Comment by tomdaniel0x01** [comment]
@watadarkstar this was not an Expo app.
@wkoutre I still had this problem even after creating a complete new react-native app through `react-native init`

**Comment by wkoutre** [comment]
@tomdaniel0x01 You've deleted your yarn.lock file, node_modules, and did a fresh `yarn install` ?

**Comment by stinodes** [comment]
Also ran into this issue.
The post-install script was fired, but didn't complete, logging something about an argument being invalid (something about cache, can't remember exactly why, sorry for that).
Apparently Carthage was out of date. Updating fixed it.

Just a heads-up :)
