### ISSUE TITLE
Every time I yarn add / remove other framework plx would be build scheme over again

### ISSUE THREAD

**Issue by CrazyWr** [Polidea/react-native-ble-plx#124]
![image](https://user-images.githubusercontent.com/19635808/29164969-d120af7c-7df3-11e7-8608-3d06834d850d.png)

**Comment by CrazyWr** [comment]
and I remove other framework the dictionary `react-native-ble-plx/ios/BleClientManager/Carthage` would be deleted

**Comment by wkoutre** [comment]
Ever find a solution to this?

**Comment by mattermoran** [comment]
Still nothing?

**Comment by derrickbeining** [comment]
@Cierpliwy, this still appears to be an issue. Every time I npm/yarn install something in my project, the bluetooth package rebuilds and takes forever. Do you have any idea what is causing that and how it could be fixed? If you can give me a clue, I'd be happy to try my hand at fixing and make a PR.

**Comment by derrickbeining** [comment]
I guess using the `--ignore-scripts` flag could also be a fine work around for now too
