### ISSUE TITLE
There is not way to access to manufacturedSpecificData 

### ISSUE THREAD

**Issue by guerjon** [Polidea/react-native-ble-plx#128]
I'm trying to access to specific data on my BLE device, this can make do it with the ScanRecord class getManufacturerSpecificData() but, there is no way to access to the ScanRecord result and get the info.

**Comment by Cierpliwy** [comment]
Devices returned during scanning [contain `manufacturerData` property](https://polidea.github.io/react-native-ble-plx/#device).
