### ISSUE TITLE
XCode 9 Frameworks not compatible - Is there any solution?!

### ISSUE THREAD

**Issue by felix-reichel** [Polidea/react-native-ble-plx#144]
➜  BleClientManager git:(master) ✗ carthage update
*** Fetching RxSwift
*** Checking out RxBluetoothKit at "3.0.14"
*** Downloading RxSwift.framework binary at "Oxygen.1"
*** Skipped installing RxSwift.framework binary due to the error:
        **"Incompatible Swift version - framework was built with 3.1 (swiftlang-802.0.53 clang-802.0.42) and the local version is 4.0 (swiftlang-900.0.65 clang-900.0.37)."**
*** Checking out RxSwift at "3.6.1"
*** xcodebuild output can be found in /var/folders/r0/n98856xx11jdjyw7s7_ys4x00000gn/T/carthage-xcodebuild.pcfBaj.log
*** Building scheme "RxBlocking-iOS" in Rx.xcworkspace

**Comment by Cierpliwy** [comment]
You shouldn't be worried about this warning. It only says that you are using different Swift compiler and carthage should rebuild all your dependencies manually from source code in that case.

**Comment by NinjaSudo** [comment]
@Cierpliwy this however, freezes on one of the repos for me leaving me stuck without my bootstrap complete.
