### ISSUE TITLE
Feature request: Catch "app scanning too frequently" exception with a callback. 

### ISSUE THREAD

**Issue by ataiiii** [Polidea/react-native-ble-plx#146]
There is a limit for ble scan on android 7 onwards and it does not allow the app to start/stop scanning more than 5 times in 30s. It would be useful to know when it happens.

**Comment by dariuszseweryn** [comment]
`RxAndroidBle 1.4.0` adds this check when right before scan.
The newest version is `1.4.1` as for the moment of this post.
@Cierpliwy

**Comment by Cierpliwy** [comment]
It would be nice to add specific error code for this situation #15.
