### ISSUE TITLE
isIndictable should be isIndicatable

### ISSUE THREAD

**Issue by rclai** [Polidea/react-native-ble-plx#148]
The word indictable has to do with the prosecution of someone for a crime.

"Indicatable", while it isn't a real word, describes the BLE indication feature's state more appropriately.

**Comment by wkoutre** [comment]
Could this please be changed? Agreed with @rclai

**Comment by Cierpliwy** [comment]
Fixed with #188. Change is available in 0.7.0.

**Comment by rclai** [comment]
Yay! Lol.
