### ISSUE TITLE
warning: directory not found for option '-F/Users/user/development/bleApp/ios/../node_modules/react-native-ble-plx/ios/BleClientManager/Carthage/Build/iOS.' when running in Xcode.

### ISSUE THREAD

**Issue by IainIsCreative** [Polidea/react-native-ble-plx#150]
I've managed to get further with getting this library to work with iOS, however this one mystifies me. I have followed all the steps necessary (except 11) for getting this to work in iOS. However, I'm getting this error when I run this in Xcode. The directory and files do exist, they've been made, but I don't understand what's going on here. Has anyone got any advice? Thank you in advance!

(NOTE: No, my username on my computer is not 'user!')

**Comment by frankimhof** [comment]
Do you have carthage installed?
If not, do this in terminal (you need homebrew to download carthage)
`brew install carthage`
create cart file with terminal in your repository where your .xcodeproj file is
`touch Cartfile`
open the file with a Texteditor and add the line
`GitHub "Polidea/react-native-ble-plx"`
save and then run
`carthage update`

Thats where I get my error 
https://github.com/Polidea/react-native-ble-plx/issues/149
I hope you will succeed

**Comment by IainIsCreative** [comment]
UPDATE: I have got it working! Though I will admit, the fault is my own. Also, the clue is in the title of this issue.

That's right, this was **caused by a spelling mistake.** 

Altogether now...

![My reaction when I found this out.](https://media.giphy.com/media/l0HlCqV35hdEg2GUo/giphy.gif)

This issue is now closed. I'm off on a humiliation conga.

**Comment by lifenautjoe** [comment]
What spelling mistake? Can  you please clarify?
