### ISSUE TITLE
Customizable device name ~

### ISSUE THREAD

**Issue by sooxiaotong** [Polidea/react-native-ble-plx#157]
Add customizable device name for `startDeviceScan` not always necessary to use device default name.

**Comment by Cierpliwy** [comment]
Can you elaborate more? I'm not sure what is your requirement?

**Comment by sooxiaotong** [comment]
can we customize our device name with js without changing our phone bluetooth display name?

**Comment by Cierpliwy** [comment]
Changing device name must be supported by device itself. You should check if your manufacturer allows that and how to do it. There is common [Device Name](https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.characteristic.gap.device_name.xml) characteristic which can be used to read and in some cases to override device name (if it's writable).

**Comment by sooxiaotong** [comment]
oh ya, I got another question, can I get device id ( Mac Addr & UUID ) without opening Bluetooth?

**Comment by Cierpliwy** [comment]
Check answer at #92
