### ISSUE TITLE
Could not figure out the format of the value returned after connecting and reading a specific  characteristic

### ISSUE THREAD

**Issue by KarthickCSK** [Polidea/react-native-ble-plx#164]
uuid : "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
value : "CAIBAQAAAAAAAAAAAAAAAAAAAAA=" 

Any insights onto this would help

**Comment by Cierpliwy** [comment]
You should check documentation before asking questions:
https://polidea.github.io/react-native-ble-plx/#characteristic
Values are in Base64 format.

**Comment by KarthickCSK** [comment]
Yeah . Apologies  but i am unable to convert the Value i mentioned above from base64 to integer. Gets an NaN error using base64-int32 module

**Comment by Cierpliwy** [comment]
Your value looks fine and can be decoded as LE or BE int32 value:
```
var base64 = require("base64-js")
const array = base64.toByteArray("CAIBAQAAAAAAAAAAAAAAAAAAAAA=").buffer
const intLE = new DataView(array).getInt32(0, true)
const intBE = new DataView(array).getInt32(0, false)
console.log("LE: ", intLE, ", BE: ", intBE)
```
