### ISSUE TITLE
On 0.6.4 called cancelDeviceConnection() Error

### ISSUE THREAD

**Issue by zyguard** [Polidea/react-native-ble-plx#166]
Attempt to invoke interface method 'int com.polidea.rxandroidble.RxBleConnection.getMtu()' on a null object reference

toJSObject
Device.java:75

cancelDeviceConnection
BleModule.java:477
........

**Comment by Cierpliwy** [comment]
Thanks for report. We know about issue and it will be resolve with next minor version. In mean time you should revert to 0.6.3.

**Comment by zyguard** [comment]
Thanks Cierpliwy
