### ISSUE TITLE
Solved - Library not loaded: @rpath/libswiftCore.dylib

### ISSUE THREAD

**Issue by psloboda** [Polidea/react-native-ble-plx#168]
Application failed on first screen, missing BleClientManager. I add the BleClientManager.framework also to EmbededLibraries, also add run script for `carthage copy-frameworks' for BleClienmanager.framework, RxSwift.framework, RxBluetoothKit.framework. Checkbox 'Run script only when installing' is unchecked.

Exact exception is:
```
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/containers/Bundle/Application/B7488450-E195-40CD-9ED4-AEAFBF85BFC1/Drydeco.app/Frameworks/BleClientManager.framework/BleClientManager
  Reason: image not found
Message from debugger: Terminated due to signal 6
```

Any idea what can be problem?

![screen shot 2017-10-31 at 22 15 09](https://user-images.githubusercontent.com/14012806/32249360-0d6aa3fe-be89-11e7-9f5b-3ff58831d48e.png)
![screen shot 2017-10-31 at 22 15 59](https://user-images.githubusercontent.com/14012806/32249371-188fbb48-be89-11e7-8090-d052622b40e4.png)

**Solution for me:**
Build Settings > Framework Search Paths - change select from non-recursive to recursive solve the problem

**Comment by swaroopa94** [comment]
@psloboda 
Hi did this also but it did not work for me in xcode 9.1
Can you tell me any other suggestion to solve this
