### ISSUE TITLE
Support for eddystone urls

### ISSUE THREAD

**Issue by Jowin** [Polidea/react-native-ble-plx#169]
Is there a way to get eddystone beacon details while scanning ? Fields like Instance Id seems to be missing while scanning.

**Comment by Cierpliwy** [comment]
Currently we can only send following fields of advertisement data on iOS:
https://developer.apple.com/documentation/corebluetooth/cbcentralmanagerdelegate/advertisement_data_retrieval_keys
On Android we have all advertisement data bytes available, but I decided to parse only above to keep compability with iOS.

**Comment by Jowin** [comment]
Thanks for the revert, I was unable to find any documentation with regard to the advertisement data. Could you point to some part of the documentation for the library where the advertisement data is sent? Currently while researching I only saw serviceuuid, etc.

**Comment by Cierpliwy** [comment]
You can't access raw advertisement data on iOS.You are limited to:
https://developer.apple.com/documentation/corebluetooth/cbcentralmanagerdelegate/advertisement_data_retrieval_keys

**Comment by Jowin** [comment]
Thanks for the quick revert. Much appreciated.
