### ISSUE TITLE
make example easier to build

### ISSUE THREAD

**Issue by pstanton** [Polidea/react-native-ble-plx#177]
The example is 2 years old and so are it's dependency versions etc. much of this makes it hard to build in an up-to date development environment.

also recommend cutting down on the non-essential dependencies so that the project is lite and the code demonstrates the plugin and nothing else.

**Comment by Cierpliwy** [comment]
We plan to remove Sniffator and create new examples which will have no other dependencies then this library. However we have other priorities right now.

**Comment by pstanton** [comment]
great. understood

**Comment by Cierpliwy** [comment]
Process of rewriting Sniffator is tracked in #189. Closing.
