### ISSUE TITLE
BleClientManager framework not found for architecture x86_64 after running carthage

### ISSUE THREAD

**Issue by LingboTang** [Polidea/react-native-ble-plx#199]
I followed the exact steps in README, and when I tried to build my project with ble-plx, I got this error:

`ld: framework not found BleClientManager for architecture x86_64`

And here is my setting:

![screen shot 2017-12-13 at 12 03 33 pm](https://user-images.githubusercontent.com/3565168/33957056-c34da924-dffd-11e7-8762-c8f73f4da7cf.png)

Then I tried manually add frameworks to my project like this:

![screen shot 2017-12-13 at 12 07 10 pm](https://user-images.githubusercontent.com/3565168/33957199-307ad7e2-dffe-11e7-8517-f05dc42a3065.png)

But I still got this:

`ld: framework not found BleClientManager`

Is there anything I'm missing?

Additional info: 

I have latest carthage 0.27.0, and latest react-native 0.51, and the build target is iOS 11.1.

**Comment by LingboTang** [comment]
My fault, 

I set the framework search path to header search path, close this.

**Comment by swaroopa94** [comment]
@LingboTang  Hi I tried everything I added framework seach path also but the app is getting crashed and the report is as follows:

`dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/ss-macmini-133/Library/Developer/CoreSimulator/Devices/1E7C8CEA-3BB8-4312-AD76-BE10A3093D13/data/Containers/Bundle/Application/07776147-E23B-4ECB-B2E5-C095111AD428/Sniffator.app/Frameworks/BleClientManager.framework/BleClientManager
  Reason: image not found
(lldb)`


Can you tell me how to solve this

**Comment by LingboTang** [comment]
@swaroopa94 Why are you using the Sniffator.app, it looks weird to me.
