### ISSUE TITLE
Current Examples/Sniffator is an empty app

### ISSUE THREAD

**Issue by LingboTang** [Polidea/react-native-ble-plx#200]
I'm learning how to use ble-plx now, however the examples/Sniffator is an empty app for RN v0.51. Could your team update this example?

**Comment by dariuszseweryn** [comment]
Hello,

The Sniffator example app is currently under an update procedure #189 . You can check out the progress on `example_app_update` branch or an older commit from before #190

**Comment by LingboTang** [comment]
@dariuszseweryn I've also complete a working sample myself with most of the functions. So thanks, I'm looking forward to the new sample though.
