### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by hansmbakker** [Polidea/react-native-ble-plx#201]
It would be great if this could be used on [React Native for Windows](https://github.com/Microsoft/react-native-windows)! Do you have any plans to add that to your roadmap?

**Comment by Cierpliwy** [comment]
I don't have Windows machine, so I'm looking forward to contributions!

**Comment by cinderblock** [comment]
I see references to people using this package with Windows in some of the issues. Has Windows support been added? I'm having a hard time finding a full-ish list of supported systems.

**Comment by msridar** [comment]
Any update on this feature ?

**Comment by noshaid-ali** [comment]
Any good news about to add support for Windows desktop app?

**Comment by noshaid-ali** [comment]
@msridar @cinderblock @hansmbakker How did you guys connect BLE devices with react native windows desktop app? I need help

**Comment by msridar** [comment]
No, I havent used this module

**Comment by noshaid-ali** [comment]
So how you did BLE communication in react native windows desktop?

**Comment by hansmbakker** [comment]
I have not used React Native in the end

**Comment by cinderblock** [comment]
@noshaid-ali per my previous comment, it seems this package doesn't support Windows.
