### ISSUE TITLE
Is there a way to cancel monitor of characteristic?

### ISSUE THREAD

**Issue by pstanton** [Polidea/react-native-ble-plx#202]
I'm adding a listener via monitorCharacteristicForService:

```
deviceC.monitorCharacteristicForService(Params.svcUUID, Params.ctlChr, (error, characteristic) =>
	this.characteristicNotification(error, characteristic)
);
```

however when I disconnect from a device via `device.cancelConnection();` my listener is called with an error "Error: Unknown error: BleDisconnectedException{....."

I would like to remove/cancel my monitor/listener prior to disconnecting to avoid this error, however cannot see in the API how this is possible.

I also think it would be a good idea to allow people to stop monitoring a characteristic without disconnecting.

Any suggestions?

**Comment by elliottheis** [comment]
@pstanton it looks like you've forgotten to pass an arbitrary transation id to `monitorCharacteristicForService()`

i.e.
```
deviceC.monitorCharacteristicForService(
  Params.svcUUID,
  Params.ctlChr,
  (error, characteristic) =>
    this.characteristicNotification(error, characteristic),
  'someTransactionId',
);
```

once specified you should then be able to stop monitoring the characteristic by calling `bleManager.cancelTransaction('someTransactionId')`

hope that helps

**Comment by Cierpliwy** [comment]
`monitorCharacteristicForService` also returns subscription with `remove()` function so setting transactionId is not necessary.

**Comment by Cierpliwy** [comment]
Closing as this shouldn't be an issue. There are two methods to cancel monitoring as described above.

**Comment by StephaneJuban** [comment]
I'm using v1.0.3 but for me, when I call `remove()` on the object returned by `monitorCharacteristicForService`, it doesn't stop the listener callback.

Any idea why ?

**Comment by StephaneJuban** [comment]
@Cierpliwy :)
