### ISSUE TITLE
Is it possible to store paired devices locally through any functions 

### ISSUE THREAD

**Issue by LingboTang** [Polidea/react-native-ble-plx#204]
Hi team,

I would like to know if we can store paired devices after connecting to it once? I didn't necessarily see any function is explicitly doing the task. So is there a workaround of storing paired devices?

**Comment by dariuszseweryn** [comment]
Hello,

There is no function for storing paired devices in the library. What would you like to achieve?

**Comment by dariuszseweryn** [comment]
Should be fine since id do not change

Closing
