### ISSUE TITLE
Successful subscriptions

### ISSUE THREAD

**Issue by mateusz-** [Polidea/react-native-ble-plx#206]
Many of the BleManager methods return Promises. If a Promise fails, it will be rejected, if it succeeds, it will resolve, which means both success and failure cases can easily be handled.

Other methods, like `monitorCharacteristicForDevice` return Subscriptions (well, actually, are there any other ones?). A subscription takes a `listener` parameter. If an error occurs, the `listener` function gets invoked with an Error as the first parameter and null as second. When a notification occurs, first parameter, Error is null and second parameter is a Characteristic object.

This does not handle one important issue - how does one know if the monitoring call succeeded, since it's async and `listener` callback gets only invoked if an error occurred or if notification happened?

Basically, what I want to do is this:
```js
const sub = ble.monitorCharacteristicForDevice(controllerID, serviceID, notCharID, (err, char) => {
  if(err) {
    // an error occurred either when trying to write the CCCD or sometime afterwards
  } else if(err === null && char === null) {
    // wrote to CCCD successfully
  } else {
    // characteristic was updated
  }
});
```
Looking at the `BleManager` js class, it looks like `_handleMonitorCharacteristic` uses a Promise internally (`monitorPromise` parameter). I looked at it and it looks like it only resolves when subscription is removed, not, as I had thought, after CCCD writes successfully.

The specific issue that I am having is the following. I have a single characteristic that is notify only (no read / write) and it requires encryption and authentication. Calling `monitorCharacteristicForDevice` triggers the pairing process, but I have no idea when it succeeds. With read / write, I could do:

```js
// should trigger pairing process
ble.writeCharacteristicWithResponseForDevice(controllerID, serviceID, notCharID, value)
.then(() => {
  // pairing succeeded AND wrote successfully
})
.catch(() => {
  // pairing failed OR could not write characteristic
});
```

Pairing support would resolve my issue but the general problem is still there.

**Comment by Cierpliwy** [comment]
I fully agree.

I plan to promisify all callback based calls, so that they will be easier to use in `async` and generators functions (saga). In case of notifications I plan to do something like:

1) Mimic old behaviour.
```js
const readAllNotifications = async (characteristic: Characteristic) => {
    // We are starting notification process.
    const notificationBuffer = await characteristic.startNotifying(BleBuffer.expanding);
    // Now we are sure that notification was set up.
    for (;;) {
        // This will block until there is at least one value in an internal buffer.
        const value = await notificationBuffer.nextValue();
        // do something with value...
    }
    // Close notification
    await notificationBuffer.close()
}
```

2.) Allow more complex scenarios.
```js
const complexScenario = async (characteristic: Characteristic) => {
    // We are starting notification process.
    const notificationBuffer = await characteristic.startNotifying(BleBuffer.discarding, 5);
    // We _might_ need to enable notifications by writing specific value.
    await characteristic.writeWithResponse(...)
    // Take 5 samples, 3 times.
    for (let i = 0; i < 3; i++) {
        // Wait until there are 5 values in a buffer and take them.
        const values = await notificationBuffer.take(5);
        // do something with value...
    }
    // We _might_ need to disable notifications by writing specific value.
    await characteristic.writeWithResponse(...)
    // Close notification
    await notificationBuffer.close()
}
```
