### ISSUE TITLE
Expokit project iOS :module appregistry is not a registered callable module 

### ISSUE THREAD

**Issue by honbaa** [Polidea/react-native-ble-plx#210]
In our project, we add the “react-native-ble-plx” package, and config the Xcode as described in https://github.com/Polidea/react-native-ble-plx but after finishing the configurations, we build it and run on the simulator (iOS 11.2), it failed.
![screen shot 2018-01-10 at 3 59 13 pm](https://user-images.githubusercontent.com/8036140/34862065-3a4e6dc6-f7a3-11e7-9e62-9e763135f1e5.png)

the environment as follows:

- expo sdk version :23
- macos version:10.13.2
- xcode version: 9.2
- simulator version: iPhone 8 iOS 11.2
- react-native-ble-plx version : 0.8.0

Has anyone solved this problem?

**Comment by dariuszseweryn** [comment]
Hello,
I have seen this problem recently but with a different module. I was doing an update of Expo SDK on a detached application and I forgot to update `EXSDKVersions.plist`. Maybe it is the case in your situation?

**Comment by honbaa** [comment]
@dariuszseweryn thanks for your reply. We have made other choice to solve it. Thank you all the same.

**Comment by honbaa** [comment]
@dariuszseweryn We have decided to use the pure react-native project rather than Expo project.
