### ISSUE TITLE
Accessing logs

### ISSUE THREAD

**Issue by laughingguffly** [Polidea/react-native-ble-plx#211]
Pardon my ignorance.

I've imported 
import { BleManager, LogLevel } from 'react-native-ble-plx';

I've enabled the logs as per setLogLevel(LogLevel.Verbose);

I can't find where they are printed to. They aren't going to the browser console or the android logs via react-native android-logs

So where do they go or what am I doing wrong?

Thanks

**Comment by Cierpliwy** [comment]
All logs are printed in native's logging mechanism. You can observe logs in XCode (iOS) and Android Studio (Android).
