### ISSUE TITLE
Run as Android Foreground Service

### ISSUE THREAD

**Issue by rgstephens** [Polidea/react-native-ble-plx#217]
I've read some of the discussions about background mode (#127 & #151).  I have a basic RN project that starts an android Foreground Service and runs BluetoothLeScanner to scan for devices.  I only need to capture advertising packets (no connections, no GATT).

Can I use this project from my RN bridge foreground service?

**Comment by Cierpliwy** [comment]
I didn't do it myself, but I can't see any potential blockers. Do you agree @dariuszseweryn , @paweljaneczek ?

**Comment by dariuszseweryn** [comment]
I do not see any problems from the Android side apart from the UX.

**Comment by rgstephens** [comment]
This is my first RN bridge and I'm not a native developer.  It seems like the best approach would be for my Java foreground service call the `com.polidea.reactnativeblue.BleModule` calls (startDeviceScan, onStateChange, stopDeviceScan, etc).

Does that make sense?

**Comment by rgstephens** [comment]
I'd prefer to call it from JS but I have to start the foreground service from Java (don't I?) and wouldn't I have to make the startDeviceScan from within the Java foreground service code?

**Comment by rgstephens** [comment]
If I start an Android Foreground Service, then on the JS side, periodically call `startDeviceScan`, the JS code is only executed while the app is active even though the Foreground Service is active and shown in notifications. If the screen times out or the user switches away from my app, the JS code stops running even though the Foreground Service is active.

**Comment by dariuszseweryn** [comment]
@rgstephens You are not calling `startDeviceScan` from any `Component` do you?

**Comment by rgstephens** [comment]
Yes, I was.  Good question.  I'm going to make a sample app and do the call the from the root.  This [example in github](https://github.com/rgstephens/ForegroundTest) currently starts a loop in `index.js` that logs the time to console.log and stores it in redux every 10 seconds. I start the loop before the root component is registered.

I have a switch on the main component that starts a foreground service.  Whether the service is started or not, the 10 second timer updates stop when the app loses focus, even though the Android Foreground Service notification shows that it is still running.

I'm going to update this loop to call startDeviceScan at a regular interval.

```
setInterval(function() {
    console.log('*** index.js setInterval', new Date());
    store.dispatch({ type: 'TIMESTAMP' });
  }, 10000);
```

**Comment by rgstephens** [comment]
@DariuszAniszewski I now have a complete example on [github](https://github.com/rgstephens/ForegroundTest) which calls `startDeviceScan` from the root in a loop every 10 seconds and has a switch to start/stop a foreground service.  The scans still stop when I switch away from the app even though the foreground service is running.

**Comment by DariuszAniszewski** [comment]
cc: @dariuszseweryn ^^

**Comment by Cierpliwy** [comment]
@rgstephens Do you still have an issue?

**Comment by rgstephens** [comment]
Yes, I still have the problem. The sample app posted announce does not work in the background.

**Comment by Deityhub** [comment]
still facing this same issue too

**Comment by bimix** [comment]
timers and intervals do not work in background mode. Use something else.
