### ISSUE TITLE
Share json data between devices

### ISSUE THREAD

**Issue by janroures** [Polidea/react-native-ble-plx#218]
Hello, great package by the way. Just wanted to know if it's possible to share json objects between android/ios devices with this library. thank you!

**Comment by Cierpliwy** [comment]
This library doesn't support peripheral mode, so direct communication is not possible yet.

**Comment by janroures** [comment]
I see, thanks! is this feature on your roadmap? I'm currently developing a library to see if that's possible. Will post findings here.

**Comment by Cierpliwy** [comment]
Closing this in favour of #220.
