### ISSUE TITLE
Android studio emulator dont detect any device !

### ISSUE THREAD

**Issue by karimraoudy** [Polidea/react-native-ble-plx#228]
Hello, thank you for this great library, I work on a project and I need to connect the application with a specific device, but it is not detected in my emulator, and when I try the sniffer, it is detected and connect successfully. the library work with real device or it work with the android studio emulator?
thank you all.

**Comment by dariuszseweryn** [comment]
Hello,
Thanks for using the library!
Unfortunately [no Bluetooth functionality works on Android Emulator unless some steps are taken](https://stackoverflow.com/questions/22604305/how-to-use-android-emulator-for-testing-bluetooth-application)
Best Regards

**Comment by karimraoudy** [comment]
Ok, thank you  @dariuszseweryn
