### ISSUE TITLE
Turn off or refresh device caching on iOS

### ISSUE THREAD

**Issue by LingboTang** [Polidea/react-native-ble-plx#230]
I'm trying to scan some nrf52 UART devices, I have no problem scanning them. However, when I changed the device name, and then do a scan using ble-plx again, it still displaying the old name that I believe it is cached in iOS system. I confirmed this behaviour with nordic nrf connection app. What's different is that nordic app will refresh the device name after few seconds or after enable a connection between my iphone and my device. I assume ble-plx has similar functions to refresh the cache, but I didn't see it explicitly in the documentation. Can someone help?

**Comment by LeonidVeremchuk** [comment]
+1

**Comment by AlexKotov** [comment]
+1

**Comment by Cierpliwy** [comment]
iOS uses value of https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.characteristic.gap.device_name.xml in caches, so yes it is possible that when device name is changed and new connection wasn't established scanning can show old name.

Unfortunately I'm not aware of any specific API on iOS to make this process faster. We are using currenty https://developer.apple.com/documentation/corebluetooth/cbperipheral/1519029-name.

**Comment by rafkhan** [comment]
+1

**Comment by bntzio** [comment]
+1

**Comment by CyxouD** [comment]
Still not implemented, but I can only say for sure that it happens on Android

**Comment by gilador** [comment]
i think they way to refresh the gatt cache is by passing the right option parameter:
`connectToDevice(deviceIdentifier: DeviceId, options?: ConnectionOptions): Promise<Device>`
where ConnectionOptions has `refreshGatt?: RefreshGattMoment`:
![image](https://user-images.githubusercontent.com/8309205/85436672-14616000-b592-11ea-8298-7ab161ee8d49.png)

**Comment by originalix** [comment]
> i think there is a way to refresh the gatt cache by passing the right option parameter to the connectToDevice method: `connectToDevice(deviceIdentifier: DeviceId, options?: ConnectionOptions): Promise<Device>` where ConnectionOptions has `refreshGatt?: RefreshGattMoment`: ![image](https://user-images.githubusercontent.com/8309205/85436672-14616000-b592-11ea-8298-7ab161ee8d49.png) so the call should be: `const result = await this.manager.connectToDevice(deviceId, { refreshGatt: 'OnConnected', ...other-options.... })`

`refreshGatt` option is Android only.

**Comment by ArthurRuxton-DY** [comment]
@originalix @gilador @Cierpliwy @LingboTang 

> > i think there is a way to refresh the gatt cache by passing the right option parameter to the connectToDevice method: `connectToDevice(deviceIdentifier: DeviceId, options?: ConnectionOptions): Promise<Device>` where ConnectionOptions has `refreshGatt?: RefreshGattMoment`: ![image](https://user-images.githubusercontent.com/8309205/85436672-14616000-b592-11ea-8298-7ab161ee8d49.png) so the call should be: `const result = await this.manager.connectToDevice(deviceId, { refreshGatt: 'OnConnected', ...other-options.... })`
> 
> `refreshGatt` option is Android only.

Is there a way to refresh or clear cache on IOS?

**Comment by nmurashi** [comment]
Is there any update to this for iOS? Right now it seems the only way to refresh the device in the cache is to connect to it.
