### ISSUE TITLE
BleDisconnectedException

### ISSUE THREAD

**Issue by sachithkadamba** [Polidea/react-native-ble-plx#241]
Hi All,

I get below exception when I try to connect to the BLE peripheral . This is not consistent and I can say there are 50:50 chance of this happening. Any thoughts what could be going wrong?.

 Unknown error: com.polidea.rxandroidble.exceptions.BleDisconnectedException: Disconnected from 76:C1:98:1D:EA:DE
    at createErrorFromErrorData (NativeModules.js:123)
    at NativeModules.js:80
    at MessageQueue.__invokeCallback (MessageQueue.js:400)
    at MessageQueue.js:139
    at MessageQueue.__guardSafe (MessageQueue.js:316)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:138)
    at debuggerWorker.js:72

**Comment by Cierpliwy** [comment]
Colleagues are working on https://github.com/Polidea/RxAndroidBle/pull/405 which will allow me to add specific error reason in upcoming 0.9 release. My bet is that you are getting error 133, which means that something bad happened with your Android's BLE stack.
