### ISSUE TITLE
Upgrade swift version from 4.0.2 to 4.0.3 RxBluetoothKit and RxSwift

### ISSUE THREAD

**Issue by rottenoats** [Polidea/react-native-ble-plx#243]
Just attempted installation and saw this. No idea if this will have an effect later, just thought it should be noted.

> *** Skipped installing RxBluetoothKit.framework binary due to the error:
> 	"Incompatible Swift version - framework was built with 4.0.2 (swiftlang-900.0.69.2 clang-900.0.38) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
> *** Skipped installing RxSwift.framework binary due to the error:
> 	"Incompatible Swift version - framework was built with 4.0.2 (swiftlang-900.0.69.2 clang-900.0.38) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
>

**Comment by Cierpliwy** [comment]
It's not an error. Binary frameworks provided by carthage were built  using Swift 4.0.2 and right now you have version 4.0.3. In that case, everything will be build from source and will take longer due to that. I'll try to update prebuilt binaries in 0.9.

**Comment by wilr** [comment]
@Cierpliwy Any ETA on when the binaries will be updated?

**Comment by radko93** [comment]
RxBluetoothKit seems to be updated for 9.3 now.

**Comment by yogeshk19** [comment]
I get a similar error while running the npm install,

 `npm install --save react-native-ble-plx`

Here is the error I get.

> Skipped installing RxBluetoothKit.framework binary due to the error:
> 	"Incompatible Swift version - framework was built with 4.0.2 (swiftlang-900.0.69.2 clang-900.0.38) and the local version is 4.1 (swiftlang-902.0.48 clang-902.0.37.1)."
> *** Skipped installing RxSwift.framework binary due to the error:
> 	"Incompatible Swift version - framework was built with 4.0.2 (swiftlang-900.0.69.2 clang-900.0.38) and the local version is 4.1 (swiftlang-902.0.48 clang-902.0.37.1).

Thanks,
Yogesh

**Comment by radko93** [comment]
@yogeshk19 This won't work until underlying library gets updated for new Swift.

**Comment by Cierpliwy** [comment]
Latest version of RxSwift is still Spread.2 (https://github.com/ReactiveX/RxSwift/releases)

**Comment by karimkhamwani** [comment]
@Cierpliwy when this issue get fixed thanks

**Comment by ChrisEdson** [comment]
There’s a new RxSwift version released (‘Zurich’) which fixes this. Any chance of a new release now? We depend on this :)

**Comment by Cierpliwy** [comment]
@ChrisEdson Please check version 0.9.1 if it's working for you.

**Comment by efournival** [comment]
With the latest Xcode and `react-native-ble-plx` 0.9.1:
```
*** Checking out RxBluetoothKit at "4.0.3"
*** Checking out RxSwift at "4.2.0"
*** xcodebuild output can be found in /var/folders/hm/7dwsxrq964z38lgvsqzk6btc0000gn/T/carthage-xcodebuild.sHZbCr.log
*** Downloading RxSwift.framework binary at "Zürich"
*** Downloading RxBluetoothKit.framework binary at "4.0.3"
*** xcodebuild output can be found in /var/folders/hm/7dwsxrq964z38lgvsqzk6btc0000gn/T/carthage-xcodebuild.OhtlvM.log
*** Valid cache found for RxSwift, skipping build
*** Valid cache found for RxBluetoothKit, skipping build
*** Building scheme "BleClientManager" in BleClientManager.xcodeproj
Build Failed
	Task failed with exit code 6:
	/usr/bin/xcrun simctl list devices

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/hm/7dwsxrq964z38lgvsqzk6btc0000gn/T/carthage-xcodebuild.OhtlvM.log
Error: "carthage build --no-skip-current --platform iOS --cache-builds"  command failed with status=1
```

**Comment by Dina-Nashaat** [comment]
I think this problem still persists at my end, 
` Downloading RxBluetoothKit.framework binary at "4.0.3"
***  Skipped installing RxBluetoothKit.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2) and the local version is 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)."

    Falling back to building from the source
***  Skipped installing RxSwift.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2) and the local version is 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)."

    Falling back to building from the source`

which in turn gives me this when running the project:
`dyld: Library not loaded: @rpath/RxBluetoothKit.framework/RxBluetoothKit
  Referenced from: /Users/Dina/Library/Developer/Xcode/DerivedData/EpilarmApp-drlgussdbgntayfntobawjihvyrk/Build/Products/Debug-iphonesimulator/BleClientManager.framework/BleClientManager
  Reason: image not found`


Is anybody having the same problem, and if yes, how can I resolve it?
