### ISSUE TITLE
Sending Long Messages

### ISSUE THREAD

**Issue by sowdri** [Polidea/react-native-ble-plx#245]
I'm trying to print a long order in a bluetooth LE thermal printer. If I send the order as it is, then it gets truncated, but if I split it into 200 char chunks, then it works as expected. 

```
const payload = format(order);
const promises = [];
for (const str of R.splitEvery(200, payload as any)) {
  promises.push(device.writeCharacteristicWithResponseForService(SERVICE_UUID, CHAR_UUID, str as any));
}
await Promise.all(promises)
console.log('Printed Successfully')
```
If I change the chunks to 201 characters, then it doesn't work. I'm guessing that somewhere a buffer of max length 200 is being created, is this a documented behaviour? 

I'm not sure if writing to the device in quick succession in a loop has any side-effects. 

Please advice. Thanks

**Comment by Cierpliwy** [comment]
It is not guaranteed to send all of the bytes, which are passed to `write` function. There is a MTU value which your device supports and it is a protocol limit how big your data chunks can be.

Check out https://github.com/Polidea/react-native-ble-plx/wiki/MTU-Negotiation and https://polidea.github.io/react-native-ble-plx/#devicemtu. 

Closing as this is not an issue of library itself.
