### ISSUE TITLE
startDeviceScan() can't find any device after second call

### ISSUE THREAD

**Issue by AlexKotov** [Polidea/react-native-ble-plx#246]
iOS 9.3.5
"react-native": "0.44.0",
"react-native-ble-plx": "^0.6.3",

**Comment by LingboTang** [comment]
What do you mean second call? Also can you try to update your iOS version to 10+, react-native version to 0.5+ and react-native-ble-plx version to 0.7+?

**Comment by Cierpliwy** [comment]
In version 0.7 there is a fix: "Fixed an issue when successive scans could stop emitting scanned devices.". Please retest with version 0.7+ and reopen this issue if it happens again.

**Comment by AlexKotov** [comment]
@Cierpliwy thank u

**Comment by lastmjs** [comment]
My scans seem to randomly stop finding my device
