### ISSUE TITLE
Unsuported architecture during upload to iTunes Store

### ISSUE THREAD

**Issue by psloboda** [Polidea/react-native-ble-plx#247]
I create application with react-native-ble-plx dependency. On phone everything work correctly, but after I archive the bundle for iTunes Store, during the validation of bundle I got error:

`iTunes Store Operation Failed Unsupported Architectures. The executable for Drydeco.app/Frameworks/BleClientManager.framework contains unsupported architectures '[x86_64, i386]'.`

react-native-cli: 2.0.1
react-native: 0.49.5
 react-native-ble-plx: ^0.6.5

I the embeded libraries it is displayed corretly in Xcode.

<img width="992" alt="screen shot 2018-04-07 at 20 19 17" src="https://user-images.githubusercontent.com/14012806/38458673-15743f9e-3aa1-11e8-96df-cb2f7ad0a69c.png">

**Comment by Cierpliwy** [comment]
If you are using carthage you should not manually link and embed framework files. It is the job of copy-framework script to do that correctly as far as I know.

**Comment by psloboda** [comment]
When I remove Linked library, nothing changed.

**Comment by Cierpliwy** [comment]
I'm sure that adding BleClientManager.framework to Embedded binaries is not required. Carthage script should do that for you. Maybe because of that XCode is embedding framework by itself without stripping from unnecessary architectures.

**Comment by psloboda** [comment]
@Cierpliwy it does not change anything when I add or remove BleClientManager.framework from Embedded binaries, but still I am not able to publish archive to iTunes store because of same exception:

` iTunes Store Operation Failed Unsupported Architectures. The executable for Drydeco.app/Frameworks/BleClientManager.framework contains unsupported architectures '[x86_64, i386]'.`

**Comment by psloboda** [comment]
@Cierpliwy any update? We are still facing the same issue, and we are not able to publish application to the appStore because of this issue? Any idea what can be wrong?

**Comment by paweljaneczek** [comment]
@psloboda could you look at your target `Build Phases` and check if you have build script that does `/usr/local/bin/carthage copy-frameworks` and if it have `BleClientManager.framework` in input files?

**Comment by psloboda** [comment]
@paweljaneczek  Yes, I go throught setup manual more times to check the project setup.

![Uploading Screen Shot 2018-07-12 at 10.06.45.png…]()

**Comment by paweljaneczek** [comment]
@psloboda screenshot that you've uploaded only showing `General` section, not `Build Phases`. 
Also library should not be in `Embeeded Libraries`, only in `Linked Frameworks and Libraries`

**Comment by psloboda** [comment]
@paweljaneczek sorry, I probably upload wrong screenshot 

![screen shot 2018-07-12 at 10 12 20](https://user-images.githubusercontent.com/14012806/42620738-17089ee8-85bc-11e8-98d0-1caaaea39742.png)

**Comment by paweljaneczek** [comment]
Please remove library from embed frameworks.

**Comment by psloboda** [comment]
@paweljaneczek thank you a lot, this solve my issue, I had to also update the `react-native-ble-plx` because of some swift incompatibility issue reported here https://github.com/Polidea/react-native-ble-plx/issues/274 but now everything works corretly.

**Comment by paweljaneczek** [comment]
Great to hear. I am glad that could help you!
Closing issue.
