### ISSUE TITLE
Device not authorized to use BluetoothLE

### ISSUE THREAD

**Issue by warrenronsiek** [Polidea/react-native-ble-plx#248]
Hi, just upgraded to react-native-ble-plx from a different ble module. I'm getting an error when I run `startDeviceScan` on android 8.0.0, react-native 0.54.4:

```
Error: Device is not authorized to use BluetoothLE
    at new BleError (BleError.js:53)
    at parseBleError (BleError.js:68)
    at scanListener (BleManager.js:298)
    at RCTDeviceEventEmitter.emit (EventEmitter.js:181)
    at MessageQueue.__callFunction (MessageQueue.js:353)
    at MessageQueue.js:118
    at MessageQueue.__guardSafe (MessageQueue.js:316)
    at MessageQueue.callFunctionReturnFlushedQueue (MessageQueue.js:117)
    at t (RNDebuggerWorker.js:1)
``` 

This seems like it would be a permissions problem, but it isn't. 

AndroidManifest.xml:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          ...
          xmlns:tools="http://schemas.android.com/tools">
          ...
          <uses-permission android:name="android.permission.BLUETOOTH" />
          <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
          <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
          <uses-feature android:name="android.hardware.bluetooth_le" android:required="true"/>
          <uses-sdk
                  android:minSdkVersion="18"
                  android:targetSdkVersion="23"/>
          ...
```
The bleManager reports that bluetooth is "PoweredOn" and I've verified this directly.

Whats going wrong here?

**Comment by Cierpliwy** [comment]
According to error converter, this may happen when we got exception from RxAndroidBLE (BleScanException.BLUETOOTH_NOT_AVAILABLE):
https://github.com/Polidea/react-native-ble-plx/blob/master/android/src/main/java/com/polidea/reactnativeble/errors/ErrorConverter.java#L202.

Reason of this expection is:
"Bluetooth Adapter is not available on the given OS. Most functions will throw {@link UnsupportedOperationException} when called."

Can you put a breakpoint inside of this method and verify if that's the case?

**Comment by warrenronsiek** [comment]
I checked the app install, and despite the fact that the AndroidManifest.xml requests the correct permissions (and a bunch of other permissions as well), Android's App Info says "No Permissions Granted". 

I went to Settings > Apps and notifications > App permissions > Location Permissions and my app was turned off for some reason. Turning it on resolved the problem. 

Looks like even if you ask for permissions in the manifest, the Android might not grant them. Apparently the way you solve this is by using react-native's [PermissionsAndroid](https://facebook.github.io/react-native/docs/permissionsandroid.html) and asking in app to get location enabled. I'm closing this issue, but we might want to add something about this in the README.

**Comment by Cierpliwy** [comment]
Since SDK 23 (Android 6.0) all dangerous permissions must be enabled by the user in runtime. In case of this library at least coarse location is needed for scanning. As you mentioned, you can use PermissionsAndroid to do that.

**Comment by mllw** [comment]
target Sdk Version Less than 23 will prevent this problem

**Comment by dschinkel** [comment]
I thought above you said you were gonna update the readme with https://facebook.github.io/react-native/docs/permissionsandroid.html.  

This is a huge missing piece.  The instructions in the Readme currently is not the full story and it's frustrating when we think kit should work but there are other missing pieces that ble needs to "work with" to ultimately "work"

**Comment by mtrabelsi** [comment]
You promised to update the README, imagine how we can the world a better place by writing 1 line in readme to save hundreds if not thousands of hour for humanity :)

**Comment by outinspace** [comment]
Can this be added to the README?

**Comment by bvanderdrift** [comment]
I haven't seen a PR yet to include this in the README, so made one: https://github.com/dotintent/react-native-ble-plx/pull/940
