### ISSUE TITLE
how can i fix this?

### ISSUE THREAD

**Issue by cicodes** [Polidea/react-native-ble-plx#250]
![image](https://user-images.githubusercontent.com/35441543/38488313-c26d5fa0-3beb-11e8-97b8-130cf1f26a2a.png)
![image](https://user-images.githubusercontent.com/35441543/38488349-db42e900-3beb-11e8-9198-e90d627cf45c.png)
![image](https://user-images.githubusercontent.com/35441543/38488364-e5342dde-3beb-11e8-81ca-8c3ab3ba24a5.png)

**Comment by Cierpliwy** [comment]
In `./android/app/build.gradle` set minSdkVersion to at least 18.
