### ISSUE TITLE
How to Print HTML Table & QR code

### ISSUE THREAD

**Issue by VyankeshH** [Polidea/react-native-ble-plx#251]
Can't able to get Print of HTML Table & QR code.If you have any reference please suggest me.
Thank You:)

**Comment by Cierpliwy** [comment]
@VyankeshH I guess you asked question in wrong project?

**Comment by VyankeshH** [comment]
@Cierpliwy  Yes,I need help to Print HTML Table & QR code.If you know then please suggest any library.
Thank You : )

**Comment by Cierpliwy** [comment]
Unfortunately I don't know any. Closing as this is not related to this library.
