### ISSUE TITLE
Ad Hoc Network

### ISSUE THREAD

**Issue by gleydson** [Polidea/react-native-ble-plx#258]
Hello, does this module provide support for multiple bluetooth connections? I need to create an ad hoc network that will have a master device that will transmit data to other devices. @corymsmith @iegik @literator @verges @davidstritzl

**Comment by dariuszseweryn** [comment]
This library is for the `central` only.
You can connect to multiple `peripheral` devices at the same time.
Using this library you cannot act as a `peripheral` device.

Best Regards

**Comment by gleydson** [comment]
okay, thank you!
