### ISSUE TITLE
Error:Service ... for device ? not found

### ISSUE THREAD

**Issue by pride7** [Polidea/react-native-ble-plx#267]
Hello , 
i m new to the library .i have finally successfully found my device using the library . what i want to do now is writing characteristic in order to control my device . the service UUID and characteristic UUID are given . so i m trying to do it using this code (looks bad but i will improve it when it will work :p ) 
```
startScan() {
        this.setState({scanning: true});
        this.manager.startDeviceScan(null, null, (err, device) => {
            if (err) {
                alert(err);
                return;
            }
            if (device.name === 'Wearable 4') {
                alert('found it');//this is shown
                this.manager.stopDeviceScan();
                this.setState({scanning: false});
                device.connect()
                    .then((device) => {
                        alert(device.name + ':' + device.id);//this is shown
                        device.writeCharacteristicWithoutResponseForService(
                            "713D0000-503E-4C75-BA94-3148F18D941E",
                            "713D0003-503E-4C75-BA94-3148F18D941E",
                            "0xff000000"
                        ).then((success) => {
                            alert(success);
                        }).catch((error) => {
                            alert(error)
                        })
                    })
                    .catch((error) => {
                        alert(error);
                    });
            }
        });
```

i m always receiving " Error Service 713D0000-503E-4C75-BA94-3148F18D941E for device ? not found.

I appreciate your help and thank you in advance

**Comment by pride7** [comment]
![image](https://user-images.githubusercontent.com/10854362/39374323-d419ddba-4a4a-11e8-9b4b-79a7bf55964e.png)

**Comment by dariuszseweryn** [comment]
`"0xff000000"` is not a valid `Base64` string

**Comment by lastmjs** [comment]
I'm receiving the same type of error as @pride7, it doesn't seem to matter what I send as the value, I can't even get my device to write, even though I'm grabbing the serviceUUID and characteristicUUID from the discovered device

**Comment by lastmjs** [comment]
It looks like I had to call `await device.discoverAllServicesAndCharacteristics();` before I could perform the write to the characteristic, is that expected behavior?

**Comment by dariuszseweryn** [comment]
Yes, it is

**Comment by akshayoyo16** [comment]
how would i discover if my the device i am looking for is not in range ?

**Comment by akshayoyo16** [comment]
Is there a concept of timeout in this startDeviceScan function  ??
like if i only want to scan for like 20 seconds, & if i dont find the device i am looking for in 20 seconds then i dont want to move further.

**Comment by ragsav** [comment]
> It looks like I had to call `await device.discoverAllServicesAndCharacteristics();` before I could perform the write to the characteristic, is that expected behavior?

Thanks a lot for pointing out this.
