### ISSUE TITLE
Correct way of enabling and disabling notifications using the client characteristic configuration descriptor (CCCD)

### ISSUE THREAD

**Issue by designingSparks** [Polidea/react-native-ble-plx#272]
I have been reading [this](https://www.polidea.com/blog/ReactNative_and_Bluetooth_to_An_Other_level/) and [this](https://github.com/Polidea/react-native-ble-plx/wiki/Characteristic-Notifying) regarding setting up notifications. It would appear that device.monitorCharacteristicForService() just allows the GAP central to monitor notifications arriving from the GAP peripheral. However, I first need to enable the notication on the GAP peripheral by writing 0x10, 0x00 to the client characteristic configuration descriptor (CCCD), since the notification is not enabled by default. Is this done automatically when device.monitorCharacteristicForService() is called? If not, how is the notification on the GAP peripheral enabled/disabled?

**Comment by dariuszseweryn** [comment]
> Is this done automatically when device.monitorCharacteristicForService() is called? 

Yes

Best Regards
