### ISSUE TITLE
 code ELIFECYCLE while running npm install 

### ISSUE THREAD

**Issue by Kiozak** [Polidea/react-native-ble-plx#275]
Hello , i'm new to react-native and i tried to install this module by following the documentation , but whenever i try "npm install" it shows me this error:
![screen shot 2018-05-15 at 11 50 05](https://user-images.githubusercontent.com/18468446/40055142-7a51e184-5836-11e8-83f5-31dba885d5aa.png)

I don't know how to solve this , if anyone can help ?

Thanks

**Comment by AustenElswick** [comment]
install carthage, and make sure it is linked with ```brew install carthage``` and ```brew link carthage```
