### ISSUE TITLE
Mac installation instructions missing some info

### ISSUE THREAD

**Issue by pstanton** [Polidea/react-native-ble-plx#276]
I have Xcode 9.3.1 installed.

> 1. fine
> 2. fine
> 3. fine
> 4. Open iOS project located in ./ios folder.

my "ios" folder contains:
- dir build
- dir MyProj
- dir MyProj-tvOS
- dir MyProj-tvOSTests
- dir MyProjTests
- MyProj.xcodeproj

... no "iOS Project", it becomes apparent that you mean the "MyProj.xcodeproj". I suggest re-wording the instruction.

> 5. fine
> 6. fine

> 7. In Build Settings/Search Paths/Framework search paths add path: $(SRCROOT)/../node_modules/react-native-ble-plx/ios/BleClientManager/Carthage/Build/iOS.

This option (Search Paths/Framework search paths) only appears after I select "All" in the toolbar below the menu which contains "Build Settings". The default setting of "Basic" hides this option. Also, this is added by default with "non-recursive" .. is that right?

> 8. In Build Settings/Build Options/Always Embed Swift Standard Libraries set to Yes.

same as 7. only available after changing "basic" to "all".

I recommend adding a step between 6 and 7 stating "change option filter in second menu from 'basic' to 'all' " - or mentioning this point in some way.

**Comment by bitcrumb** [comment]
+1

Can't have clear enough instructions :)
