### ISSUE TITLE
Bluetooth is not supported in ios

### ISSUE THREAD

**Issue by amit2080799** [Polidea/react-native-ble-plx#283]
When I start device scan by calling the method startDevcieScan(), most of the time "bluetooth is not supported" alert comes. This happens only in ios. I am unable to figure out why its happening. 

Below is the code snippet:

`
        let that = this;
        let deviceList = [];
        let count = 0;

        that.manager.startDeviceScan(["1802"], null, (error, device) => {
            if (error) {
                try {
                    alert(`${error.message}`);
                    Log.info(`BLE scan error: ${error.message}`);
                } catch (e) {
                    Log.info(`BLE scan error: ${error}`);
                }
                return;
            }

            let localDeviceList = deviceList;
            let exists = false;

            localDeviceList.map((d) => {
                if (d.id == device.id) {
                    exists = true;
                }
            });

            if (!exists) {
                deviceList.push(device);
                this.homeScreen.setState({listBLEDevices: deviceList});
                let arr = this.homeScreen.state.availableDevices;
                arr.push({id: device.id, name: device.name, connected: false});
                this.homeScreen.setState({availableDevices: arr});
            }
        });
    };`

**Comment by twhitacre** [comment]
@amit2080799 are you running your code on an actual device or on a simulator?

**Comment by Mahaswami** [comment]
on actual device. This is the issue on all versions of ios.

**Comment by amit2080799** [comment]
On actual device.

**Comment by amit2080799** [comment]
the above code will work some times but most of the time it will throw alert saying "Bluetooth is not supported."

**Comment by twhitacre** [comment]
That's strange. I guess it could be the device you are using. 

I've been using [this library](https://github.com/nearit/react-native-connectivity-status) to check if Bluetooth is enabled and working, so I can alert the user before I try to connect. Maybe try that and see if your device is reporting that bluetooth is in fact working.

**Comment by amit2080799** [comment]
I tried in 2 3 devices which includes iphone 5s, 6s and an ipad.

**Comment by pvsong** [comment]
Same problem

**Comment by ioss** [comment]
Maybe a bit late, but did you check first, if the state is 'PoweredOn'? (you can request the current state, and also listen to state changes)
How soon after your app started is the above code run?
