### ISSUE TITLE
Pre-packaged frameworks

### ISSUE THREAD

**Issue by Looveh** [Polidea/react-native-ble-plx#29]
Installing this lib with `npm install` currently takes quite a bit of time, which will significantly increase the time taken to build/test projects with this lib as a dependency in CI processes where package caching isn't implemented.

Would it be possible to pre-package the frameworks used by this lib to speed up the installation?

**Comment by Cierpliwy** [comment]
Currently on our internal CI all packages in node_modules are cached between builds and only updated when there are changes detected in package.json file. 

However, I would love to package prebuild binaries, but unfortunately Swift frameworks currently don't have stable ABI (expected in Swift 4.x) and therefore I'm worried that they might not work when Xcode versions (and Swift compiler) will change in the future.
