### ISSUE TITLE
Can't disable console logs for Android

### ISSUE THREAD

**Issue by ericwhitefield** [Polidea/react-native-ble-plx#291]
Logcat is showing debug level log output from a release build. I'm trying to silence it.

Finding the exact source of the logs is difficult. I believe this project pulls com.polidea.rxandroidble:rxandroidble:1.4.3 from mavenCentral at build time, perhaps the log output is actually coming from there.

If that's true is it possible to silence the logs from the perspective of react-native-ble-plx?

Both projects react-native-ble-plx and RxAndroidBle mention that they have a log level mechanism and that the default setting is "None".

My ProGuard settings are configured to remove console logs but it seems to have no effect on these particular logs.

-assumenosideeffects class android.util.Log {
    public static int v(...);
    public static int d(...);
}
-assumenosideeffects class com.polidea.rxandroidble.internal.RxBleLog { 
	void log(...);
	void v(...);
	void d(...); 
}

example of some logs in logcat:

D BluetoothGatt: onClientConnectionState() - status=0 clientIf=6 device=10:02:C8:61:B4:26
D BluetoothGatt: discoverServices() - device: 10:02:C8:61:B4:26
D BluetoothGatt: onSearchComplete() = Device=10:02:C8:61:B4:26 Status=0
D BluetoothManager: getConnectionState()
D BluetoothManager: getConnectedDevices

**Comment by dariuszseweryn** [comment]
Hello,

The mentioned logs are not originating from the library but from the Android OS itself. There was [a similar bug reported](https://issuetracker.google.com/issues/37088105) already for scanning. Let's hope it will get fixed someday.

Best Regards
