### ISSUE TITLE
iOS Crash: dyld: Library not loaded: @rpath/libswiftSwiftOnoneSupport.dylib

### ISSUE THREAD

**Issue by chenbekor** [Polidea/react-native-ble-plx#294]
Starting a clean xcode **9.4.1** project. Followed the instructions (auto linking and continue manually from step 7 including alway embedding swift step). Project compiles but when run on simulator/actual device there is a crash with the following error:

```
dyld: Library not loaded: @rpath/libswiftSwiftOnoneSupport.dylib
  Referenced from: /.../Build/Products/Debug-iphonesimulator/BleClientManager.framework/BleClientManager
  Reason: image not found

**Comment by jacobkring** [comment]
I fixed a similar issue by updating xcode
