### ISSUE TITLE
Operation Timed out

### ISSUE THREAD

**Issue by HmFlashy** [Polidea/react-native-ble-plx#301]
Hi,

I am using a ble chip. It is using a specific communication protocol using hex format.
I saw that I have to encode the hex data into base64 format.
But I get an operation timed out.
I created a method that convert hex to base64 called hexToBase64 (it works).
For example one command is : 0x41 0x82 0x07 0x01 0x03
Do I have to convert all this line or send the data term by term like:
`device.writeCharacteristicWithResponseForService(
          service, characteristicW, this.hexToBase64("4182070103")
)`
OR
`device.writeCharacteristicWithResponseForService(
          service, characteristicW, this.hexToBase64("41")
)`
`device.writeCharacteristicWithResponseForService(
          service, characteristicW, this.hexToBase64("82")
)`
`device.writeCharacteristicWithResponseForService(
          service, characteristicW, this.hexToBase64("07")
)`
...
The device is responding right if I use another tool like hterm and send the data in raw Hex. So what am I doing wrong?

Thank you,
Regards,
Hugo Maitre

**Comment by Cierpliwy** [comment]
> It is using a specific communication protocol using hex format.

Does device accept hex data in string form? If that's true, why don't you use normal function to encode  to Base64? Are spaces or prefixes "0x" important? In case of "4182070103" it should be "NDE4MjA3MDEwMw==".

> Do I have to convert all this line or send the data term by term 
No, you shouldn't. It's a waste of bandwidth. Just keep in mind what your MTU limit is.
