### ISSUE TITLE
Is there a way to monitor when a connection is established?

### ISSUE THREAD

**Issue by ericschaal** [Polidea/react-native-ble-plx#302]
Hi!

Is there a way to monitor when a connection is established? This is useful when `autoConnect` is enabled to detect when a connection has been reestablished.

Thank you

**Comment by Cierpliwy** [comment]
According to RxAndroidBle documentation:

> Unlike the native Android API, if set to true [autoconnect] and the connection is lost there will NOT be any attempt to reconnect unless explicitly resubscribed.

So currently there is no need to monitor connection in current API. Correct me @dariuszseweryn if I'm wrong here.

**Comment by dariuszseweryn** [comment]
> According to RxAndroidBle documentation:
>
>> Unlike the native Android API, if set to true [autoconnect] and the connection is lost there will NOT be any attempt to reconnect unless explicitly resubscribed.
>
> So currently there is no need to monitor connection in current API. Correct me @dariuszseweryn if I'm wrong here.

Correct.
