### ISSUE TITLE
startDeviceScan() timeout

### ISSUE THREAD

**Issue by alfacommunication-alessandro** [Polidea/react-native-ble-plx#309]
When starting device scan I'm targetting a specific device. There is an option for timeout this function if after a while nothing is scanned? If not, there is a workaround?

Thanks

**Comment by paweljaneczek** [comment]
@alfacommunication-alessandro there is no `timeout` option for scanning. You can just create timeout by yourself in js and call `stopDeviceScan` after it

**Comment by alfacommunication-alessandro** [comment]
Yes, I did it. Thanks
