### ISSUE TITLE
[Android] Turn on Bluetooth

### ISSUE THREAD

**Issue by vikeri** [Polidea/react-native-ble-plx#31]
I don't know if this is in the scope of this library but it would be really nice to include in this library a function that enables/disables Bluetooth. I know this only works for Android but it would still be useful.

Found some examples here: http://stackoverflow.com/a/20142972/1836121

**Comment by Cierpliwy** [comment]
Thank you for a suggestion. I'll definitely add it to library.

**Comment by stinodes** [comment]
@Cierpliwy any news on this feature?

**Comment by Cierpliwy** [comment]
I don't have enough time right now to implement this feature. Also for 0.5 release I plan to focus on support for background mode, as it's very important for users of this library. I'll definitely welcome more contributions :)

**Comment by stinodes** [comment]
Alright, that's totally understandable of course.  
If it becomes a requirement from my side, I might do a pull request, but for now it's just a nice to have and pretty low priority.

**Comment by watadarkstar** [comment]
Did this ever make it in the code base? @Cierpliwy

**Comment by arashd** [comment]
No updates on this feature?

**Comment by watadarkstar** [comment]
I'm thinking of working on this issue on my free time! Will submit a pull request.

**Comment by saeedvaziry** [comment]
any updates?

**Comment by watadarkstar** [comment]
@saeedvaziry I started working on a PR but I still need to do some further testing. See: #138

**Comment by darkrift** [comment]
This option is not available on iOS, however for iOS we can make it so that it redirects to the control panel to enable it as described here : 

https://stackoverflow.com/a/36129124

To unify it, we should probably prompt the user on Android. I'm not a fan of applications enabling stuff in my back without asking me if I disabled it.

**Comment by brancooo1** [comment]
any news on this feature?

**Comment by JasiuHimself** [comment]
Any news?

**Comment by Cierpliwy** [comment]
@JasiuHimself Feature is implemented on the v1.0 branch. After proper testing, I plan to land it on the master.

**Comment by JasiuHimself** [comment]
Amazing, can't wait!

**Comment by brancooo1** [comment]
When is v1.0 expected to be public @Cierpliwy ?

**Comment by Cierpliwy** [comment]
[It is public :)](https://www.npmjs.com/package/react-native-ble-plx)

**Comment by manoj-makkuboy** [comment]
How to turn on the bluetooth, I am not able to find any function to do so in documentation.

**Comment by a1lu** [comment]
I found this (android only):
https://github.com/Polidea/react-native-ble-plx/blob/b4ccdf352f8ec06a718ef267ee7e31d7eabd87c6/src/BleManager.js#L225-L251

**Comment by Cierpliwy** [comment]
@a1lu It's only for Android, because iOS doesn't provide any API to do the same thing.
