### ISSUE TITLE
Library not loaded 

### ISSUE THREAD

**Issue by yonjuukyuu** [Polidea/react-native-ble-plx#310]
Have seen similar problems, but can't seem to find a solution, may you guys give me some ideas ? 

Print: https://gyazo.com/062db5d5ae3fc164feabd8ff052d2f54

dyld: Library not loaded: @rpath/BleClientManager.framework/BleClientManager
  Referenced from: /var/containers/Bundle/Application/467651F7-4605-4DCF-80FB-12AF59C0F46D/app.app/app
  Reason: image not found
(lldb)

**Comment by seanculver** [comment]
I'm also running into this problem.

**Comment by paweljaneczek** [comment]
@yonjuukyuu could you check if you have `BleClientManager` in `General->Linked Frameworks And Libraries`?

**Comment by kyle-ssg** [comment]
Seeing this too
