### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by axlider** [Polidea/react-native-ble-plx#311]
When I try to install react-native-ble-plx, I get this error.

the folder react-native-ble-plx is not even created under .../node_modules.

Thanks for any suggestions.

$ npm install --save react-native-ble-plx

> react-native-ble-plx@0.9.2 postinstall /Users/b9179/ws/wirt/node_modules/react-native-ble-plx
> node ./postinstall.js

*** Checking out RxBluetoothKit at "4.0.3"
*** Checking out RxSwift at "4.2.0"
*** xcodebuild output can be found in /var/folders/72/x41x98ls31x31nhb96q4ypr94c6xl1/T/carthage-xcodebuild.yCyrsY.log
*** Downloading RxBluetoothKit.framework binary at "4.0.3"
*** Downloading RxSwift.framework binary at "Zürich"
***  Skipped installing RxBluetoothKit.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2) and the local version is 3.1 (swiftlang-802.0.53 clang-802.0.42)."

    Falling back to building from the source
***  Skipped installing RxSwift.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2) and the local version is 3.1 (swiftlang-802.0.53 clang-802.0.42)."

    Falling back to building from the source
*** Building scheme "RxBlocking-iOS" in Rx.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/b9179/ws/wirt/node_modules/react-native-ble-plx/ios/BleClientManager/Carthage/Checkouts/RxSwift/Rx.xcworkspace -scheme RxBlocking-iOS -configuration Release -derivedDataPath /Users/b9179/Library/Caches/org.carthage.CarthageKit/DerivedData/8.3.2_8E2002/RxSwift/4.2.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/72/x41x98ls31x31nhb96q4ypr94c6xl1/T/RxSwift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/b9179/ws/wirt/node_modules/react-native-ble-plx/ios/BleClientManager/Carthage/Checkouts/RxSwift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/72/x41x98ls31x31nhb96q4ypr94c6xl1/T/carthage-xcodebuild.yCyrsY.log
Error: "carthage bootstrap --platform iOS"  command failed with status=1
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "react-native-ble-plx"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! react-native-ble-plx@0.9.2 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-native-ble-plx@0.9.2 postinstall script 'node ./postinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-native-ble-plx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./postinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-native-ble-plx
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-native-ble-plx
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/b9179/ws/wirt/npm-debug.log
mntbden00097468:wirt b9179$ more /var/folders/72/x41x98ls31x31nhb96q4ypr94c6xl1/T/carthage-xcodebuild.yCyrsY.log
/usr/bin/xcrun xcodebuild -workspace /Users/b9179/ws/wirt/node_modules/react-native-ble-plx/ios/BleClientManager/Carthage/Checkouts/RxSwift/Rx.xcworkspace -scheme RxBlocking-iOS -configuration Release -derivedDataPath /Users/b9179/Library/Caches/org.carthage.CarthageKit/DerivedData/8.3.2_8E2002/RxSwift/4.2.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/72/x41x98ls31x31nhb96q4ypr94c6xl1/T/RxSwift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/b9179/ws/wirt/node_modules/react-native-ble-plx/ios/BleClientManager/Carthage/Checkouts/RxSwift)User defaults from command line:
    IDEArchivePathOverride = /var/folders/72/x41x98ls31x31nhb96q4ypr94c6xl1/T/RxSwift
    IDEDerivedDataPathOverride = /Users/b9179/Library/Caches/org.carthage.CarthageKit/DerivedData/8.3.2_8E2002/RxSwift/4.2.0

Build settings from command line:
    CARTHAGE = YES
    CLANG_ENABLE_CODE_COVERAGE = NO
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos10.3
    SKIP_INSTALL = YES
    STRIP_INSTALLED_PRODUCT = NO

2018-07-26 16:34:46.242 xcodebuild[70762:3155263] CoreSimulatorService connection became invalid.  Simulator services will no longer be available.
2018-07-26 16:34:46.244 xcodebuild[70762:3155264]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-12109/IDEiOSSupportCore/DVTiPhoneSimulatorLocator.m:105
Details:  [SimServiceContext defaultDeviceSetWithError:] returned nil (Error Domain=NSPOSIXErrorDomain Code=53 "Software caused connection abort" UserInfo={NSLocalizedFailureReason=Failed to subscribe to notifications from CoreSimulatorService., NSLocalizedDescription=Failed to initialize simulator device set., NSUnderlyingError=0x7fd6704351b0 {Error Domain=NSPOSIXErrorDomain Code=53 "Software caused connection abort" UserInfo={NSLocalizedDescription=Error returned in reply to notification request: Connection invalid}}}). Simulator device support disabled.
Object:   <DVTiPhoneSimulatorLocator: 0x7fd672c61fb0>
Method:   -startLocating
Thread:   <NSThread: 0x7fd670400b00>{number = 3, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2018-07-26 16:34:46.254 xcodebuild[70762:3155264] CoreSimulatorService connection became invalid.  Simulator services will no longer be available.
--- xcodebuild: WARNING: Unable to open project file '/Users/b9179/ws/wirt/node_modules/react-native-ble-plx/ios/BleClientManager/Carthage/Checkouts/RxSwift/Rx.playground' in workspace '/Users/b9179/ws/wirt/node_modules/react-native-ble-plx/ios/BleClientManager/Carthage/Checkouts/RxSwift/Rx.xcworkspace'.
=== BUILD TARGET RxSwift-iOS OF PROJECT Rx WITH CONFIGURATION Release ===

Check dependencies
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
warning: no umbrella header found for target 'RxSwift-iOS', module map will not be generated

** ARCHIVE FAILED **

The following build commands failed:
        Check dependencies
(1 failure)

**Comment by paweljaneczek** [comment]
@axlider it looks like you have swift version 3.1 and library is written in swift 4.1.2. You would need to either update your project to use newest swift (which is recommended) or use older version of library (some between 0.6.5 -0.5.0)

**Comment by Cierpliwy** [comment]
@axlider Or try using version 0.10.0 which doesn't require frameworks to work.

**Comment by axlider** [comment]
Thanks both of you!
 I'll give it a try.

**Comment by vijay-chavakula** [comment]
installing this in the root of the project solved my problem:
 npm i --save github:facebook/react-native#master
then run react-native link <packagename>
