### ISSUE TITLE
react_native_ble_plx_swift.modulemap' not found

### ISSUE THREAD

**Issue by hamishwebb** [Polidea/react-native-ble-plx#316]
I keep getting this error when building in xcode:

<unknown>:0: error: module map file '/Users/.../Library/Developer/Xcode/DerivedData/...-ddineicerhcwzmemgxqivvkqammg/Build/Products/Debug-iphonesimulator/react-native-ble-plx-swift/react_native_ble_plx_swift.modulemap' not found

as well as:

<unknown>:0: error: failed to emit precompiled header '/Users/.../Library/Developer/Xcode/DerivedData/...-ddineicerhcwzmemgxqivvkqammg/Build/Intermediates.noindex/PrecompiledHeaders/...-Bridging-Header-swift_1YY2538E66OCR-clang_11Y2ANE0GION0.pch' for bridging header '/Users/.../.../.../ios/...-Bridging-Header.h'

I'm new to working with xcode, which may be the problem, I come from a javascript background.

**Comment by Avinash-Setty** [comment]
Even I am facing the same issue. Any help will be appreciated.

**Comment by hamishwebb** [comment]
By using a pure React Native build everything worked fine, the above was when using Expo.

**Comment by Cierpliwy** [comment]
Closing as the author solved the issue.

**Comment by TrebuhD** [comment]
My xcode build works fine, but I get the above error when building with fastlane.

```
<unknown>:0: error: module map file '/Users/../Library/Developer/Xcode/DerivedData/NotaNota-hcfeypxdnfwftnexobelztcqblci/Build/Intermediates.noindex/ArchiveIntermediates/NotaNota (staging)/BuildProductsPath/Release-iphoneos/react-native-ble-plx-swift/react_native_ble_plx_swift.modulemap' not found
<unknown>:0: error: module map file '/Users/../Library/Developer/Xcode/DerivedData/NotaNota-hcfeypxdnfwftnexobelztcqblci/Build/Intermediates.noindex/ArchiveIntermediates/NotaNota (staging)/BuildProductsPath/Release-iphoneos/react-native-ble-plx-swift/react_native_ble_plx_swift.modulemap' not found
```

**Comment by jogboms** [comment]
@TrebuhD did you by any chance manage to solve your issue?

**Comment by smarchante1** [comment]
Currently having issues with this very thing. Would be nice to know the solution OP found!

**Comment by ustincameron** [comment]
Why is this closed? This is happening without Expo.

**Comment by mi-mazouz** [comment]
still having this issue!

**Comment by echezbro** [comment]
?

**Comment by nandorojo** [comment]
I'm having this issue with a bare workflow Expo project. It's running fine when doing `react-native run-ios`, but if I try to run from xCode, I get these errors.

**Comment by LondonX** [comment]
open `.xcworkspace` insted of `.xcodeproj` works for me.

**Comment by Ailton265** [comment]
I have the same issue. any one found workround?
