### ISSUE TITLE
[Android] Incorrectly getting Bluetooth Powered off error

### ISSUE THREAD

**Issue by vikeri** [Polidea/react-native-ble-plx#32]
Sometimes when trying to reconnect to a device I get the following error:
```
{message: "Bluetooth is powered off", code: 102}
```
Even though the Bluetooth is definitely on. It also results in me not being able to reconnect.

**Comment by Cierpliwy** [comment]
Hello,

I will try to update RxAndroidBle backend to new 1.1.0 version and then we will see if it's still reproducible.

**Comment by vikeri** [comment]
Great!

**Comment by Cierpliwy** [comment]
Could you check latest 0.5.0 version?

**Comment by vikeri** [comment]
Sorry, moved to another library so not using this atm

**Comment by Cierpliwy** [comment]
Closing as this is an overdue issue. Please feel free to reopen if you tested it with the latest version of a library.
