### ISSUE TITLE
isWritable fields false

### ISSUE THREAD

**Issue by onuroo** [Polidea/react-native-ble-plx#321]
Services function returns isWritableWithResponse and isWritableWithoutResponse is false

Therefore can not write anything with writeCharacteristicWithResponseForDevice.
writeCharacteristicWithResponseForDevice gives error " Operation was rejected "

![whatsapp image 2018-08-15 at 15 15 26](https://user-images.githubusercontent.com/5569462/44147796-4ddadd30-a09e-11e8-8ae5-adab3551ba3b.jpeg)

How I can change this fields and write something ? Thanks.

**Comment by darkrift** [comment]
From what I can find, you are trying to write in a characteristic that represents the "Device name" which is fair to be not writable.

**Comment by onuroo** [comment]
Yes you are right. But I wonder why this fields return false ?

**Comment by darkrift** [comment]
Because this is a field that cannot be written to in order to update it but only be read from, in other words readonly.

**Comment by Cierpliwy** [comment]
I think that this was answered by @darkrift clearly. Thanks!
