### ISSUE TITLE
How can I subscribe to activate the sound?

### ISSUE THREAD

**Issue by NdozHH** [Polidea/react-native-ble-plx#323]
Hello, if I have this feature that corresponds to my device alarm (TrackR Bravo), how can I subscribe to activate the sound?

![imagen](https://user-images.githubusercontent.com/25773289/44304605-10c17a00-a326-11e8-8f32-f40444be0580.png)

**Comment by NdozHH** [comment]
![imagen](https://user-images.githubusercontent.com/25773289/44320815-e8ab4700-a409-11e8-9380-d1e9ec8ad853.png)

The device has this service, when used with the nrf connect application, the sound is triggered, but I don't know how to do it using RN ble plx. I'm using this code but nothing happens

`ring = () => {
     this.manager.writeCharacteristicWithoutResponseForDevice(this.state.mydevice.id,'1802','2a06','MDI=').then((res) => {
        console.dir("res",res);
      }).catch((error) => {
        console.dir(error)
      })
}`

and this is the log output
![imagen](https://user-images.githubusercontent.com/25773289/44320915-7dae4000-a40a-11e8-878a-e6571aa98d12.png)

**Comment by Cierpliwy** [comment]
Please ask about library usage on [Gitter](https://gitter.im/RxBLELibraries/react-native-ble) channel.
