### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_BleModule.BleModule.createClient')

### ISSUE THREAD

**Issue by SergeyMyssak** [Polidea/react-native-ble-plx#324]
I'm new to this library. I've done all steps written in this site (https://github.com/Polidea/react-native-ble-plx) successfully. I get this error all the time: TypeError: undefined is not an object (evaluating '_BleModule.BleModule.createClient'). Here is my project at github: https://github.com/SergeyMyssak/BluetoothInit

How to solve this problem?

**Comment by Esxiel** [comment]
I'm also in the same rut, I detached my project from Expo, and I did all the steps written https://github.com/Polidea/react-native-ble-plx#android, including the react-native-link that people keep missing.

**Comment by AlexKotov** [comment]
Guys, using `react-native link` doesn't add `new BlePackage()` to `MainApplication.java`. Please, fix this.

**Comment by Cierpliwy** [comment]
I tested `react-native link` both on normal RN project as well as on detached Expo. It works fine. Please reopen if there are any other problems around this issue.

**Comment by shinstev** [comment]
@Esxiel how did you fix this problem? I get the error when I publish to expo
