### ISSUE TITLE
Delay before device.onDisconnected is fired

### ISSUE THREAD

**Issue by designingSparks** [Polidea/react-native-ble-plx#329]
My simplified code is as follows:

this.manager
        .connectToDevice(id)
        .then(device => {
          device.onDisconnected((error, disconnectedDevice) => {
            console.log("Disconnected ", disconnectedDevice.name);
          });

However there is approximately a 10s delay between turning of the physical device and the onDisconnected listener being called. Is there any possibility of decreasing the delay?

**Comment by Cierpliwy** [comment]
It's better to monitor disconnection before `connectToDevice` call as otherwise there might be a race condition. Actual disconnection event depends on `Connection supervision timeout`, which is configured on the firmware side. Nothing can be done about it with current API on iOS or Android.
