### ISSUE TITLE
[Feature Request] Throw an error when calling characteristic.write*() functions without a properly encoded string

### ISSUE THREAD

**Issue by Barbiero** [Polidea/react-native-ble-plx#333]
I know this is kinda dumb but I just spent more time than I'd like to admit having an issue with a device, where the only error was that I did this:

```typescript
    const buffer = Buffer.alloc(1)
    buffer.writeUInt8(130, 0)
    await manager.writeCharacteristicWithResponseForDevice(
      deviceId,
      ServiceUUID,
      CharacteristicUUID,
      buffer.toString(),
    )
```

when the correct implementation was:

```typescript
    const buffer = Buffer.alloc(1)
    buffer.writeUInt8(130, 0)
    await manager.writeCharacteristicWithResponseForDevice(
      deviceId,
      ServiceUUID,
      CharacteristicUUID,
      buffer.toString('base64'),
    )
```

I know how dumb that looks, and I'm so mad at myself for not noticing it earlier, but I believe that since the library *needs* to use Base64-encoded strings(due to limitations of RN I believe?), it should throw an error when it tried to write a non-base64 string. Hopefully that'd save time for future developers to not fall into the same trap I fell.

Thank you for your time, and thank you for your library by the way. It's great.

**Comment by Cierpliwy** [comment]
The documentation mentions that. Additionally, if you have Flowtype configured in your IDE it hints you about that as well. I'm not sure what can I do more about it.

Thanks for kind words :)
