### ISSUE TITLE
not discover service 00001801-0000-1000-8000-00805f9b34fb

### ISSUE THREAD

**Issue by iwater** [Polidea/react-native-ble-plx#335]
00001801-0000-1000-8000-00805f9b34fb can listed by gatttool, but not discoverd by react-native-ble-plx

**Comment by Cierpliwy** [comment]
I assume you are talking about iOS here. Operating system hides `00001801-0000-1000-8000-00805f9b34fb` and few others characteristic/descriptors as they are fully managed by it.
