### ISSUE TITLE
Bluetooth connection instable with Android Outdoor Phones

### ISSUE THREAD

**Issue by modmido** [Polidea/react-native-ble-plx#342]
Hello, i wrote an app that connects to an external ble device. It works pretty well on iPhones and common Android phones such as Samsung, Sony etc. but i'm having trouble with two somewhat exotic outdoor phones: Cubot KingKong (2018) and Blackview BV 6000. Connecting usually works but the routines device.discoverAllServicesAndCharacteristics() and device.writeCharacteristicWithResponseForService() are extremely slow and unstable. They work at most 1 out of 10 times. Do you have any ideas what could be the issue? I am using react-native-ble-plx 0.10.0

**Comment by Cierpliwy** [comment]
Please try connectivity and characteristic write with nRF Connect application if you can. See if it responds similarly.
