### ISSUE TITLE
Get list of connected / known BLE devices

### ISSUE THREAD

**Issue by zhanguangao** [Polidea/react-native-ble-plx#35]
Can I get the connected Bluetooth device informations without any parameters ,and the device is  connected manually in system setting.

**Comment by Cierpliwy** [comment]
If you mean normal Bluetooth devices I think it is currently impossible to do.

**Comment by sikhote** [comment]
@Cierpliwy what about a BLE device that is paired within the system bluetooth settings? Possibly attain a list of paired devices?

Thanks for the great library.

**Comment by Cierpliwy** [comment]
There is possibility to add functions:

- `function knownDevices(): Promise<Array<Device>>`
- `function connectedDevices(): Promise<Array<Device>>`

There are native counterparts on iOS side. On Android we could use internal caches for that purpose.

**Comment by Cierpliwy** [comment]
```js
async devices(deviceIdentifiers: Array<DeviceId>): Promise<Array<Device>> 
```
and
```js
async connectedDevices(serviceUUIDs: Array<UUID>): Promise<Array<Device>>
```
were added in version 0.9

**Comment by bhenav** [comment]
Hi,

**Error**: knownDevices is not a function. 

Are you sure this is the best?
Can you write an example?

Thank you,
bhenav

**Comment by askesis** [comment]
Hi, @Cierpliwy !

Is it possible to interact with paired (via OS, only android interesting for me) device through the package?

```js 
async devices(deviceIdentifiers: Array<DeviceId>): Promise<Array<Device>>
```
and other your example get required argument, but I don't know of devics UUID or something else...

Looks like I should know information about device earlier then use this package

**Comment by fitbuff** [comment]
i also would like to interact with paired device (connected via Bluetooth System Settings).
is this possible with this package?
