### ISSUE TITLE
Unable to monitor peripheral on android

### ISSUE THREAD

**Issue by vaukalak** [Polidea/react-native-ble-plx#351]
I've created an android app to make it easy to emulate behavior of target ble device. I've configured it in following way:
```
        UUID CHAR_UUID = UUID.fromString(uuid);
        BluetoothGattCharacteristic tempChar = new BluetoothGattCharacteristic(
                CHAR_UUID,
                BluetoothGattCharacteristic.PROPERTY_NOTIFY |
                        BluetoothGattCharacteristic.PROPERTY_INDICATE |
                        BluetoothGattCharacteristic.PROPERTY_READ |
                        BluetoothGattCharacteristic.PROPERTY_WRITE_NO_RESPONSE |
                        BluetoothGattCharacteristic.PROPERTY_WRITE,
                BluetoothGattCharacteristic.PERMISSION_READ
        );
        BluetoothGattDescriptor gD = new BluetoothGattDescriptor(
                CHAR_UUID,
                BluetoothGattDescriptor.PERMISSION_READ
        );
        gD.setValue(BluetoothGattDescriptor.ENABLE_NOTIFICATION_VALUE);
        tempChar.addDescriptor(gD);
        this.servicesMap.get(serviceUUID).addCharacteristic(tempChar);
```
So I'm able to locate this device, locate services and characteristics. I'm also able to read from characteristic:
![47473565-cd9af000-d81b-11e8-9b58-69458efc9c20](https://user-images.githubusercontent.com/1864367/47584635-c252dc00-d963-11e8-8d7a-18d143d607a3.png)
 
But if I try to monitor it, I get 
```
Error: Characteristic $myCharId notify change failed for device ? and service $myServiceId
```
Android application invokes my mock function for `mtu`:
```
        @Override
        public void onMtuChanged(BluetoothDevice device, int mtu) {

        }
```
after that ios application (that I'm using as master, receive error in callback I've passed to `monitor`). I'm not sure if I need to handle somehow in `onMtuChanged` or in `react-native-ble-plx` configuration. Any advices are welcome.
Thanks.

**Comment by dariuszseweryn** [comment]
You probably would like to ask Google about an example of [how to implement Android BLE Server](https://www.google.com/search?q=android+ble+server+example)

From what I can quickly see you have setup permissions wrong. Either way this is not a problem with the library
