### ISSUE TITLE
issues installing

### ISSUE THREAD

**Issue by ErreMalote** [Polidea/react-native-ble-plx#36]
tall"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! react-native-ble-plx@0.3.3 postinstall: `bash build_ios_frameworks.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-ble-plx@0.3.3 postinstall script 'bash build_ios_frameworks.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-native-ble-plx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bash build_ios_frameworks.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-native-ble-plx
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-native-ble-plx
npm ERR! There is likely additional logging output above.

**Comment by ErreMalote** [comment]
Solved by using Git BASH. Windows doesn't support .sh files on command line.

**Comment by Cierpliwy** [comment]
I'll definitely check out and fix that issue on Windows.

**Comment by albert-l-garrett** [comment]
I found this solution. 
http://www.windowscentral.com/how-install-bash-shell-command-line-windows-10

**Comment by marwakhalil** [comment]
Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "react-native-ble-plx"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! react-native-ble-plx@0.4.0 postinstall: `bash build_ios_frameworks.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-native-ble-plx@0.4.0 postinstall script 'bash build_ios_frameworks.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-native-ble-plx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bash build_ios_frameworks.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-native-ble-plx
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-native-ble-plx
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/marwazribi/.npm/_logs/2017-05-05T14_59_43_032Z-debug.log

and i'm a mac user

**Comment by Cierpliwy** [comment]
Can you check version 0.5.0 if this still happens?

**Comment by BAVhel** [comment]
132426 verbose stack Error: react-native-ble-plx@0.6.0 postinstall: `bash build_ios_frameworks.sh`

**Comment by Cierpliwy** [comment]
Is it your full error? Can you enter library directory and run this script by hand?:
```
cd ./node_modules/react-native-ble-plx/
./build_ios_frameworks.sh
```

**Comment by BAVhel** [comment]
@Cierpliwy I ran the script on windows and I cant run sh without bash.

**Comment by Cierpliwy** [comment]
Probably I will need to create node based script to be platform agnostic. If you want this feature faster, maybe you can tackle this problem and send me PR?

**Comment by BAVhel** [comment]
@Cierpliwy I have the same error on examples/ReactBLEScanner

**Comment by jiazil** [comment]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-ble-plx@0.6.1 postinstall: `bash build_ios_frameworks.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-ble-plx@0.6.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by jiazil** [comment]
xcode 9
