### ISSUE TITLE
how to set up  a GattServer ?

### ISSUE THREAD

**Issue by NU11B0T** [Polidea/react-native-ble-plx#360]
I want to Implement Proximity Alert Feature using Immediate Alert Service 0x1802. 

nrf Toolbox Android code
https://github.com/NordicSemiconductor/Android-nRF-Toolbox/blob/master/app/src/main/java/no/nordicsemi/android/nrftoolbox/proximity/ProximityService.java

nrf Toolbox ios code 
https://github.com/NordicSemiconductor/IOS-nRF-Toolbox/blob/master/nRF%20Toolbox/PROXIMITY/NORProximityViewController.swift#L125

**Comment by Cierpliwy** [comment]
This library doesn't support Peripheral role. You wont' be able to do what you want.
