### ISSUE TITLE
How to use writeCharacteristicWithResponseForDevice()?

### ISSUE THREAD

**Issue by whhotw** [Polidea/react-native-ble-plx#368]
I didn't way is right that write hex string to my board, anybody know that? i did a test my board by free BLE scanner, it's work.
Please refer screenshot that write '1b01' hex string. how can i do same thing on my app?
![screen shot 2018-11-22 at 00 00 20](https://user-images.githubusercontent.com/6612648/48853525-aae40300-edea-11e8-8e77-199e0c7db08f.png)

it's a BLE scanner _NOT_ my app, just for test
![img_1444](https://user-images.githubusercontent.com/6612648/48853527-addef380-edea-11e8-8a98-ae0f9f957977.PNG)

**Comment by Cierpliwy** [comment]
Values are accepted in Base64 format, so you need to convert your hexadecimal string representation to Base64 in:

- binary form: `1B02` is equal to `GwI=`. 
- string form: `1B02` -> `31423032` -> `MUIwMg==` / `MUIwMgA=` (null terminated)

**Comment by whhotw** [comment]
@Cierpliwy it's work, thank you so much!
