### ISSUE TITLE
Could not find method implementation() for arguments 

### ISSUE THREAD

**Issue by umakantp** [Polidea/react-native-ble-plx#370]
Using version 1.0.0 of react-native-ble-plx

1. react-native-ble-plx: 1.0.0
2. React native: 0.57.5
3. Gradle wrapper: 4.4
4. com.android.tools.build:gradle:2.3.3
5. buildToolsVersion "25.0.1"

I kept getting :-1: 

```
* What went wrong:
A problem occurred evaluating project ':react-native-ble-plx'.
> Could not find method implementation() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

If I rollback classpath to com.android.tools.build:gradle:2.2.3

I keep getting:

```
* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V
```

**Comment by Cierpliwy** [comment]
I updated https://github.com/Cierpliwy/SensorTag to RN 0.57.5 and it works just fine. With 1.x you need to use gradle `classpath 'com.android.tools.build:gradle:3.1.4'` defined in `android/build.gradle`. Make sure to use new implementation API as well.
