### ISSUE TITLE
Error: Couldn't find preset "module:metro-react-native-babel-preset"

### ISSUE THREAD

**Issue by izaxon** [Polidea/react-native-ble-plx#377]
When trying to build the app for Android at `appcenter.ms` and locally (with `react-native run-android`) I get the following error:

`error: bundling failed: Error: Couldn't find preset "module:metro-react-native-babel-preset" relative to directory "C:\\Users\\johan\\source\\repos\\gobius-app\\node_modules\\react-native-ble-plx"`

I have a reference to version 1.0.1 of react-native-ble-plx in package.json.

**Comment by BenjaminHabert** [comment]
This issue was also reported elsewhere: https://github.com/facebook/react-native/issues/21241
