### ISSUE TITLE
Connecting with Mobile Bluetooth device

### ISSUE THREAD

**Issue by UdayKandpal** [Polidea/react-native-ble-plx#378]
1. How to pair a mobile device using passcode ?
2. Many devices show their name as null.
3. How to send sensor data via bluetooth? Here sensor data means data sent by mobile with the help of sensors.

**Comment by dariuszseweryn** [comment]
> How to pair a mobile device using passcode ?

It's usually handled by the OS

> Many devices show their name as null.

That is because they do not advertise any

> How to send sensor data via bluetooth? Here sensor data means data sent by mobile with the help of sensors.

Check samples and/or documentation. I am assuming your peripheral is a BLE device
