### ISSUE TITLE
[Android] add support for allowDuplicates flag on scan

### ISSUE THREAD

**Issue by Sanjeevs1995** [Polidea/react-native-ble-plx#382]
allowDuplicates not getting set to false in android while it is default false in iOS

`this.manager.startDeviceScan(null, {allowDuplicates:false}, (error, device) => { 
//2nd parameter is scanOptions
        if (error) {
            // Handle error (scanning will be stopped automatically)
            return
        }
       this.state.count++
        if(this.state.count>10)
        {
          this.manager.stopDeviceScan();
        }
        console.log("id",device.id) 
}`

**Comment by dariuszseweryn** [comment]
This is [exactly as advertised](https://github.com/Polidea/react-native-ble-plx/wiki/Bluetooth-Scanning).

I am marking this as a feature request and hopefully someone will help
