### ISSUE TITLE
Monitor not being called when AppState is background on iOS

### ISSUE THREAD

**Issue by dested** [Polidea/react-native-ble-plx#383]
I am seeing a strange behavior on iOS where:

1. I `monitorCharacteristicForService` in foreground
2. I start a timeout of say 10 seconds
3. I put the app in the background 5 seconds in 
4. My setTimeout fires on time
5. I `writeCharacteristicWithoutResponseForService` 
6. The monitor never comes back with the expected result

If I follow these exact steps without putting the app in the background everything executes as expected. Is this a known behavior or do you suspect something else is happening that I am leaving out? I have solved it by checking my current `AppState` before I write the characteristic, but it was rough to track down.

**Comment by dariuszseweryn** [comment]
Are you sure that `setTimeout` does work? The default timeout mechanism stops working while the RN app is in background.

**Comment by dested** [comment]
If I have the app in the background for just a few seconds it is keeping my thread alive. After that it sleeps accordingly. I will try to write up an expo app with this behavior in a few days.
