### ISSUE TITLE
How to use hands free bluetooth? 

### ISSUE THREAD

**Issue by AideProjet** [Polidea/react-native-ble-plx#384]
Hi, 

We're trying to use this library inside an app made to be used in a car.

We want to listen to audio messages with the car's bluetooth and record the radio at the same time (with the phone mic). 

Problem is, we seem to be unable to record radio and use bluetooth at the same time. 

We believe hands free protocol might be a solution, I couldn't find any information on its use with this library, any idea? 

Thanks!

**Comment by dariuszseweryn** [comment]
Why do you think it is an issue with the library?

**Comment by AideProjet** [comment]
Hey, thanks for your answer. 

I don't think it's an issue, sorry if I'm in the wrong category, I want to know how to switch from A2DP protocol to HFP protocol with the library, any idea? 

Thanks

**Comment by dariuszseweryn** [comment]
This is a BLE library (hence `react-native-ble-plx`) it has no support for A2DP and I have no information about HFP but I doubt it is implemented on BLE

**Comment by AideProjet** [comment]
Ok, my bad, any chance you have knowledge of a way to have support A2DP/Hands Free Protocol with React Native? 

Thanks

**Comment by dariuszseweryn** [comment]
Unfortunately not

**Comment by AideProjet** [comment]
Ok thanks man
