### ISSUE TITLE
@types/react-native-ble-plx

### ISSUE THREAD

**Issue by danielfssz** [Polidea/react-native-ble-plx#386]
"react": "16.6.3"
"react-native": "0.57.8"

I can not import the module that was installed via 'npm install react-native-ble-plx'.

![image](https://user-images.githubusercontent.com/22052403/50704927-34b8fa00-1040-11e9-87ca-bd3379a24e4a.png)

When I try to install via npm install @ types / react-native-ble-plx, the package is not found

![image](https://user-images.githubusercontent.com/22052403/50705087-c88ac600-1040-11e9-8d72-37e46053a404.png)

Could someone help me, please?

**Comment by Sean-Brown-Digi** [comment]
Two solutions:

1. (easiest) create a declaration file (e.g. `app.d.ts`) and add the app declaration there: `declare module 'react-native-ble-plx';`. The downside to this is that you don't get any intellisense.
2. (more difficult) create the actual typescript definition file and merge it into the DefinitelyTyped repository (https://github.com/DefinitelyTyped/DefinitelyTyped)
