### ISSUE TITLE
Could not run example

### ISSUE THREAD

**Issue by ithieund** [Polidea/react-native-ble-plx#387]
I pulled the fresh repository, go to example folder and type react-native android-run and this error display:

Android project not found. Maybe run react-native android first?

I also tried to run npm install and lots of errors display:
<img width="396" alt="screenshot at jan 06 15-07-08" src="https://user-images.githubusercontent.com/4217195/50733689-c6517480-11c4-11e9-8e46-0cac3015829c.png">

Could you help?

**Comment by ithieund** [comment]
@userException ,
It does not work
<img width="392" alt="screenshot at jan 12 09-55-43" src="https://user-images.githubusercontent.com/4217195/51068415-4b6adc80-1650-11e9-8579-e35c4538921b.png">

**Comment by dariuszseweryn** [comment]
The example folder inside the library is not maintained for a long time already. [The official docs](https://github.com/Polidea/react-native-ble-plx#configuration--installation) have links to other projects that use this library though.

**Comment by ithieund** [comment]
> The example folder inside the library is not maintained for a long time already. [The official docs](https://github.com/Polidea/react-native-ble-plx#configuration--installation) have links to other projects that use this library though.

Thanks for pointing out.
I think that link should be state obviously in Example section, and the example folder should be remove d to prevent confusion.

**Comment by Cierpliwy** [comment]
Example is already removed from the repo. Closing.
