### ISSUE TITLE
[iOS] Immediate disconnect after reconnect in background

### ISSUE THREAD

**Issue by RocketPuppy** [Polidea/react-native-ble-plx#389]
On iOS I ran the following experiment and received a counter-intuitive result:

1. Connect a device via scanning and connecting.
2. Power off the device to trigger a disconnect.
3. Put app in background and attempt to directly connect to the device using `device.connect()`. This should not timeout as specified in the core bluetooth docs (https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/CoreBluetoothBackgroundProcessingForIOSApps/PerformingTasksWhileYourAppIsInTheBackground.html#//apple_ref/doc/uid/TP40013257-CH7-SW5).
    > At this point, the app can simply call the connectPeripheral:options: method of the CBCentralManager class, and because connection requests do not time out, the iOS device will reconnect when the user returns home
4. Power on the device after some time.

At this point the device is successfully reconnected, but is immediately disconnected afterwards. Upon reconnection I issue `discoverAllServicesAndCharacteristics`. The immediate disconnection seems undesirable and unexpected to me.

I was able to prevent the immediate disconnection by including a `restoreStateIdentifier` in the `BleManager` initialization.

I don't know if this is a bug in code, but it is definitely a bug in documentation. I'm happy to correct documentation but would appreciate a pointer to the document needing correcting.

**Comment by Cierpliwy** [comment]
Can you send me logs from XCode console? I'm mostly interested how native callbacks were invoked and what methods were called.
