### ISSUE TITLE
Reading or Writing Characteristics Asynchronously hangs on Android

### ISSUE THREAD

**Issue by jkpvecino** [Polidea/react-native-ble-plx#391]
Currently trying to debug a React Native app that's trying to write and read some set of values to devices. Previously, I was writing and reading with minor problems (I had to make the reads asynchronous to ensure that the app did not continue), however, since then, I've been having problems with both reading and writing characteristics. At first I was able to read characteristics fine, and then read only once, and then it would hang, and eventually writing characteristics would also hang, resulting in no promise. I'm confirming that on the device firmware that the values are being written correctly, but no promise is occurring on the app side. Are there any known solutions or similar problems that I can be pointed to? I'm at a loss at the moment as to what has caused this.

EDIT: Now I'm finding cases where sometimes writing completes and sometimes it does not. I don't understand why there is so much variability to the responses given that there shouldn't be a race condition here. Doing it synchronously doesn't change anything either.

**Comment by Cierpliwy** [comment]
Could you provide code samples and testing scenario? Are you debugging RN app by stopping its execution on web browser or you are doing something else (ex debugging in Android Studio)?
