### ISSUE TITLE
How do i continuously read data sent by the ble device?

### ISSUE THREAD

**Issue by Dhiraj2996** [Polidea/react-native-ble-plx#392]
I am able to connect to device and also perform write operation.My device is continuously sending data,but how do I read that data continously?

**Comment by dariuszseweryn** [comment]
> how do I read that data continously?

You start monitoring the characteristic that sends the data

**Comment by Dhiraj2996** [comment]
Hey thanks for the reply! So i am looking for notifiable characteristics,but there are more than one available. This is my function to find characteristic to monitor.
Is there a way to find the required characteristic without hard coding uuid (as it may be used for other ble devices)?
` getNotifyServicesAndCharacteristics(device) {
    return new Promise((resolve, reject) => {
      device.services().then(services => {
        const characteristics = []

        services.forEach((service, i) => {
          service.characteristics().then(c => {
            characteristics.push(c)

            if (i === services.length - 1) {
              const temp = characteristics.reduce((acc, current) => {
                return [...acc, ...current]
              }, [])
              const dialog = temp.find(
                characteristic => characteristic.isNotifiable
              )
              if (!dialog) {
                reject('No notifiable characteristic')
              }
              resolve(dialog)
            }
          })
        })
      })
    })
  }`
thanking you in advance!

**Comment by dariuszseweryn** [comment]
> Is there a way to find the required characteristic without hard coding uuid (as it may be used for other ble devices)?

You usually identify a characteristic by UUID because you as the user of the library know what you are looking for and how to interpret the received data. Alternatively you can iterate and filter the discovered characteristics in any way you want

I hope this answers your question

**Comment by yangchange** [comment]
hey, maybe it is late but you solved your problem?
