### ISSUE TITLE
General question - swift & objective-c

### ISSUE THREAD

**Issue by assafb81** [Polidea/react-native-ble-plx#393]
Hi @Cierpliwy 
First let me say that its great package and I use it in my app.
I wanted to check with much more generic issue even though its not the place for this kind of questions.

I noticed that your application is written in `swift` and I would like to understand the flow that you did because I am having issue.

My flow is as follow:
1. I have my app written in `react-native v0.57.8`
2. Create new library using `react-native-create-library`
3. Migrate `objective-c` files and to `swift` + create `libName-Bridging-Header.h`
4. `yarn install` and `react-native link libName` in my react native app
5. Build the app in `Xcode 10.1` **<- this step fails due to swift issues**

What I need to do differently?

Thanks
Asaf

**Comment by Cierpliwy** [comment]
Hey, thanks for kind words :) I didn't use any utility tools to create this package as it's quite old. RN website has great tutorial about creating libraries in Swift: https://facebook.github.io/react-native/docs/native-modules-ios. If you have any particular issue, you can send me specific errors. I probably won't have time to setup similar configuration by myself.

I will close this issue as it's not directly related to this library, but feel free to post more questions under my comment.
