### ISSUE TITLE
Can detect all devices 

### ISSUE THREAD

**Issue by omaralanei** [Polidea/react-native-ble-plx#395]
When i try to get all the nearest devices, i get only one device and a lot of null values

**Comment by Cierpliwy** [comment]
Can you describe your problem better? What platform is it? Example code and detailed logs are needed to help you.

**Comment by kaanoner3** [comment]
Hi, I am trying to scan all devices which is near to my phone. I am testing it IPhone X. I have two devices one of them is jbl charge 3, the other one my macbook. bleManager found my macbook properly but it didn't find my jbl.  If only jbl is open for connection, manager is not returning anyting either result or error. Did I miss something ?

Here is my epic for scanning:

<img width="516" alt="Screen Shot 2019-04-01 at 01 12 09" src="https://user-images.githubusercontent.com/32056713/55295921-59dcbf00-541b-11e9-92c2-4e01c61f6b43.png">



    "react-native": "0.58.4",

**Comment by Cierpliwy** [comment]
@kaanoner3 Does this jbl device support LE connections or only Bluetooth Classic (not supported by this lib)?

**Comment by kaanoner3** [comment]
@Cierpliwy I think it doesn't. I tested another device it is working fine.

**Comment by Cierpliwy** [comment]
In that case I'll close this issue.
