### ISSUE TITLE
connected devices not found!

### ISSUE THREAD

**Issue by bhenav** [Polidea/react-native-ble-plx#399]
**Name:** General Bluetooth HID Barcode Scanner
￼￼￼
### console log
* * *
<img width="1672" alt="screenshot" src="https://user-images.githubusercontent.com/14276250/51791222-9d634480-21b0-11e9-8a53-2ec2b1e0694d.png">

### iphone bluetooth settings
* * *
![img_ffbf1a913a7d-1](https://user-images.githubusercontent.com/14276250/51791098-08138080-21af-11e9-89a7-f2bbe302b558.jpeg)

### Xcode
* * *
<img width="940" alt="screenshot" src="https://user-images.githubusercontent.com/14276250/51791250-1e224080-21b1-11e9-9ecb-50e15ec08a68.png">

### Permission
* * *
![img_1049](https://user-images.githubusercontent.com/14276250/51791588-7ad42a00-21b6-11e9-913e-5b0645efa954.PNG)

### code
* * *
```javascript
  constructor() {
    this.manager = new BleManager();
  }

  async componentDidMount() {
    if (Platform.OS === 'ios') {
      this.hasBluetoothPermission = await Permissions.check('bluetooth');
      if (this.hasBluetoothPermission === 'undetermined') {
        this.hasBluetoothPermission = await Permissions.request('bluetooth');
      }
    }
    this.manager.onStateChange(async (state) => {
      if (state === State.PoweredOn) {
        this.scanAndConnect();
      } else {
        this.manager.stopDeviceScan();
      }
    }, true);
  }

  scanAndConnect() {
    this.manager.startDeviceScan(null, null, async (error, device) => {
      if (!this.devices.find(item => item.id === device.id)) {
        this.devices.push(device);
        device.onDisconnected((err, d) => {
          console.log('device Disconnected', d);
        });
        this.devices.forEach(async item => {
          console.log(item.id, item.name, item.isConnectable, await item.isConnected());
        });
        let connectedDevices = await this.manager.connectedDevices(null);
        console.log(connectedDevices);
      }
    });
  }
```

**Comment by bhenav** [comment]
?

**Comment by Cierpliwy** [comment]
Are you sure that your device supports Bluetooth Low Energy apart from Bluetooth classic?

**Comment by Cierpliwy** [comment]
@bhenav Any news?
