### ISSUE TITLE
Discovering smartphones/tablets

### ISSUE THREAD

**Issue by patrickhoehn** [Polidea/react-native-ble-plx#4]
Is it possible to discover other smartphones or tablets running the same app (in the background) with this library? Does it support advertising?

**Comment by Cierpliwy** [comment]
No, currently we don't support devices in peripheral role. It's a big task to do which would also require us to bump min sdk version from 18 (4.3) to 21 (5.0) for Android. Also such feature will need to be implemented in our RxAndroidBle and RxBluetoothKit libraries in the first place.
