### ISSUE TITLE
Problem to reconnect after manager.destroy()

### ISSUE THREAD

**Issue by michalkow** [Polidea/react-native-ble-plx#40]
I am using `manager.destroy()` when my app goes into background. I disconnect from the connected devices first.
When I go back to the app and do a new scan, I cannot find the device.
I use `new BleManager()` to create new manager after the app comes back. 
Am I doing it wrong?

**Comment by Cierpliwy** [comment]
Closing as this is an overdue issue. Please feel free to reopen if you tested it with the latest version of a library.
