### ISSUE TITLE
monitorCharacteristicForDevice does not return any values

### ISSUE THREAD

**Issue by renard12** [Polidea/react-native-ble-plx#407]
Hi to all so I need du subscribe to updates for battery lever for my device but monitorCharacteristicForDevice is not working  I am doing something like this:
 `
this.manager.monitorCharacteristicForDevice(

      this.props.device.id,
      services.BATTERY_SERVICE_UUID,
      services.BATTERY_LEVEL_CHARACTERISTIC_UUID,
      (err, char) => {
        if (err) {
          return this.showModal(
            'ERROR!',
            'There is some problem with connection, device is disconnected',
            {
              buttons: [
                { text: 'Ok', action: this.disconnectWithDevice },
              ],
            }
          );
        }
        console.log(char);
      }, 'monitor_battery');
  };

`

**Comment by dariuszseweryn** [comment]
Any info on what you are testing with? Or what is available in the logs?

**Comment by renard12** [comment]
Sorry, my bad, I`am doing monitor before discoverAllServicesAndCharacteristics
