### ISSUE TITLE
dyld: Library not loaded: @rpath/BleClientManager.framework/BleClientManager

### ISSUE THREAD

**Issue by sumesh1993** [Polidea/react-native-ble-plx#42]
Getting the above error. I installed as instructed but it doesn't seem to be working.
Any ideas what i might be doing wrong ?

"react": "15.4.1",
"react-native": "0.39.2",
"react-native-ble-plx": 0.3.3

**Comment by sumesh1993** [comment]
@Cierpliwy

**Comment by sumesh1993** [comment]
And on android i am getting this error ---- Unknown named module: 'fbjs/lib/invariant'

i tried installing fbjs but still the same error.

Please help

**Comment by Muriel0603** [comment]
build path ---> link binary  -- > 添加bye目录下的三个framework

**Comment by haohcraft** [comment]
@Muriel0603 你所指的是那个`run script`? 我还是会出现同样的问题。 求助，感谢。

![screen shot 2017-03-20 at 9 06 58 am](https://cloud.githubusercontent.com/assets/3459080/24100943/b38eadf0-0d4c-11e7-8cda-8c87c8d11278.png)

**Comment by Muriel0603** [comment]
上面两个选中 ，然后在general --> embedded binaries 添加这三个framework

**Comment by Cierpliwy** [comment]
Any news on that?

**Comment by CrazyWr** [comment]
![image](https://user-images.githubusercontent.com/19635808/28706730-0b5caa8e-73a8-11e7-97d8-7e483f2b6c39.png)
simulator ran successfully but my iPad crashed like this

**Comment by durgesh0001** [comment]
Thanks it was great help for me
