### ISSUE TITLE
pod update fail

### ISSUE THREAD

**Issue by p4bl1t0** [Polidea/react-native-ble-plx#423]
When running `pod update` I'm seeing the following error:

> [!] Unable to determine Swift version for the following pods:
> 
> - `react-native-ble-plx-swift` does not specify a Swift version and none of the targets (`evd`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

My `pod --version ` output is: 

> 1.6.1

Suggestions?

**Comment by p4bl1t0** [comment]
After setting SWIFT_VERSION I'm getting

> [!] An error occurred while processing the post-install hook of the Podfile.
> 
> undefined method `native_target' for <Pod::PodTarget name=Amplitude-iOS >:Pod::PodTarget

In order projects said that this is a problem with the cocoapod version

**Comment by p4bl1t0** [comment]
Finally that solved the problem with `pod update` but now when I try to build the solution from Xcode I'm getting the following linking error:

> Undefined symbols for architecture arm64:
>   "protocol descriptor for Swift.Collection", referenced from:
>       l_got.$SSlMp in libreact-native-ble-plx-swift.a(Zip+Collection.o)
>   "protocol witness table for Swift.Int64 : Swift.BinaryInteger in Swift", referenced from:
>       react_native_ble_plx_swift.(ZipCollectionType in _BCE3332D9AE148ED20637FC8E9C507A8).init(sources: A, resultSelector: ([A.Element.E]) throws -> B) -> react_native_ble_plx_swift.(ZipCollectionType in _BCE3332D9AE148ED20637FC8E9C507A8)<A, B> in libreact-native-ble-plx-swift.a(Zip+Collection.o)
>   "Swift.Array.subscript.nativePinningMutableAddressor : (Swift.Int) -> A", referenced from:
>       react_native_ble_plx_swift.(ZipCollectionTypeSink in _BCE3332D9AE148ED20637FC8E9C507A8).on(_: react_native_ble_plx_swift.Event<A.Element.E>, atIndex: Swift.Int) -> () in libreact-native-ble-plx-swift.a(Zip+Collection.o)
>   "Swift.Array.init(repeating: A, count: Swift.Int) -> [A]", referenced from:
>       react_native_ble_plx_swift.(ZipCollectionTypeSink in _BCE3332D9AE148ED20637FC8E9C507A8).init(parent: react_native_ble_plx_swift.(ZipCollectionType in _BCE3332D9AE148ED20637FC8E9C507A8)<A, B.E>, observer: B, cancel: react_native_ble_plx_swift.Cancelable) -> react_native_ble_plx_swift.(ZipCollectionTypeSink in _BCE3332D9AE148ED20637FC8E9C507A8)<A, B> in libreact-native-ble-plx-swift.a(Zip+Collection.o)
>   "Swift.Array.init() -> [A]", referenced from:
>       react_native_ble_plx_swift.(ZipCollectionTypeSink in _BCE3332D9AE148ED20637FC8E9C507A8).init(parent: react_native_ble_plx_swift.(ZipCollectionType in _BCE3332D9AE148ED20637FC8E9C507A8)<A, B.E>, observer: B, cancel: react_native_ble_plx_swift.Cancelable) -> react_native_ble_plx_swift.(ZipCollectionTypeSink in _BCE3332D9AE148ED20637FC8E9C507A8)<A, B> in libreact-native-ble-plx-swift.a(Zip+Collection.o)
>       react_native_ble_plx_swift.(ZipCollectionTypeSink in _BCE3332D9AE148ED20637FC8E9C507A8).on(_: react_native_ble_plx_swift.Event<A.Element.E>, atIndex: Swift.Int) -> () in libreact-native-ble-plx-swift.a(Zip+Collection.o)
>   "Swift.Array.reserveCapacity(Swift.Int) -> ()", referenced from:
>       react_native_ble_plx_swift.(ZipCollectionTypeSink in _BCE3332D9AE148ED20637FC8E9C507A8).init(parent: react_native_ble_plx_swift.(ZipCollectionType in _BCE3332D9AE148ED20637FC8E9C507A8)<A, B.E>, observer: B, cancel: react_native_ble_plx_swift.Cancelable) -> react_native_ble_plx_swift.(ZipCollectionTypeSink in _BCE3332D9AE148ED20637FC8E9C507A8)<A, B> in libreact-native-ble-plx-swift.a(Zip+Collection.o)
>       react_native_ble_plx_swift.(ZipCollectionTypeSink in _BCE3332D9AE148ED20637FC8E9C507A8).on(_: react_native_ble_plx_swift.Event<A.Element.E>, atIndex: Swift.Int) -> () in libreact-native-ble-plx-swift.a(Zip+Collection.o)
>   "Swift.String.index(before: Swift.String.Index) -> Swift.String.Index", referenced from:
>       (extension in react_native_ble_plx_swift):Swift.String.lastIndexOf(Swift.Character) -> Swift.String.Index? in libreact-native-ble-plx-swift.a(String+Rx.o)
>   "static Swift.Character.== infix(Swift.Character, Swift.Character) -> Swift.Bool", referenced from:
>       (extension in react_native_ble_plx_swift):Swift.String.lastIndexOf(Swift.Character) -> Swift.String.Index? in libreact-native-ble-plx-swift.a(String+Rx.o)
>   "_swift_getFunctionTypeMetadata2", referenced from:
>       closure #1 (A) -> react_native_ble_plx_swift.Disposable in react_native_ble_plx_swift.AnyRecursiveScheduler.schedule(_: A, dueTime: Swift.Double) -> () in libreact-native-ble-plx-swift.a(RecursiveScheduler.o)
>       closure #1 (A) -> react_native_ble_plx_swift.Disposable in react_native_ble_plx_swift.AnyRecursiveScheduler.schedule(A) -> () in libreact-native-ble-plx-swift.a(RecursiveScheduler.o)
>       closure #1 (A) -> react_native_ble_plx_swift.Disposable in react_native_ble_plx_swift.RecursiveImmediateScheduler.schedule(A) -> () in libreact-native-ble-plx-swift.a(RecursiveScheduler.o)
>   "protocol descriptor for Swift.FixedWidthInteger", referenced from:
>       l_got.$Ss17FixedWidthIntegerMp in libreact-native-ble-plx-swift.a(Timer.o)
>   "dispatch thunk of Swift.FixedWidthInteger.addingReportingOverflow(A) -> (partialValue: A, overflow: Swift.Bool)", referenced from:
>       closure #1 (A.E) -> A.E in react_native_ble_plx_swift.(TimerSink in _7E8A1FFA6C07F53EE32882E6F9B60697).run() -> react_native_ble_plx_swift.Disposable in libreact-native-ble-plx-swift.a(Timer.o)
>   "dispatch thunk of Swift._ExpressibleByBuiltinIntegerLiteral.init(_builtinIntegerLiteral: Builtin.Int2048) -> A", referenced from:
>       react_native_ble_plx_swift.(TimerSink in _7E8A1FFA6C07F53EE32882E6F9B60697).run() -> react_native_ble_plx_swift.Disposable in libreact-native-ble-plx-swift.a(Timer.o)
>       closure #1 (A.E) -> A.E in react_native_ble_plx_swift.(TimerSink in _7E8A1FFA6C07F53EE32882E6F9B60697).run() -> react_native_ble_plx_swift.Disposable in libreact-native-ble-plx-swift.a(Timer.o)
>       closure #1 (react_native_ble_plx_swift.(TimerOneOffSink in _7E8A1FFA6C07F53EE32882E6F9B60697)<A>) -> react_native_ble_plx_swift.Disposable in react_native_ble_plx_swift.(TimerOneOffSink in _7E8A1FFA6C07F53EE32882E6F9B60697).run() -> react_native_ble_plx_swift.Disposable in libreact-native-ble-plx-swift.a(Timer.o)
>   "Foundation.Date.timeIntervalSince(Foundation.Date) -> Swift.Double", referenced from:
>       react_native_ble_plx_swift.(DelaySink in _02866F39A428D8F033986E6359DFF108).drainQueue(state: (), scheduler: react_native_ble_plx_swift.AnyRecursiveScheduler<()>) -> () in libreact-native-ble-plx-swift.a(Delay.o)
>   "Swift.Character.init(_builtinExtendedGraphemeClusterLiteral: Builtin.RawPointer, utf16CodeUnitCount: Builtin.Word) -> Swift.Character", referenced from:
>       react_native_ble_plx_swift.(Debug in _FCAAD99F6E275EA165B2F484906844B9).init(source: A, identifier: Swift.String?, trimOutput: Swift.Bool, file: Swift.String, line: Swift.UInt, function: Swift.String) -> react_native_ble_plx_swift.(Debug in _FCAAD99F6E275EA165B2F484906844B9)<A> in libreact-native-ble-plx-swift.a(Debug.o)
>   "Swift.String.index(after: Swift.String.Index) -> Swift.String.Index", referenced from:
>       react_native_ble_plx_swift.(Debug in _FCAAD99F6E275EA165B2F484906844B9).init(source: A, identifier: Swift.String?, trimOutput: Swift.Bool, file: Swift.String, line: Swift.UInt, function: Swift.String) -> react_native_ble_plx_swift.(Debug in _FCAAD99F6E275EA165B2F484906844B9)<A> in libreact-native-ble-plx-swift.a(Debug.o)
>   "Swift.String.endIndex.getter : Swift.String.Index", referenced from:
>       react_native_ble_plx_swift.(Debug in _FCAAD99F6E275EA165B2F484906844B9).init(source: A, identifier: Swift.String?, trimOutput: Swift.Bool, file: Swift.String, line: Swift.UInt, function: Swift.String) -> react_native_ble_plx_swift.(Debug in _FCAAD99F6E275EA165B2F484906844B9)<A> in libreact-native-ble-plx-swift.a(Debug.o)
>       (extension in react_native_ble_plx_swift):Swift.String.lastIndexOf(Swift.Character) -> Swift.String.Index? in libreact-native-ble-plx-swift.a(String+Rx.o)
>   "type metadata for Swift.String.Index", referenced from:
>       react_native_ble_plx_swift.(Debug in _FCAAD99F6E275EA165B2F484906844B9).init(source: A, identifier: Swift.String?, trimOutput: Swift.Bool, file: Swift.String, line: Swift.UInt, function: Swift.String) -> react_native_ble_plx_swift.(Debug in _FCAAD99F6E275EA165B2F484906844B9)<A> in libreact-native-ble-plx-swift.a(Debug.o)
>       (extension in react_native_ble_plx_swift):Swift.String.lastIndexOf(Swift.Character) -> Swift.String.Index? in libreact-native-ble-plx-swift.a(String+Rx.o)
>   "Swift.Range.init(uncheckedBounds: (lower: A, upper: A)) -> Swift.Range<A>", referenced from:
>       react_native_ble_plx_swift.(Debug in _FCAAD99F6E275EA165B2F484906844B9).init(source: A, identifier: Swift.String?, trimOutput: Swift.Bool, file: Swift.String, line: Swift.UInt, function: Swift.String) -> react_native_ble_plx_swift.(Debug in _FCAAD99F6E275EA165B2F484906844B9)<A> in libreact-native-ble-plx-swift.a(Debug.o)
>   "Swift.String.subscript.getter : (Swift.Range<Swift.String.Index>) -> Swift.Substring", referenced from:
>       react_native_ble_plx_swift.(Debug in _FCAAD99F6E275EA165B2F484906844B9).init(source: A, identifier: Swift.String?, trimOutput: Swift.Bool, file: Swift.String, line: Swift.UInt, function: Swift.String) -> react_native_ble_plx_swift.(Debug in _FCAAD99F6E275EA165B2F484906844B9)<A> in libreact-native-ble-plx-swift.a(Debug.o)
>   "(extension in Swift):Swift.Collection.prefix(Swift.Int) -> A.SubSequence", referenced from:
>       react_native_ble_plx_swift.(DebugSink in _FCAAD99F6E275EA165B2F484906844B9).on(react_native_ble_plx_swift.Event<A.E>) -> () in libreact-native-ble-plx-swift.a(Debug.o)
>   "protocol witness table for Swift.String : Swift.BidirectionalCollection in Swift", referenced from:
>       react_native_ble_plx_swift.(DebugSink in _FCAAD99F6E275EA165B2F484906844B9).on(react_native_ble_plx_swift.Event<A.E>) -> () in libreact-native-ble-plx-swift.a(Debug.o)
>   "(extension in Swift):Swift.BidirectionalCollection.suffix(Swift.Int) -> A.SubSequence", referenced from:
>       react_native_ble_plx_swift.(DebugSink in _FCAAD99F6E275EA165B2F484906844B9).on(react_native_ble_plx_swift.Event<A.E>) -> () in libreact-native-ble-plx-swift.a(Debug.o)
>   "Swift.String.init(Swift.Substring) -> Swift.String", referenced from:
>       react_native_ble_plx_swift.(DebugSink in _FCAAD99F6E275EA165B2F484906844B9).on(react_native_ble_plx_swift.Event<A.E>) -> () in libreact-native-ble-plx-swift.a(Debug.o)
>       react_native_ble_plx_swift.(Debug in _FCAAD99F6E275EA165B2F484906844B9).init(source: A, identifier: Swift.String?, trimOutput: Swift.Bool, file: Swift.String, line: Swift.UInt, function: Swift.String) -> react_native_ble_plx_swift.(Debug in _FCAAD99F6E275EA165B2F484906844B9)<A> in libreact-native-ble-plx-swift.a(Debug.o)
>   "Foundation.Date._bridgeToObjectiveC() -> __C.NSDate", referenced from:
>       react_native_ble_plx_swift.(logEvent in _FCAAD99F6E275EA165B2F484906844B9)(_: Swift.String, dateFormat: __C.NSDateFormatter, content: Swift.String) -> () in libreact-native-ble-plx-swift.a(Debug.o)
>   "type metadata accessor for Dispatch.DispatchSpecificKey", referenced from:
>       type metadata accessor for Dispatch.DispatchSpecificKey<()> in libreact-native-ble-plx-swift.a(DispatchQueue+Extensions.o)
>   "(extension in Dispatch):__C.OS_dispatch_queue.setSpecific<A>(key: Dispatch.DispatchSpecificKey<A>, value: A?) -> ()", referenced from:
>       closure #1 () -> Dispatch.DispatchSpecificKey<()> in variable initialization expression of static (extension in react_native_ble_plx_swift):__C.OS_dispatch_queue.(token in _EEC4892CFB5540A867C3567336965479) : Dispatch.DispatchSpecificKey<()> in libreact-native-ble-plx-swift.a(DispatchQueue+Extensions.o)
>   "_swift_unpin", referenced from:
>       react_native_ble_plx_swift.Queue.enqueue(A) -> () in libreact-native-ble-plx-swift.a(Queue.o)
>       $defer #1 <A>() -> () in react_native_ble_plx_swift.Queue.(dequeueElementOnly in _7D931633B0035D956A5C3B08A161710B)() -> A in libreact-native-ble-plx-swift.a(Queue.o)
>       react_native_ble_plx_swift.(ZipCollectionTypeSink in _BCE3332D9AE148ED20637FC8E9C507A8).on(_: react_native_ble_plx_swift.Event<A.Element.E>, atIndex: Swift.Int) -> () in libreact-native-ble-plx-swift.a(Zip+Collection.o)
>   "protocol witness table for Swift.Int : Swift.Comparable in Swift", referenced from:
>       react_native_ble_plx_swift.Queue.(resizeTo in _7D931633B0035D956A5C3B08A161710B)(Swift.Int) -> () in libreact-native-ble-plx-swift.a(Queue.o)
>       react_native_ble_plx_swift.Queue.enqueue(A) -> () in libreact-native-ble-plx-swift.a(Queue.o)
>   "Swift.min<A where A: Swift.Comparable>(A, A) -> A", referenced from:
>       react_native_ble_plx_swift.Queue.(resizeTo in _7D931633B0035D956A5C3B08A161710B)(Swift.Int) -> () in libreact-native-ble-plx-swift.a(Queue.o)
>   "_swift_initEnumMetadataMultiPayload", referenced from:
>       type metadata completion function for react_native_ble_plx_swift.Event in libreact-native-ble-plx-swift.a(Event.o)
>       type metadata completion function for react_native_ble_plx_swift.MaybeEvent in libreact-native-ble-plx-swift.a(Maybe.o)
>       type metadata completion function for react_native_ble_plx_swift.SingleEvent in libreact-native-ble-plx-swift.a(Single.o)
>   "Swift.Dictionary.values.getter : [A : B].Values", referenced from:
>       react_native_ble_plx_swift.Bag.forEach((A) -> ()) -> () in libreact-native-ble-plx-swift.a(Bag.o)
>       react_native_ble_plx_swift.dispatch<A>(react_native_ble_plx_swift.Bag<(react_native_ble_plx_swift.Event<A>) -> ()>, react_native_ble_plx_swift.Event<A>) -> () in libreact-native-ble-plx-swift.a(Bag+Rx.o)
>       react_native_ble_plx_swift.disposeAll(in: react_native_ble_plx_swift.Bag<react_native_ble_plx_swift.Disposable>) -> () in libreact-native-ble-plx-swift.a(Bag+Rx.o)
>   "protocol witness table accessor for [A : B].Values : Swift.Collection in Swift", referenced from:
>       react_native_ble_plx_swift.Bag.forEach((A) -> ()) -> () in libreact-native-ble-plx-swift.a(Bag.o)
>       react_native_ble_plx_swift.dispatch<A>(react_native_ble_plx_swift.Bag<(react_native_ble_plx_swift.Event<A>) -> ()>, react_native_ble_plx_swift.Event<A>) -> () in libreact-native-ble-plx-swift.a(Bag+Rx.o)
>       lazy protocol witness table accessor for type [react_native_ble_plx_swift.BagKey : react_native_ble_plx_swift.Disposable].Values and conformance [A : B].Values : Swift.Collection in Swift in libreact-native-ble-plx-swift.a(Bag+Rx.o)
>   "Swift.Dictionary.removeValue(forKey: A) -> B?", referenced from:
>       react_native_ble_plx_swift.Bag.removeKey(react_native_ble_plx_swift.BagKey) -> A? in libreact-native-ble-plx-swift.a(Bag.o)
>   "Swift.ContiguousArray.subscript.getter : (Swift.Int) -> A", referenced from:
>       react_native_ble_plx_swift.Bag.removeKey(react_native_ble_plx_swift.BagKey) -> A? in libreact-native-ble-plx-swift.a(Bag.o)
>       react_native_ble_plx_swift.Bag.forEach((A) -> ()) -> () in libreact-native-ble-plx-swift.a(Bag.o)
>       react_native_ble_plx_swift.Queue.peek() -> A in libreact-native-ble-plx-swift.a(Queue.o)
>       react_native_ble_plx_swift.Queue.(dequeueElementOnly in _7D931633B0035D956A5C3B08A161710B)() -> A in libreact-native-ble-plx-swift.a(Queue.o)
>       closure #1 () -> A? in react_native_ble_plx_swift.Queue.makeIterator() -> Swift.AnyIterator<A> in libreact-native-ble-plx-swift.a(Queue.o)
>       react_native_ble_plx_swift.dispatch<A>(react_native_ble_plx_swift.Bag<(react_native_ble_plx_swift.Event<A>) -> ()>, react_native_ble_plx_swift.Event<A>) -> () in libreact-native-ble-plx-swift.a(Bag+Rx.o)
>       react_native_ble_plx_swift.disposeAll(in: react_native_ble_plx_swift.Bag<react_native_ble_plx_swift.Disposable>) -> () in libreact-native-ble-plx-swift.a(Bag+Rx.o)
>

**Comment by p4bl1t0** [comment]
Finally I start a new Expo fresh project and I was able to correct link the library following the installation steps.

**Comment by anovacap** [comment]
> After setting SWIFT_VERSION I'm getting
> 
> > [!] An error occurred while processing the post-install hook of the Podfile.
> > undefined method `native_target' for <Pod::PodTarget name=Amplitude-iOS >:Pod::PodTarget
> 
> In order projects said that this is a problem with the cocoapod version

Where did you set SWIFT_VERSION? What file is it in?

**Comment by p4bl1t0** [comment]
@anovacap don't follow that path.

Finally the only way thay I found to install this module is to start a fresh project.

I set the SWIFT_VERSION  in the build settings of the xcode project

**Comment by christianortega123** [comment]
Hi, I still can't find where you set the SWIFT_VERSION in the build settings of the xcode project. Where exactly is it? Thanks! @p4bl1t0

**Comment by p4bl1t0** [comment]
I really don't re-call. Do not mess with the SWIFT_VERSION. Try starting a fresh project.
