### ISSUE TITLE
Filter by name

### ISSUE THREAD

**Issue by StephaneJuban** [Polidea/react-native-ble-plx#427]
Is it possible now or in the future to scan device but instead of filtering by UUID, doing it by name or with a prefix ?

I know we can do that [with Web BLE](https://developer.mozilla.org/en-US/docs/Web/API/Bluetooth/requestDevice).

**Comment by Cierpliwy** [comment]
It is possible to do so as long as advertisement data send from your devices includes "Complete Local Name" or "Shortened Local Name". You can see that value in `localName` property of your scanned device object. There is no way to filter that in one API call, so you have to code that part manually in scanning callback.

**Comment by StephaneJuban** [comment]
Ok thanks for the clarification.
