### ISSUE TITLE
BleClientManager not in NativeModules with run-ios on device but with XCode is present

### ISSUE THREAD

**Issue by mrigo** [Polidea/react-native-ble-plx#429]
Hello,
I'm trying to use ble-plx, but I've got "Native modules null" error when starting on device with
```
react-native run-ios --device="device name"
```
but running from XCode, all works...

I've linked manually the library on iOS with "add file" for the project file and added .a library in Build Phases.

Is there a reason for this?
Thanks

P.s.
not yet tested on Android..

**Comment by Cierpliwy** [comment]
You should not need to add any static library manually. Linking command `react-native link react-native-ble-plx` should take care of this. Are you sure that installation step finished successfully?
