### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by weinixuehao** [Polidea/react-native-ble-plx#430]
Fuck! The lib has no example! use this lib not working to me! 
to monitor the device for notification but never receive any notifications

**Comment by piotrdubiel** [comment]
Please check [this project](https://github.com/Cierpliwy/SensorTag) for example usage.

**Comment by jimji1005** [comment]
Not sure if an ass or just bad eyesight

**Comment by weinixuehao** [comment]
@piotrdubiel 
Sorry for my bad attitude.
I found that i installed two library which are react-native-ble-manager and react-native-ble-plx
when i intead of the library with the react-native-ble-manager library.
but i have not yet proved whether they have conflict  because i am buzy and used react-native-ble-manager debug success! 

Sorry for my poor english!

**Comment by Cierpliwy** [comment]
You should not mix multiple BLE libraries as it may be problematic. How can I help you otherwise?

**Comment by mariomeraz** [comment]
> Please check [this project](https://github.com/Cierpliwy/SensorTag) for example usage.

Hi again, finally install in my Device Android, open the App, check the permission and Log seee start Scan.

After a few minutes it does not detect anything, something I'm doing wrong?


 Mi BT BLE temperature sensor and gps
![IMG_20190408_220345](https://user-images.githubusercontent.com/14825814/55770923-aba0cd00-5a4b-11e9-9c6b-58ebfcb5363c.jpg)


![SVID_20190408_221133_1](https://user-images.githubusercontent.com/14825814/55771006-fae6fd80-5a4b-11e9-98b4-94af840e6545.gif)

**Comment by Cierpliwy** [comment]
@mariomeraz Did you modify the source code of the example app to filter proper devices during a scanning procedure?

**Comment by Cierpliwy** [comment]
Look at: https://github.com/Cierpliwy/SensorTag/blob/master/src/Saga.js#L150
