### ISSUE TITLE
Application hangs during startDeviceScan due to which the user is unable to navigate back or press any button.

### ISSUE THREAD

**Issue by kkiran16** [Polidea/react-native-ble-plx#435]
I tried the basic example as below,

`import React, { Component } from "react";
import {
  AppRegistry,
  StyleSheet,
  Text,
  SafeAreaView,
  FlatList,
  Platform,
  Button
} from "react-native";
import { BleManager, Device, BleError, LogLevel } from "react-native-ble-plx";

type Props = {};

type State = {
  text: Array<string>
};

function arrayBufferToHex(buffer) {
  if (!buffer) return null;
  const values = new Uint8Array(buffer);
  var string = "";
  for (var i = 0; i < values.length; i += 1) {
    const num = values[i].toString(16);
    string += num.length == 1 ? "0" + num : num;
  }
  return string;
}

export default class App extends Component<Props, State> {
  manager = new BleManager();

  constructor(props: Props) {
    super(props);
    this.state = {
      text: []
    };
  }

  componentDidMount() {
    this.manager = new BleManager();
    const manager = this.manager;

    manager.onStateChange(newState => {
      if (newState != "PoweredOn") {
       manager.enable();
          
        return;
      }
      this._log("Started scanning...");
      this._startDeviceScan();
    }, true);

    setInterval(this._stopDeviceScan, 3000);

    setInterval(this._startDeviceScan, 9000);

    /*setInterval((this.manager) => {
      console.warn('In Start');
      this._startDeviceScan(this.manager);
    }, 600); */
  }

  _stopDeviceScan = () => {
    console.warn('In stop:');
    this.manager.stopDeviceScan();
  }

  _startDeviceScan = () => {
    const manager = this.manager;
    manager.startDeviceScan(
      null, {
        allowDuplicates: false
      },
      (error, device) => {
        if (error) {
          this._logError("SCAN", error);
          return;
        }

        this._log("Device : " + device.name, device.id);
        //device.id === 'C5:12:11:BF:25:EA'
        if (device.id === 'C5:12:11:AD:2B:28') {
          this._log('It is our BLE');
          manager.stopDeviceScan();

          device.connect()
            .then((device) => {
              this._log("Connected to BLE", device);
              return device.discoverAllServicesAndCharacteristics('123');
              //return device.services();
            })
            .then((device) => {
              this._log("Connected services : " + device);
              return device.services();
              //console.warn(JSON.stringify(services));
            })
            .then((services) => {
              console.warn('Services Length : ' + services.length);
              console.warn('Services UUID : ' + services[0].uuid + ' , ' + services[1].uuid + ' , ' + services[2].uuid);

              return services[2].characteristics();

            }).then((characteristics) => {

              console.warn('Characteristics Length : ' + characteristics.length);
              console.warn('Characteristics UUID : ' + characteristics[0].uuid + ' , ' + characteristics[1].uuid);

              console.warn('Characteristic UUID : ' + characteristics[0].uuid);
              console.warn('Characteristic Value : ' + characteristics[0].value);
            })
            .catch((error) => {
              // Handle errors
              this._log("Error in Connection", error);
            });

        }

      }
    );
  }

  _log = (text: string, ...args) => {
    const message = "[" + Date.now() % 10000 + "] " + text + ":" + args[0];
    this.setState({
      text: [message, ...this.state.text]
    });
  };

  _logError = (tag: string, error: BleError) => {
    this._log(
      tag +
        "ERROR(" +
        error.errorCode +
        "): " +
        error.message +
        "\nREASON: " +
        error.reason +
        " (att: " +
        error.attErrorCode +
        ", ios: " +
        error.iosErrorCode +
        ", and: " +
        error.androidErrorCode +
        ")"
    );
  };

  delay = () => {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve();
      }, 5000);
    });
  };

  render() {
    return (
      <SafeAreaView
        style={styles.container}
      >
        <Button
          onPress={() => {
            console.warn('In Clear');
            this.setState({
              text: []
            });
          }}
          title={"Clear"}
        />
        <FlatList
          style={styles.container}
          data={this.state.text}
          renderItem={({ item }) => <Text> {item} </Text>}
          keyExtractor={(item, index) => index.toString()}
        />
      </SafeAreaView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1
  }
});
`

It is able to scan devices and also connect to a specific device. But during the process of scanning application hangs and user is not able to perform any other action. 
How can I overcome this issue? Is there any other approach of using the library like threading or running background, if yes please share any example.

**Comment by Cierpliwy** [comment]
Every operation provided by a library is asynchronous. Nothing should be blocked. Could you create a repo with your example, so that I could test it more easily?

**Comment by tomdaniel0x01** [comment]
My React Native UI would also hang while performing a `startDeviceScan`. The cause was having the Debugger enabled. Once I disabled the debugger the UI responded lighting fast while `startDeviceScan` was executing.

**Comment by webjay** [comment]
Mine was blocked in dev when I had `{ allowDuplicates: true }`.
