### ISSUE TITLE
Getting null in startDeviceScan

### ISSUE THREAD

**Issue by Gu7z** [Polidea/react-native-ble-plx#438]
Hey,
I have a code with basically this

`search = () => {`
  `manager.startDeviceScan(null, null, (error, device) => {`
    `console.log(device)`
    `manager.stopDeviceScan()`
  `}`
`}`

`<Button onClick={this.search}></Button>`

When i click 5 times in a row, i got null for some seconds then going back to scan. Any ideas to solve?

**Comment by dariuszseweryn** [comment]
Have you checked `error`?

**Comment by Gu7z** [comment]
i excluded the code and restarted, now it's working but i want to get more than 1 device at a time
Do you know how can i do it?

**Comment by dariuszseweryn** [comment]
Do you know what you do in the `startDeviceScan` callback?

**Comment by CaptainJeff** [comment]
Yeah, you are stopping the device scan when you return one device

manager.stopDeviceScan()

**Comment by Cierpliwy** [comment]
[Type signature](https://polidea.github.io/react-native-ble-plx/#blemanagerstartdevicescan) clearly suggests that Device can be a `null`, when error occurred during scanning. I'm closing this issue, as this is an expected behaviour.

**Comment by santiagomartinez** [comment]
Sorry to open this, but please consider the following limitation on Android 7+:
https://blog.classycode.com/undocumented-android-7-ble-behavior-changes-d1a9bd87d983

You cannot scan more than 5 times in a 30 seconds window or else the scan will fail silently.
