### ISSUE TITLE
is it possible to put the device running the application in advertise mode?

### ISSUE THREAD

**Issue by vijay122** [Polidea/react-native-ble-plx#44]
i am creating a android application in react native. in this application i have to put the device in advertise mode, so other nearby devices (over bluetooth) can identify it and subscribe to it. i am seeing examples where we can listen to advertised devices and get its characteristics using plx, is it possible to advertise from my app?

**Comment by Cierpliwy** [comment]
Unfortunately not. We still need to do a lot of work related to that on our backend libraries (RxBluetoothKit and RxAndroidBLE).

**Comment by vijay122** [comment]
@Cierpliwy thankyou for the reply. can you suggest me any package which i can use for advertising in react-native. or is it a good to use android's ble advertising module in the react-native project with a wrapper.?

**Comment by Cierpliwy** [comment]
Unfortunately I'm not familiar with any library that supports Peripheral Mode.

**Comment by anton-aleksandrov** [comment]
why peripheral mode is a problem?

**Comment by Cierpliwy** [comment]
Peripheral mode will require support for it in our RxBluetoothKit and RxAndroidBle libraries to land in react-native-ble-plx. Also Peripheral mode is working fine on Android from version 5.0 and on selected devices from what I know.

**Comment by Cierpliwy** [comment]
Closing as we are blocked by missing implementation of RxBluetoothKit and RxAndroidBle libraries.

**Comment by robertherber** [comment]
This seems to be available in RxBluetoothKit now, right?

**Comment by thePsguy** [comment]
@Cierpliwy, Should this issue be opened again now that it looks like peripheral / advertisement support is now present in the previously blocking libraries.

**Comment by artiya4u** [comment]
Hi, maybe this is the time to support the peripheral / advertisement feature. I really need this feature to create an application to track people's proximity to help reduce the COVID-19 spread.
