### ISSUE TITLE
Question Android Example 

### ISSUE THREAD

**Issue by mariomeraz** [Polidea/react-native-ble-plx#448]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active) or on our [Gitter](https://gitter.im/RxBLELibraries/react-native-ble) channel.

## Question

Please describe the question.

Hi!, download the examples and follow step by step, install the app in my emulator, but no active the BT, any idea? Emulator work with Bluetooth?
<img width="475" alt="Screen Shot 2019-04-08 at 15 27 14" src="https://user-images.githubusercontent.com/14825814/55755054-b63f7000-5a13-11e9-8a69-f6eb102b1133.png">

**Comment by dariuszseweryn** [comment]
Hello,

Follow this [link](http://lmgtfy.com/?q=android+emulator+bluetooth) — the answer should appear at the top ;)

Best Regards
