### ISSUE TITLE
Question: Is it possible to access the raw advertismentData on iOS devices?  

### ISSUE THREAD

**Issue by jacobkring** [Polidea/react-native-ble-plx#449]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active) or on our [Gitter](https://gitter.im/RxBLELibraries/react-native-ble) channel.

## Question

Please describe the question.

I've tried to find an answer in the docs and I'm not seeing anything immediately popping out. Our BLE devices have data encrypted in the raw advertisement packet that does not follow the typical convention of BLE advertisement packet. Is this something that is possible with the library currently? 

Based on my quick googling it appears possible to grab the raw 'advertismentData' from the iOS side of things. Android would be nice to have but we would really like to have it for our iOS devices to get around the BLE mac address -> UUID generation that iOS does.

Thanks!

**Comment by Cierpliwy** [comment]
Actually you can't get raw advertisement data on the iOS platform. You are limited only to selected advertisement data types, which you can find [here](https://developer.apple.com/documentation/corebluetooth/cbcentralmanagerdelegate/advertisement_data_retrieval_keys) (all of them are currently supported). Your BLE device should place all vendor specific data inside "manufacturer data".

**Comment by jacobkring** [comment]
I see, thanks!
