### ISSUE TITLE
Question: Connection to Bluetooth

### ISSUE THREAD

**Issue by keyz23** [Polidea/react-native-ble-plx#451]
Hello, I have a request. I would like to know if, once connected to a device, I can safely navigate through the application (Android App) and always be connected to that device in order to use the information obtained from the device and display, for example, on other pages of the app. Thanks a lot.

**Comment by Cierpliwy** [comment]
UI and this library code are independent. You can design communication as you want and architect it in a way, which will meet your design goals. Hope that helps.
