### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ganisivakumar** [Polidea/react-native-ble-plx#459]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [yes ] I am running the latest version
- [yes ] I checked the documentation and found no answer
- [yes ] I checked to make sure that this issue has not already been filed
- [yes ] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active) or on our [Gitter](https://gitter.im/RxBLELibraries/react-native-ble) channel.

## Question

Please describe the question.
My app minSdkVersion is 16, how to use the library and disable the feature with platform version check

**Comment by dariuszseweryn** [comment]
To disable the `minSdk` requirement you can [check google](http://lmgtfy.com/?q=android+how+to+disable+minsdk+check)

To disable the feature with platform version check just do not call the library if [the platform version is prior to 18](https://facebook.github.io/react-native/docs/platform-specific-code.html#detecting-the-android-version)

Best Regards
