### ISSUE TITLE
error: The following binaries use incompatible versions of Swift: only in release mode

### ISSUE THREAD

**Issue by harshjoshi096** [Polidea/react-native-ble-plx#460]
Hello,
My build is not working in release mode while it is working in debug mode.
Can anyone help me regarding this issue.
The issue which I am getting is - 

error: The following binaries use incompatible versions of Swift:

Thanks

**Comment by dariuszseweryn** [comment]
Maybe you have different build settings for release and debug?

**Comment by harshjoshi096** [comment]
@dariuszseweryn No I am using same default settings, just updated the ble-plx to 9.0.1 version on xcode version 10.1 and OS version 10.14.

**Comment by Ashi90** [comment]
I'm also getting same issue. @harshjoshi096 Have you got Any solution?
