### ISSUE TITLE
iOS not recognizing service, Android does

### ISSUE THREAD

**Issue by AdamGold** [Polidea/react-native-ble-plx#462]
## Question

I was wondering if anyone else stumbled upon the problem that everything works fine in Android - I managed to connect to the peripheral and send data to it, while in iOS the connection is fine but the same service and characteristics UIDs aren't being recognized at all? I'm not sure it has anything to do with the package itself, maybe it's even firmware related.

**Comment by Cierpliwy** [comment]
It's strange. In most cases I have seen this issue other way around. Make sure you call `discoverServicesAndCharacteristics` and try to send me iOS logs from XCode.

**Comment by AdamGold** [comment]
For future reference - The characistics and service UUIDs were different on iOS. Had to check with LightBlue.
