### ISSUE TITLE
Can I use This library in React Native Windows app 

### ISSUE THREAD

**Issue by dharmendrasingh88** [Polidea/react-native-ble-plx#466]
## Question

I want to connect BLE Devices in react native windows app please let me know can i use this or is there any plan for windows app

**Comment by Cierpliwy** [comment]
Currently, this library doesn't support Windows and there are no plans for it right now.

**Comment by noshaid-ali** [comment]
Any update on it? Is there any support available for Windows desktop or still not?

**Comment by noshaid-ali** [comment]
@dharmendrasingh88 How did you connect BLE devices in react native windows desktop app?
