### ISSUE TITLE
Bluetooth pairing with a password / pin

### ISSUE THREAD

**Issue by jinqiangg** [Polidea/react-native-ble-plx#469]
I am trying to connect a bluetooth device but it requires a pin. Is there any such feature to connect the device with pin?

**Comment by Cierpliwy** [comment]
Pairing procedure is mostly handled by OS. Do you use Android or iOS?

**Comment by NastyZ98** [comment]
Hello @jinqiangg if you have successfully paired your device with a password/pin can you describe the procedure please ?

Thank you,
Nathan.

**Comment by renard12** [comment]
@Cierpliwy 
Hi, so I am using Android 7 and at this OS we have no pairing automatically. 
My code works without issues on Android 8 and higher, so I need to bound manually

**Comment by tangtai** [comment]
I am having similar problem, the device connect requires PIN to establish connection,  the device can be authenticated in bluetooth settings in the android os, but i want the establish connection in ble-plx. i konw you can trigger authentication in application,  i wonder if ble-plx can do it. and if i establish connection using the system, can i still receive data in my bleManager,

**Comment by WarishaAli** [comment]
Hi. I'd also like to connect my android with a bluetooth device without any user input, i.e. no pairing. possible using this library, or possible at all in the android OS?

**Comment by aarthigovardhanan88** [comment]
Any inputs on this?

**Comment by oskarhertzman** [comment]
maybe the creators could be useful for once and answer this thread?
