### ISSUE TITLE
Device.id is undefined v0.4.0

### ISSUE THREAD

**Issue by monumentyusuf** [Polidea/react-native-ble-plx#47]
While i scan with filtering by service uuid, scanned device id property is undefined. It was working great with `v0.3.3`

**Comment by Cierpliwy** [comment]
On what platform do you have an issue? I've just checked implementation on both Android and iOS and I can't find any problems on native and JS side.

**Comment by monumentyusuf** [comment]
Im sorry @Cierpliwy i just forget the mention about platform. Im working with Android

**Comment by Cierpliwy** [comment]
The only thing that comes to my mind right know is that your native library was not rebuild with changes which occurred between 0.3.3 and 0.4.0. Could you clean your Android project and try again? If it doesn't help, please post minimal code snippet which doesn't work correctly.

**Comment by Cierpliwy** [comment]
Could you check if it works on 0.5.0?

**Comment by Cierpliwy** [comment]
Closing as this is an overdue issue which should be working just fine on 0.6.5.
