### ISSUE TITLE
The device found doesn't include the advert service uuid

### ISSUE THREAD

**Issue by ethan6077** [Polidea/react-native-ble-plx#470]
The device found doesn't include the advert service uuid.

I am scaning for two different types of devices at the same time.
I can get both of the them by scanning for a uuid array.
But when the device is detected, I want to further process them based on which uuid they are from. The returned device object doesn't include where it's from(advert uuid). Can we patch the library for this? 
Thanks a lot.

```
this.bleManager.startDeviceScan([advertUuidA, advertuuidB], scanOptions, (error, device) => {
      if (device.advert_uuid === advertUuidA) {
           ....
      }
      if (device.advert_uuid === advertUuidB) {
            ....
      }
    }
);
```

**Comment by Cierpliwy** [comment]
`advertUuidA` or `advertUuidB ` should be present in `device.serviceUUIDs` array. Just remember that values are written there in 128bit UUIDs. You can use `fullUUID` utility function for a comparison. Check documentation.
