### ISSUE TITLE
[Question] Bump native version?

### ISSUE THREAD

**Issue by kevinresol** [Polidea/react-native-ble-plx#473]
For example `implementation "com.polidea.rxandroidble:rxandroidble:1.7.0"`

But apparently the upstream native library is at `1.10.0`. Will this library get a bump?

**Comment by dariuszseweryn** [comment]
Eventually yes but not yet. 

`1.10.0` is an `RxJava 2` library where this one uses the `RxJava 1` branch — which is up to date. There is [a blocking issue](https://github.com/Polidea/RxAndroidBle/wiki/FAQ:-UndeliverableException) with the `RxJava 2` implementation. When it will be solved the bump will happen.

Best Regards
