### ISSUE TITLE
Covert Values from MonitorCharacteristicsForService

### ISSUE THREAD

**Issue by keyz23** [Polidea/react-native-ble-plx#476]
I guys, I'm using your library to connect to a BLE device with Android Device.
I have a question for you, when I use monitorCharacteristicForService for services and characteristics I receive data in this format, but i need to have numbers (like battery number):

    Accelerometer + Gyroscope: "zLAi/wD/SpwiAOv/VwBnAML/xQE="

    Pressure: "bgBvAHAAcQByAA="

    Battery: "ChYKARoA"
 
Do you know what kind of data are these? And How can i convert to int? 
Thank you

**Comment by dariuszseweryn** [comment]
Please check project Wiki
