### ISSUE TITLE
BleError: Cannot start scanning operation

### ISSUE THREAD

**Issue by VihangaAshinsana** [Polidea/react-native-ble-plx#479]
I'm getting the following error when I'm trying to call `this.manager.startDeviceScan` method.  I did the following but non of them solved the issue.
`BleError: Cannot start scanning operation`

`AndroidManifest ` file has the following
```
<uses-permission android:name="android.permission.BLUETOOTH"/>
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
<uses-permission-sdk-23 android:name="android.permission.ACCESS_COARSE_LOCATION"/>
<uses-feature android:name="android.hardware.bluetooth_le" android:required="true"/>
```
Both phones had bluetooth enabled and location enabled.
- Restarted my phone(Huawei GR5 2017: Android Nougat) and tried to call the method(No other apps were running).
- Tried using a different device (Nokia 8: Android Pie )

How can i sort this out?
Thanks

PS: This is the same error which mentioned in Issue #390. Opened a new issue because the issue #390 is closed and I have tried all the methods mentioned in that issue.

**Comment by dariuszseweryn** [comment]
https://github.com/Polidea/react-native-ble-plx/wiki/=-FAQ:-I-got-an-BleError.-Now-what%3F
