### ISSUE TITLE
ScanCallbackType not working

### ISSUE THREAD

**Issue by yoppoy** [Polidea/react-native-ble-plx#482]
Hi,

As my app needs to scan about 50 ble devices around it, optimisation is important on my end. I wanted to change callbackType to FirstMatch. 
```
this.manager.startDeviceScan(null, {scanMode: 2, callbackType: 2}, (error, device) => {
      if (error) {
        this.props.error(error);
        return
      }
      this.addScannedDevice(device);
    });
```

After doing that, every time I start a scan I get this error : 
```BleError: Cannot start scanning operation```

I am testing on a Xiaomi MI8 on android Pie.

Any ideas how I can make first match work ? I am using the latest version of react-native-ble-plx.

Thanks in advance

**Comment by dariuszseweryn** [comment]
Have you checked the [wiki FAQ](https://github.com/Polidea/react-native-ble-plx/wiki/=-FAQ:-I-got-a-BleError.-Now-what%3F)?

**Comment by yoppoy** [comment]
Thanks for your quick response. I hadn't had a read at it. I was just printing the BleError without stringifying it, turns out the feature isn't supported on my device sadly. Have a great day and thank you again for your hard work

**Comment by AjayParambath** [comment]
> 
> ```
> this.manager.startDeviceScan(null, { callbackType: ScanCallbackType.FirstMatch}, (error, device) => {
>       if (error) {
>         this.props.error(error);
>         return
>       }
>       this.addScannedDevice(device);
>     });
> ```
> try this
