### ISSUE TITLE
Using BLE in background on Android

### ISSUE THREAD

**Issue by keyz23** [Polidea/react-native-ble-plx#484]
Hi everyone, I use this library on my Android App, but I need to use also BLE in background! It's possible to do on Android Device with this module?
Thank you

**Comment by njdullea** [comment]
Hey @keyz23 did you ever get an answer?

**Comment by curest0x1021** [comment]
I need to get the BLE signals even though the app is in the background on both of iOS and Android devices.
@keyz23 Did you solve the background issue? If you already solved this problem please let me know the solution.

Thanks.

**Comment by ezranbayantemur** [comment]
Any update?

**Comment by dariuszseweryn** [comment]
On Android one needs to implement a Foreground Service to keep the Application process running. You can find more info on that using Google.

**Comment by ezranbayantemur** [comment]
> On Android one needs to implement a Foreground Service to keep the Application process running. You can find more info on that using Google.

Thank you for your quick response.
I haven't try but does [react-native-background-task](https://github.com/jamesisaac/react-native-background-task) package handles foreground service implementation?

**Comment by dariuszseweryn** [comment]
> I haven't try but does react-native-background-task package handles foreground service implementation?

I am not familiar with this library

**Comment by jordan-tpz** [comment]
> On Android one needs to implement a Foreground Service to keep the Application process running. You can find more info on that using Google.

@dariuszseweryn If I want to keep the connection with my BLE device in background on Android, I understood I have to create a specific task (using foreground service). 

My question is : do you think I should use the `connectToDevice()` function in this task when I connect my BLE device with my app ? (and I could remove this task when I would like to disconnect my BLE device)
But, another solution : maybe quite simply I should create the BleManager instance within this task ?

**Comment by dariuszseweryn** [comment]
It all depends on how you want to architecture your app. This topic is very wide and subjective — personally I tend to have a single object managing the connection.
