### ISSUE TITLE
[Android] Empty array of services without any error

### ISSUE THREAD

**Issue by inotekk** [Polidea/react-native-ble-plx#488]
Hi,

We currently use react-native-ble-plx 1.0.3 in a project for iOS and Android.

We have a raspberry pi 3 acting as :
- a Central module to connect to another bluetooth device thanks to Noble library
- a Peripheral using Bleno library to allow connection from our react native projet (mobile app)

_Note : we see the warning on Bleno page about using bleno in tandem with noble and we follow the guide and all requirements, and it works... at least for iOS. So we think that the problem is not on the raspberry._

Everything works well on iOS : 
1. the raspberry is found
2. the connection works
3. then we call discoverAllServicesAndCharacteristics, all works
4. then we call servicesForDevice : our 2 services are found
5. then we call writeCharacteristicWithResponse and all works as intended

On android, 3 first steps works but servicesForDevice returns an empty array of services without any error. 

We also try, after discovering to call directly writeCharacteristicWithResponseForDevice but we get an error "Service 7F3F1BAA-0013-462B-A236-016C66BF2648 for device ? not found".

We saw this disclaimer on the wiki/Device-Service-Discovery :
> On some older Android devices there is a known bug. The service discovery is resolved with an empty array of services without any error. What usually helps is to disconnect/powercycle bluetooth adapter. We do not have a pair of device/peripheral that would reliably show this behaviour to workaround it—if someone would be able to reproduce this feel free to open an issue and help us fix it.

So, how could we work together to fix this issue please ?

Thanks for your help.
Kind regards.

**Comment by dariuszseweryn** [comment]
Could you follow the template and add all required info?
