### ISSUE TITLE
Bug Report: [iOS Background & Suspended mode]"the callback never gets invoked in the startDeviceScan "

### ISSUE THREAD

**Issue by GeekChao** [Polidea/react-native-ble-plx#494]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [Yes ] I am running the latest version
- [Yes ] I checked the documentation and found no answer
- [ Yes] I checked to make sure that this issue has not already been filed

## Expected Behavior
When the app is even in the background or suspended mode of ios, the callback of the startDeviceScan gets invoked.

## Current Behavior
When the app is in the background or suspended mode of ios, the callback of the startDeviceScan never gets invoked. I assume there is never discovery event found yet, according to the apple ble doc. Is it possible to configure the 'startDeviceScan' to make the app scan in the background and suspended mode? Thank you

### Context
IOS Background and suspended mode

* Library version: 1.0.3
* Platform: iOS.
* Platform logs (XCode):

**Comment by jayrenteria** [comment]
@GeekChao did you find a solution for this?

**Comment by joaomdmoura** [comment]
Same issue, any updates?
