### ISSUE TITLE
Android: bleglattexception 133 & Chrome Debugger

### ISSUE THREAD

**Issue by stinodes** [Polidea/react-native-ble-plx#50]
I have been working with your library for the past couple of weeks now, and it works great. Although sometimes (seemingly inexplicable), I consistently get `bleglattexception 133` on my Android device (HTC M9 running Android 6.0.0).  

Answers on other issues mentioned using timeouts in between various connects / calls, which did not change anything in my particular case.
___
After not being able to pinpoint the issue and just letting it be for now, I have found out that this occurs when I am using Chrome as debugger.  

The solutions proposed in other issues did not help in my case (at least the ones I could apply without editing dependencies).

I do not know whether that is something that can be fixed, but I thought sharing my findings would still be worthwhile for anyone else experiencing similar issues.

**Comment by Cierpliwy** [comment]
Error 133 often happens during connection problems and most of the time the only solution is to try establish it once again. In worst cases you have to reset BLE stack on your phone. I'm closing this issue as it is not directly related to this library.
