### ISSUE TITLE
How do I disconnect the connected device on button press?

### ISSUE THREAD

**Issue by 50shashwat** [Polidea/react-native-ble-plx#505]
-  I am running the latest version 0.60.3 (react-native) with 1.0.3 rn-ble-plx library

I couldn't find any code related to disconnecting the device when its already connected.

**Comment by chaselal** [comment]
Try `BleManager.cancelDeviceConnection`. https://polidea.github.io/react-native-ble-plx/#blemanagercanceldeviceconnection
