### ISSUE TITLE
Question: Beacon support

### ISSUE THREAD

**Issue by farzd** [Polidea/react-native-ble-plx#516]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active) or on our [Gitter](https://gitter.im/RxBLELibraries/react-native-ble) channel.

## Question

Is there any reason this cant identify beacons ? i've tried scanning with the beacon UUID. Leaving the array as null only identifies my Mac bluetooth address. Testing it on iOS 12/iPhone 7

**Comment by dariuszseweryn** [comment]
> Is there any reason this cant identify beacons ?

Yes, iOS uses a completely separate API for Beacons

I will try to add a wiki page for this topic in the future

**Comment by dariuszseweryn** [comment]
https://github.com/Polidea/react-native-ble-plx/wiki/=-FAQ:-Beacons

**Comment by farzd** [comment]
Thanks for the speedy reply
