### ISSUE TITLE
Feature Request: Request for Permissions inside of Library.

### ISSUE THREAD

**Issue by wongcoder** [Polidea/react-native-ble-plx#517]
## Current Behavior

If you call startDeviceScan(), it will fail due to not having sufficient permissions in Android. This is because dangerous permissions must be called in runtime.

## New behavior

On startDeviceScan(), call PermissionsAndroid.

------------------------------------------------------------

The implementation of this seems pretty trivial if you can outright import react-native, and call PermissionsAndroid from there; however, putting react-native in a library might not be the best solution. 

Perhaps implementing a native Android solution would be nice here.

**Comment by Cierpliwy** [comment]
To be honest, I'm against magic features, which will happen behind the scenes. PermissionsAndroid API is fine by itself and I know that UX/UI designers would like to have control when system popup appears to make the less distractive process. We would like to be flexible there.
