### ISSUE TITLE
Question: writeCharacteristicWithResponseForService the promise always returns "Operation was rejected"

### ISSUE THREAD

**Issue by Chourioz** [Polidea/react-native-ble-plx#522]
## Prerequisites
React Native 0.60.4
React Native Ble Plx 1.0.3
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active) or on our [Gitter](https://gitter.im/RxBLELibraries/react-native-ble) channel.

## Question
Hello, I'm develop application to connect with smart bands, but when I write characteristic (00002a37-0000-1000-8000-00805f9b34fb) of heart rate service (0000180d-0000-1000-8000-00805f9b34fb), the promise always returns error and message is "Operation was rejected".

### My code is:

```javascript
const numberBuffer = Buffer.alloc(2);
numberBuffer.writeUInt16LE(1, 0);
console.warn(numberBuffer.toString('base64'))
const characteristic = await device.writeCharacteristicWithResponseForService(
   service, characteristicW, numberBuffer.toString('base64')
)
```

**Comment by Cierpliwy** [comment]
Characteristic 0x2A37 in service 0x180D is notify only, [it can't be read.](https://www.bluetooth.com/wp-content/uploads/Sitecore-Media-Library/Gatt/Xml/Services/org.bluetooth.service.heart_rate.xml)

**Comment by Marvedog** [comment]
### Addendum: 
How do you notify a characteristic that is notifiable only? If it isn't write-able, the promise always returns "Operation was rejected" (using the approach from the docs).

**Comment by akram-beleaf** [comment]
Hello Everyone 
I'm using an ESP32 and want to connect it with my app using bluetooth. 
I'm also facing similar issue. I'm trying writeCharacteristicWithResponseForService and getting the same error 

====>   **BleError:Operation was rejected**

Please help

here is my code for reference

`import React, { useEffect, useState } from "react";
import { Button, PermissionsAndroid, Platform, Text } from "react-native"
import { BleManager } from "react-native-ble-plx";
import { Buffer } from 'buffer'

const BLEServiceUUID = "6e400001-b5a3-f393-e0a9-e50e24dcca9e";
const BLEReadUUID = "6e400002-b5a3-f393-e0a9-e50e24dcca9e";
const BLEWriteUUID = "6e400003-b5a3-f393-e0a9-e50e24dcca9e";
const deviceID = "D8:BC:38:F9:0C:2A";

const bleManager = new BleManager();

const BleSerialComponent = () => {
    const [device, setDevice] = useState(null);

    const requestBluetoothPermission = async () => {
        if (Platform.OS === 'ios') {
            return true
        }
        if (Platform.OS === 'android' && PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION) {
            const apiLevel = parseInt(Platform.Version.toString(), 10)

            if (apiLevel < 31) {
                const result = await PermissionsAndroid.requestMultiple([
                    PermissionsAndroid.PERMISSIONS.BLUETOOTH_SCAN,
                    PermissionsAndroid.PERMISSIONS.BLUETOOTH_CONNECT
                ])
                return result
            }
            if (PermissionsAndroid.PERMISSIONS.BLUETOOTH_SCAN && PermissionsAndroid.PERMISSIONS.BLUETOOTH_CONNECT) {
                const result = await PermissionsAndroid.requestMultiple([
                    PermissionsAndroid.PERMISSIONS.BLUETOOTH_SCAN,
                    PermissionsAndroid.PERMISSIONS.BLUETOOTH_CONNECT,
                    PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION
                ])

                return (
                    result['android.permission.BLUETOOTH_CONNECT'] === PermissionsAndroid.RESULTS.GRANTED &&
                    result['android.permission.BLUETOOTH_SCAN'] === PermissionsAndroid.RESULTS.GRANTED &&
                    result['android.permission.ACCESS_FINE_LOCATION'] === PermissionsAndroid.RESULTS.GRANTED
                )
            }
        }
        return false
    }


    useEffect(() => {

        requestBluetoothPermission()
        return () => {
            device && device.cancelConnection();
        };
    }, []);

    const handleWrite = async () => {
        let data = Buffer.from('Hello', 'utf-8').toString('base64')
        console.log(data);
        const services = await device.discoverAllServicesAndCharacteristics();
        if (device) {
            try {
                const characteristic =
                    await device.writeCharacteristicWithResponseForService(
                        BLEServiceUUID,
                        BLEWriteUUID,
                        data
                    );
                console.log("Data successfully written.", characteristic);
                device.monitorCharacteristicForService(BLEServiceUUID, characteristic, (error, characteristic) => {
                    if (error) {
                        this.error(error.message)
                        return
                    }
                    console.log("Data successfully written.---->", characteristic);
                    // this.updateValue(characteristic.uuid, characteristic.value)
                })
            } catch (error) {
                console.log(error);
            }
        }
    };

    const handleRead = async () => {
        const result = await device.discoverAllServicesAndCharacteristics();
        console.log('discovered--->', result);
        if (device) {
            try {
                const characteristic = await device.readCharacteristicForService(
                    BLEServiceUUID,
                    BLEReadUUID
                );
                console.log("Read data:", characteristic.value);
            } catch (error) {
                console.log(error);
            }

        }
    };

    const scanAndConnect = () => {
        bleManager.startDeviceScan(null, null, (error, scannedDevice) => {
            if (error) {
                console.error("Error scanning for devices.", error);
                return;
            }
            if (scannedDevice?.name === 'BleBridge-0C2A') {
                console.log(scannedDevice);
                bleManager.stopDeviceScan();
                scannedDevice
                    .connect()
                    .then((connectedDevice) => {
                        setDevice(connectedDevice);
                        console.log('connected');
                    })
                    .catch((error) => {
                        console.error("Error connecting to device.", error);
                    });
            }
        });
    }

    const disconnectDevice = async () => {
        try {
            if (!device) {
                console.log('No device connected');
                return;
            }

            await device.cancelConnection();
            setDevice(null);
        } catch (error) {
            console.log('Error disconnecting:', error);
        }
    };

    const checkConnection = async () => {
        let result = await bleManager.isDeviceConnected(device?.id)
        console.log(result);
    }
    const connectDevice = async () => {
        let result = await bleManager.connectToDevice(device?.id).then(device => {
            // Discover services and characteristics
            return device.discoverAllServicesAndCharacteristics();
        })
            .then(device => {
                // Find the characteristic to write to
                return device.characteristicsForService(BLEServiceUUID);
            })
            .then(characteristics => {
                // Find the characteristic to write to
                const characteristic = characteristics.find(c => c.uuid === BLEWriteUUID);
                if (!characteristic) {
                    throw new Error('Characteristic not found');
                }
                // Write data to the characteristic
                console.log(characteristic, '---------------->');
                return characteristic.isWritableWithoutResponse
            })
            .then((e) => {
                console.log('Write operation successful', e);
            })
            .catch(error => {
                console.error('Error performing write operation:', error);
            });
        console.log('----', result);
        // BleManagerrr.connect(device?.id)
        // .then(() => {
        //   // Success code
        //   console.log("Connected");
        // })
        // .catch((error) => {
        //   // Failure code
        //   console.log(error);
        // });

    }



    return (
        <>
            <Text>{device ? "Connected to:" + (device?.name || '') + "--"(device?.id || '') : 'No device connected'}</Text>
            {device ? (
                <Button title="Disconnect" onPress={disconnectDevice} />
            ) : (
                <Button title="Scan and Connect" onPress={scanAndConnect} />
            )}
            <Button title={'write'} onPress={handleWrite} />
            <Button title={'read'} onPress={handleRead} />
            <Button title={'checkConnection'} onPress={checkConnection} />
            <Button title={'connectDevice'} onPress={connectDevice} />
        </>
    )
};

export default BleSerialComponent;`

after connecting to the esp32 when I press handleWrite the I get this error.
