### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by HectorLobatoSilva** [Polidea/react-native-ble-plx#524]
Hello, i get this json and name it's null

{ overflowServiceUUIDs: null,
08-13 16:58:45.152 13235 14506 I ReactNativeJS:   isConnectable: null,
08-13 16:58:45.152 13235 14506 I ReactNativeJS:   solicitedServiceUUIDs: null,
08-13 16:58:45.152 13235 14506 I ReactNativeJS:   txPowerLevel: null,
08-13 16:58:45.152 13235 14506 I ReactNativeJS:   localName: null,
08-13 16:58:45.152 13235 14506 I ReactNativeJS:   serviceUUIDs: null,
08-13 16:58:45.152 13235 14506 I ReactNativeJS:   serviceData: null,
08-13 16:58:45.152 13235 14506 I ReactNativeJS:   manufacturerData: 'TAAQBQscj0MW',
08-13 16:58:45.152 13235 14506 I ReactNativeJS:   mtu: 23,
08-13 16:58:45.152 13235 14506 I ReactNativeJS:   rssi: -77,
08-13 16:58:45.152 13235 14506 I ReactNativeJS:   name: null,
08-13 16:58:45.152 13235 14506 I ReactNativeJS:   id: '38:F9:D3:E1:2B:2A',
08-13 16:58:45.152 13235 14506 I ReactNativeJS:   _manager: 
08-13 16:58:45.152 13235 14506 I ReactNativeJS:    { _eventEmitter: 
08-13 16:58:45.152 13235 14506 I ReactNativeJS:       { _subscriber: 
08-13 16:58:45.152 13235 14506 I ReactNativeJS:          { _subscriptionsForType: 
08-13 16:58:45.152 13235 14506 I ReactNativeJS:             { appStateDidChange: 
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                [ { subscriber: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    emitter: 
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                     { _subscriber: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                       isAvailable: true,
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                       _eventHandlers: { change: {}, memoryWarning: {} },
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                       currentState: 'active' },
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    listener: [Function],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    context: undefined,
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    eventType: 'appStateDidChange',
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    key: 0 } ],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:               websocketMessage: [  ],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:               websocketOpen: [  ],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:               websocketClosed: [  ],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:               websocketFailed: [  ],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:               didUpdateDimensions: 
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                [ { subscriber: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    emitter: 
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                     { _subscriber: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                       sharedSubscriber: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                       _currentSubscription: 
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                        { subscriber: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                          emitter: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                          listener: [Function: scanListener],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                          context: undefined,
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                          eventType: 'ScanEvent',
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                          key: 1 } },
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    listener: [Function],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    context: undefined,
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    eventType: 'didUpdateDimensions',
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    key: 0 } ],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:               hardwareBackPress: 
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                [ { subscriber: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    emitter: 
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                     { _subscriber: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                       sharedSubscriber: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                       _currentSubscription: 
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                        { subscriber: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                          emitter: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                          listener: [Function: scanListener],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                          context: undefined,
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                          eventType: 'ScanEvent',
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                          key: 1 } },
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    listener: [Function],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    context: undefined,
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    eventType: 'hardwareBackPress',
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    key: 0 } ],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:               collectBugExtraData: 
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                [ { subscriber: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    emitter: 
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                     { _subscriber: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                       sharedSubscriber: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                       _currentSubscription: 
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                        { subscriber: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                          emitter: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                          listener: [Function: scanListener],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                          context: undefined,
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                          eventType: 'ScanEvent',
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                          key: 1 } },
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    listener: [Function: collectExtraData],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    context: null,
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    eventType: 'collectBugExtraData',
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    key: 0 } ],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:               collectRedBoxExtraData: 
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                [ { subscriber: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    emitter: 
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                     { _subscriber: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                       sharedSubscriber: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                       _currentSubscription: 
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                        { subscriber: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                          emitter: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                          listener: [Function: scanListener],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                          context: undefined,
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                          eventType: 'ScanEvent',
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                          key: 1 } },
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    listener: [Function: collectExtraData],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    context: null,
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    eventType: 'collectRedBoxExtraData',
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    key: 0 } ],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:               StateChangeEvent: [ ,  ],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:               toggleElementInspector: 
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                [ { subscriber: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                    emitter: 
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                     { _subscriber: [Circular],
08-13 16:58:45.152 13235 14506 I ReactNativeJS:                       sharedSu

**Comment by dariuszseweryn** [comment]
name can be null
