### ISSUE TITLE
Handling case where BLE is turned on before opening app on iOS

### ISSUE THREAD

**Issue by henry132109** [Polidea/react-native-ble-plx#526]
I see that the documentation mentions that:
> When iOS application launches BLE stack is not immediately available and we need to check its status. To detect current state and following state changes we can use onStateChange() function

I'm using this snippet in **componentDidMount**:
```
if (Platform.OS === 'ios') 
  const subscription = this.manager.onStateChange((state) => {
    if (state === 'PoweredOn'){
      //do my stuff
      subscription.remove();
    }
  })
} else {
  this.manager.state().then((state)=>{
    if(state === 'PoweredOn'){
      //do my stuff
    }else{
      this.manager.enable().then(()=>{
        //do my stuff
      });
    }
  })
}
```

But my stuff doesn't fire when BLE was turned on before opening the app.
How do I ensure my event can be fired and fired only once?

**Comment by Cierpliwy** [comment]
If you really want to check it once you can use [`state()`](https://polidea.github.io/react-native-ble-plx/#blemanagerstate) function directly. However, I would recommend to use [`onStateChange(listener, emitCurrentState`)](https://polidea.github.io/react-native-ble-plx/#blemanageronstatechange) with last parameter set to true.

**Comment by henry132109** [comment]
Thank you for your quick reply!
I'm referring to my colleague and see if it works out :)

**Comment by henry132109** [comment]
It worked like charm, dziękuję!
