### ISSUE TITLE
How to print photos via thermal printer?

### ISSUE THREAD

**Issue by PhamMinhKha** [Polidea/react-native-ble-plx#534]
I hope someone can show me how to print images via react-native-ble-plx
- [✔︎] I am running the latest version
- [✔︎] I checked the documentation and found no answer
- [✔︎] I checked to make sure that this issue has not already been filed

**This is my device print**
https://bit.ly/2lIsVgK

**I was able to print the text with this code**
```
await device
      .discoverAllServicesAndCharacteristics()
      .catch(err => console.log(err));
    var services = device.services();
    services
      .then(async value => {
        value[3].characteristics().then(char => {
          char[0].writeWithoutResponse('aGVsbG8gd29ybGQK');
        });
      }).catch(bigerror => console.log('big err'));
````
![20190911_194354](https://user-images.githubusercontent.com/12944689/64698395-ffb54f00-d4cc-11e9-88aa-cf28de97e637.jpg)

**Comment by Cierpliwy** [comment]
We don't troubleshoot problems which are not related to the library itself. This includes an understanding of how the API works on certain types of peripherals.
