### ISSUE TITLE
Remove const enums from index.d.ts do it works with --isolatedModules

### ISSUE THREAD

**Issue by Barbiero** [Polidea/react-native-ble-plx#537]
## Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Expected Behavior

There should be no typescript errors with --isolatedModules, which is recommended for react-native typescript since typescript const enums don't work with babel

## Current Behavior

Currently, every enum on index.d.ts is defines as a `const enum`. These are not compatible with `--isolatedModules`(see microsoft/Typescript#207). However, babel does not support const enums (babel/babel#8741) which means that when writing RN projects with typescript, using `--isolatedModules` guarantess the programmers won't accidentally add in const enums and break code unknowingly.

In practice, react-native-ble-plx doesn't actually *use* typescript const enums(which is what is declared in the .d.ts), which means that it's fine to run the library without isolatedmodules since we're not really compiling typescript through babel; However, this particular change creates a conflict when using that particular option at no real benefit from what I can gather.

### Steps to Reproduce

write any code with `isolatedModules` enabled on `tsconfig.json`, and you'll see that your IDE(if it uses the ts language server) will complain when using ble-plx enums.

**Comment by Cierpliwy** [comment]
I'd love PR for that change. I'm not an active Typescript user and I have limited time to do all of the things.
