### ISSUE TITLE
iOS 13 - canSendWriteWithoutResponse is only available in iOS 11 or higher.

### ISSUE THREAD

**Issue by AdamGold** [Polidea/react-native-ble-plx#545]
## Expected Behavior

Successful build.

## Current Behavior

Prior to the iOS 13 update, everything ran correctly. After the update, XCode fails to build with the exception - 
`canSendWriteWithoutResponse  is only available in iOS 11 or higher.`

![Screen Shot 2019-09-23 at 11 26 35](https://user-images.githubusercontent.com/747847/65411347-4cfebe00-ddf5-11e9-8eee-da02d00f1ed8.png)

**Comment by ppietruszewskiinfullmobile** [comment]
@AdamGold How did you resolved this issue?

**Comment by AdamGold** [comment]
@ppietruszewskiinfullmobile Upgraded to the latest version - `1.1.0` :)
