### ISSUE TITLE
Command /bin/sh failed with exit code 1

### ISSUE THREAD

**Issue by WillDent** [Polidea/react-native-ble-plx#55]
Unrecognized arguments: "/Users/willdent/Library/Developer/Xcode/DerivedData/ble-ausclppugcjrecboiwdlaycdoyfq/Build/Intermediates/ble.build/Debug-iphoneos/ble.build/Script-5D4CFAB11E7BFAE5005783F4.sh"
Command /bin/sh failed with exit code 1

Running this on:
Version 8.2.1 (8C1002)

**Comment by haohcraft** [comment]
any update?

**Comment by WillDent** [comment]
@haohcraft maybe we can help one another?  Are you pulling from master or using what is in NPM?

I tried with npm.  Guess I will try from master.

**Comment by haohcraft** [comment]
@WillDent so I have resolved this. I had put the `copy-frameworks` script in the wrong place. Could you share me with a screenshot of your Run Script setting in xcode? I could take a look.

**Comment by tuantle** [comment]
Hi, I have the same issue. And this what I have set.
<img width="1058" alt="screen shot 2017-03-23 at 1 17 45 pm" src="https://cloud.githubusercontent.com/assets/4650277/24268493/33071f4c-0fcb-11e7-9117-b70c7443752d.png">

**Comment by haohcraft** [comment]
1. make sure `carthage` has installed
2. make sure the frameworks have been in `node_modules/react-native-ble-plx/ios/BleClientManager/Carthage/Build/iOS/`, otherwise you should re npm install the lib
3. and my `run script` looks like below:

![screen shot 2017-03-20 at 9 06 58 am](https://cloud.githubusercontent.com/assets/3459080/24295792/ccc45b8e-1072-11e7-92aa-730a5baa6186.png)

**Comment by tuantle** [comment]
Thanks. That fixed it for me, I originally put the copy-frameworks line in the Shell input box.

**Comment by WillDent** [comment]
@haohcraft @tuantle got this working. thanks

**Comment by ykcai** [comment]
I am getting ```[34;1m***[0m Please update to the latest Carthage version: 0.21.0. You currently are on 0.20.1
Failed to read file or folder at /Users/michaelcai/Desktop/React/IoTApp/ios/../node_modules/react-native-ble-plx/ios/BleClientManager/Carthage/Build/iOS/RxBluetoothKit.framework

Command /bin/sh failed with exit code 1```

**Comment by Cierpliwy** [comment]
Probably you didn't build iOS frameworks properly. Does carthage finish successfully when react-native-ble-plx is installed? Please check all manual steps.

**Comment by nickvido** [comment]
I'm having the same problem. The specified folder exists:

```
$ ls -la node_modules/react-native-ble-plx/ios/BleClientManager/Carthage/Build/iOS/RxBluetoothKit.framework
total 12672
drwxr-xr-x   6 myname  myrole      204 Aug 13 20:46 .
drwxr-xr-x  24 myname  myrole      816 Aug 13 20:46 ..
drwxr-xr-x   3 myname  myrole      102 Aug 13 20:46 Headers
-rw-r--r--   1 myname  myrole      769 Aug 13 20:46 Info.plist
drwxr-xr-x   4 myname  myrole      136 Aug 13 20:46 Modules
-rwxr-xr-x   1 myname  myrole  6480052 Aug 13 20:46 RxBluetoothKit
```

Version information:
```
"react": "16.0.0-alpha.12",
"react-native": "^0.46.1",
"react-native-ble-plx": "^0.6.1",
XCode: 8.3.3 (8E3004b)
```

**Comment by nisargap** [comment]
Same issue

**Comment by nisargap** [comment]
@nickvido did you ever figure it out?

**Comment by nisargap** [comment]
@nickvido  I fixed that problem by using an absolute path for RxBluetoothKit.framework

**Comment by rynop** [comment]
I get the same error as well, but on `Carthage/Build/iOS/RxSwift.framework`.  If I hard code input files in `Run Script` like @nisargap does I do not get the error.  Folder exists.

```
xcode Version 9.1 (9B55)
react@16.0.0-alpha.6
react-native@0.44.0
react-native-ble-plx@0.6.4
carthage version 0.26.2
```

FWIW I also ran into issue on Xcode v9.0.  I've tried cleaning project (cmd+opt+shift+k) no use.

@Cierpliwy any idea what is going wrong? Hard code kills team development.

**Comment by nickvido** [comment]
I ended up scrapping the whole thing and re-creating the app using `react-native init` instead of `create-react-native-app`. I also switched to just using the `react-native-ble-manager` package that this package references.

**Comment by rynop** [comment]
@nickvido thanks. Curious, where do you see `react-native-ble-manager` referenced to in this project? I dont see it in `package.json` and don't find any codehits. Just wondering what the diff is between this project and `react-native-ble-manager`.

The other piece of info I did not mention yesterday, was my project was started with this boilerplate: https://github.com/junedomingo/movieapp so wonder if not starting clean as you mention has something to do with this issue.

**Comment by vadimue** [comment]
@haohcraft Thanks, you save my time!

**Comment by seriph** [comment]
@rynop @nickvido The issue here actually turned out to be caused by copying these Input Files from the install instructions. It copied a newline character due to the way the md file is formatted. Close inspection of the logs (reading through all the environment variables) revealed this.
@Cierpliwy I think we should place a note warning against this in the install instructions or reformat it to be less likely.

**Comment by Pouria22** [comment]
I had this issue because i denied keychain access
