### ISSUE TITLE
Create BleManager() without a native component

### ISSUE THREAD

**Issue by dschinkel** [Polidea/react-native-ble-plx#551]
I'm abstracting ble logic out of my native components and pushing that down to be functional behavior that lives out side my component.  

I created a function in a JS Custom Component of mine that tries to use the manager:
```
import { BleManager } from 'react-native-ble-plx';

function _BluetoothConnector(device) {

  const manager = new BleManager();

  function scanForDevice(){
	manager.startDeviceScan(null, null, (error, device) => {
      return device;
  });
}

  return {scanForDevice}
}

function BluetoothConnector(device){
  return _BluetoothConnector(device)
}

export default BluetoothConnector;
```

When I run my unit test that creates an instance of my BluetoothConnector, I get `Cannot read property 'createClient' of undefined` once it hits ` const manager = new BleManager();` during the creation of my BluetoothConnector module, and then ultimately bombs out at `BleModule.createClient(options.restoreStateIdentifier || null)` in BleManager.js, it can't create **BleModule** and I'm not sure how that wires up and works in the case of a headless unit test like this.

I went through the docs, step by step and still I have this issue.  Is it just simply not possible to do that without a React Native component?  OR is there something I can do here to decouple the bluetooth logic from react native components.  Ultimately my React Native component will call my `scanForDevice` method later, but I'm test driving lower down first...or at least trying to.

Ultimately what I'm trying to do I probably can't I probably need to write a test that's testing through a real device.

**Comment by mlisik** [comment]
Can you post the contents of the failing unit test (imports, mocks, test itself)? Perhaps it would be fixed by simply mocking out the dependency like so: `jest.mock('react-native-ble-plx');`?

**Comment by riegaz** [comment]
I do have the same issue. Can anyone help me? I'm completely new.

![image](https://user-images.githubusercontent.com/1749401/74594892-b1881700-503b-11ea-8a37-e7b4a6d35e82.png)

**Comment by Cierpliwy** [comment]
It means that BLE native module is not properly loaded. Please recheck instruction steps and make sure you link your native dependencies from the root of the project.

**Comment by ouya99** [comment]
Any update on this issue? cannot get past the error on Expo

**Comment by aarthigovardhanan88** [comment]
Any updates on this? I am also facing the same issue

**Comment by kriit24** [comment]
same issue

**Comment by KyrolosMagdy** [comment]
Same issue

**Comment by Moyando** [comment]
same issue

**Comment by lokacoding** [comment]
same issue

**Comment by gokhantiknaz** [comment]
same issue.

**Comment by DevKalebe** [comment]
mesmo problema.

**Comment by mathiasnohall** [comment]
same issue

**Comment by Mottion** [comment]
mesmo problema.

**Comment by Naveen-g09** [comment]
have anyone figured it out?

**Comment by Naveen-g09** [comment]
hey @everyone, tis fixed my issue:
```{
  "expo": {
    "plugins": ["react-native-ble-plx"]
  }
}
```

**Comment by MaghsoodTT** [comment]
I did these:
1- useing `npx expo run:android` instead of `npx expo run:android`
2- it only works with USB debugging, before run command connect device to the usb and check connection by `adb devices` 
3- `npx expo run:android` might help
