### ISSUE TITLE
about background mode

### ISSUE THREAD

**Issue by graygray** [Polidea/react-native-ble-plx#558]
## Prerequisites

- [ Y ] I checked the documentation and found no answer
- [ Y ] I checked to make sure that this issue has not already been filed
- [ Y ] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active) or on our [Gitter](https://gitter.im/RxBLELibraries/react-native-ble) channel.

## Question

thank you for the good job first.

** env:
xcode 11, iOS 12.3, rn 0.6

About background mode:

** I tried following:
react-native-background-task or react-native-background-fetch, but it will take 15 min or some random minutes to exe the background task; ( the expected behavior should exe task right the way app goes to background )

** Question:
1. The module seems to support background mode, I want to know if long term background exec is work? 
( see : https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/CoreBluetoothBackgroundProcessingForIOSApps/PerformingTasksWhileYourAppIsInTheBackground.html )
2. is there a long run function can be implemented? if so, simple sample code or little hints will be great.

thanks for answering.

**Comment by njdullea** [comment]
I think the execution of background tasks is handled entirely on the OS side. 

Pretty much the way it works is you can register a task (i'm sure you have read about this while checkout out the other libraries), and then on IOS you get 30 seconds to execute the full task, and on Android there is not a limit but they will discontinue the task if the workload is too much, or other active apps need to run. 

On Android you also have the option to use Headless JS, which will execute the whole app's code in the background periodically, but on IOS there is nothing like this and you are limited to the registered task I mentioned previously. 

So unfortunately I think the answer is mostly there is no long running background function (with the exception of headless js on Android).

If anyone else has corrections of what I have said please let me know, I am still learning this stuff myself!
