### ISSUE TITLE
Which Android-Permissions for BluetoothLE

### ISSUE THREAD

**Issue by Pinny3** [Polidea/react-native-ble-plx#559]
Hi there I am facing this problem using 

targetSdkVersion 28 for **Android**, 

which is required to upload the App to Google PlayStore:

> 10-16 18:20:15.179  7747  7933 I ReactNativeJS: 'Error at device scan', { [Error: Device is not authorized to use BluetoothLE]
>10-16 18:20:15.179  7747  7933 I ReactNativeJS:   errorCode: 101,
>10-16 18:20:15.179  7747  7933 I ReactNativeJS:   attErrorCode: null,
>10-16 18:20:15.179  7747  7933 I ReactNativeJS:   iosErrorCode: null,
>10-16 18:20:15.179  7747  7933 I ReactNativeJS:   androidErrorCode: null,
>10-16 18:20:15.179  7747  7933 I ReactNativeJS:   reason: 'Location Permission missing (code 3)' }
>10-16 18:20:15.180  7747  7933 I ReactNativeJS: Error scanning devices

According to 

https://github.com/Polidea/react-native-ble-plx/issues/248

I have to ask the user for the proper permission, using the way described here

https://facebook.github.io/react-native/docs/permissionsandroid.html

But I wonder what the proper permission is I have to ask for.

Please advise....

**Comment by wfischer42** [comment]
I ran into this problem also, and fixed it with the `android.permission.ACCESS_COARSE_LOCATION` in PermissionsAndroid. 

The android setup docs have you add that permission to `AndroidManifest.xml`, but your error said your Location Permission is missing, which is the "dangerous" permission that can be handled with `PermissionsAndroid` in SDK >= 23. For quick verification, see if it works by manually turning on the Location permission in Settings > Application Manager.
