### ISSUE TITLE
Does it support classic bluetooth (non BLE) device?

### ISSUE THREAD

**Issue by tienw** [Polidea/react-native-ble-plx#564]
I was able to connect to the bluetooth printer and write comman to print using the react-native-ble-plx. However, due to firmware update, the priner no longer support bluetooth low energy and the code stop working. Do you know if the library will support bluetooth classic ?

Thank you in advance

react-native 0.59.1

**Comment by WhaSukGO** [comment]
Yes, I want to know if it supports bluetooth classic!
