### ISSUE TITLE
bash 

### ISSUE THREAD

**Issue by ecasona** [Polidea/react-native-ble-plx#57]
npm ERR! react-native-ble-plx@0.4.0 postinstall: `bash build_ios_frameworks.sh`
npm ERR! Exit status 1

**Comment by ecasona** [comment]
what can i do

**Comment by haohcraft** [comment]
Have you installed  Carthage before running npm install ?

**Comment by ecasona** [comment]
@haohcraft  I have tried npm install carthage  ,but the problem exits already.
 > react-native-ble-plx@0.4.0 postinstall E:\react native\work_place\test_ble\node_modules\react-native-ble-plx
> bash build_ios_frameworks.sh

'bash' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

I am in windows dev envirenment。

**Comment by m7775223** [comment]
I also encountered this problem in windows dev envirenment。 What else do you do before you install the npm install react-native-ble-plx？

**Comment by Cierpliwy** [comment]
On Windows you have to have bash in system path to install this library. It is something which could be improved.

**Comment by Cierpliwy** [comment]
Bash is not used anymore in build process.
