### ISSUE TITLE
Is there a way to turn the scan function into an async function?

### ISSUE THREAD

**Issue by Stedelie** [Polidea/react-native-ble-plx#572]
Hello there, I'm wondering if there's a way to make the scan function async.
I'm referring to this function:

```
scanAndConnect() {
    this.manager.startDeviceScan(null, null, (error, device) => {
        if (error) {
            // Handle error (scanning will be stopped automatically)
            return
        }

        // Check if it is a device you are looking for based on advertisement data
        // or other criteria.
        if (device.name === 'TI BLE Sensor Tag' || 
            device.name === 'SensorTag') {
            
            // Stop scanning as it's not necessary if you are scanning for one device.
            this.manager.stopDeviceScan();

            // Proceed with connection.
        }
    });
}
```

Right now, if I write some code like this:
```
console.log('test')
scanAndConnect()
console.log('test')
```

I can see that both 'test' are printed before the scanAndConnect function stop running, what's the best way to turn the function async so that I can wait for whatever result is coming from that function and use it in the following line?

**Comment by iftkharhussain** [comment]
You can solve your problem by using Promise and Async await. here is example

scanAndConnect() {
  return new Promise((resolve, reject) => {
    this.manager.startDeviceScan(null, null, (error, device) => {
      if (error) {
        // Handle error (scanning will be stopped automatically)
        reject()
      }

      // Check if it is a device you are looking for based on advertisement data
      // or other criteria.
      if (device.name === 'TI BLE Sensor Tag' ||
        device.name === 'SensorTag') {

        // Stop scanning as it's not necessary if you are scanning for one device.
        this.manager.stopDeviceScan();

        resolve()
        // Proceed with connection.
      }
    });
  })
}


async function test() {
  console.log('1st func')
  await scanAndConnect()
  console.log('3rd func')
}

test();
