### ISSUE TITLE
Not work reading/writing/notifications with real device

### ISSUE THREAD

**Issue by SlavaInstinctools** [Polidea/react-native-ble-plx#577]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [+] I am running the latest version
- [+] I checked the documentation and found no answer
- [+] I checked to make sure that this issue has not already been filed
- [+/-] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active) or on our [Gitter](https://gitter.im/RxBLELibraries/react-native-ble) channel.

## Question

I have hardcoded service and characteristic UUIDs in my app and trying to use them after connection. And when I call any action like 'device.readCharacteristicForService()' or 'device.writeCharacteristicWithResponseForService()' or 'device.monitorCharacteristicForService()' I get the error that this device has not this service:

`Service {code} for device ? not found","errorCode":302, ....`

But I'm sure, that connected device has this service and characteristic (i print logs and get same ids, that I hardcoded).  Moreover, it works fine with my Peripheral emulator on Bleno library. But when I'm trying to use my app with a real device I get this error despite that device.services() and service.characteristics() returned services and characteristics equals my hardcoded strings!

I added follow my code with connection and read characteristic for to show that ~~I'm not stupid~~ I made all right. 

**Connection and store device object:** 
```
  const { id } = await bleManager.connectToDevice(uuid);

  const device = await bleManager.discoverAllServicesAndCharacteristicsForDevice(id);

  const wasConnected = await device.isConnected();

  if (wasConnected) {
    storeDevice(device);
  }

  // todo - temp for test
  const services = await device.services();

  const charPromises = map(service => service.characteristics())(services);

  const characteristics = await Promise.all(
    charPromises.map(p => p.catch(e => console.error(e) || e)),
  );

  // here I see connected devices services and characteristics UUIDs and there are my hardcoded too!
  console.log(characteristics);

```

Usage: 

```
  // device - stored device which was saved by 'storeDevice' above
  // serviceUuid, characteristicUuid - hardcoded UUIDs matched with got above

  // first usage, part of wrapper-function
  const result = await device.writeCharacteristicWithResponseForService(
    serviceUuid,
    characteristicUuid,
    valueBase64,
  );

  // second
  const result = await device.readCharacteristicForService(serviceUuid, characteristicUuid);

  // third
  return device.monitorCharacteristicForService(serviceUuid, characteristicUuid, listener);
```

Eventually, I ask your help and advice, what can be wrong or what I missed. Probably there is a problem with access or library or my code... But it works with bleno, but not a real device. And I have not access to a real device and can just guess what wrong. I hope for your help!

**Comment by dyarfaradj** [comment]
I also get this, when I try to connect to a service it says "Service {code} for device ? not found" , I've double checked and printed the available services.
