### ISSUE TITLE
startDeviceScan get the wrong mac id

### ISSUE THREAD

**Issue by iaminvictus1993** [Polidea/react-native-ble-plx#578]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [1 ] I am running the latest version
- [1 ] I checked the documentation and found no answer
- [1 ] I checked to make sure that this issue has not already been filed
- [1 ] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active) or on our [Gitter](https://gitter.im/RxBLELibraries/react-native-ble) channel.

## Question

the true mac ID should be "FC:58:FA:11:5C:6E",  but it scan ""FD:58:FA:11:5C:6E""

```
    this.state.bleManager.startDeviceScan(
      null,
      { allowDuplicates: false },
      (error, scannedDevice) => {
        console.log("errorerrorerror", error);
        console.log("scannedDevice", scannedDevice);
        if (scannedDevice && scannedDevice.name) {
          console.log(scannedDevice.name, scannedDevice);
          this.setState(state => {
            state.bleList.add(scannedDevice);
            return state;
          });
        }
      }
    );
```

**Comment by dariuszseweryn** [comment]
This is what the underlying platform reports — there is nothing the library can do. If you think otherwise then please open a bug report with all related data like native logs etc.
Best regards
