### ISSUE TITLE
Cannot connect to laptop

### ISSUE THREAD

**Issue by coch110149** [Polidea/react-native-ble-plx#580]
##Question
I am able to search for devices, and I can find my laptop, but when I run a device.connect() I get an error [BleError: Operation timed out]. 
`
import React, {Component} from 'react';
import {Button, View, Text} from 'react-native';
import {BleManager} from 'react-native-ble-plx';

export default class App extends Component {
  constructor() {
    super();
    this.state = {
      device: null,
    };
    this.manager = new BleManager();
  }

  pressAction = () => {
    console.log('searching...');
    this.manager.startDeviceScan(null, null, (error, device) => {
      if (error) {
        console.log(error);
        return;
      }
      console.log(`${device.name} '\n'`);
      if (device.name === 'hippieLaptop') {
        this.manager.stopDeviceScan();

        device.connect()
      }
    });

  render() {
    return (
      <View>
        <Button onPress={this.pressAction} title="Press Me" />
        <Text>{this.state.device && this.state.device.name}</Text>
      </View>
    );
  }
}

`
I am paired through the android settings menu to the laptop. 
I am using nexus 6p on 8.1 and a dell laptop running latest windows 10
react native: .61.5
react-native-ble-plx: 1.1.0

**Comment by Cierpliwy** [comment]
Does your laptop support Bluetooth Low Energy or just normal Bluetooth?
