### ISSUE TITLE
Trying to write 0b00000001 to a device Uint8 characteristic (maxBytes == 1), end up with '49'

### ISSUE THREAD

**Issue by mgcrea** [Polidea/react-native-ble-plx#582]
Wondering where does the bug comes from,

I'm trying to write `0b00000001` to a device Uint8 characteristic (maxBytes == 1), and end up with `'49'` on the other side. Probably something stupid :).

Writing strings do work properly.

I'm using the [moddable](https://www.moddable.com/) framework with [this basic example](https://github.com/Moddable-OpenSource/moddable/tree/public/examples/network/ble/wifi-connection-server), trying to set the `control` characteristic:

Thanks for the great lib!

**Comment by Cierpliwy** [comment]
Can you send me a code snippet how you send a value?
