### ISSUE TITLE
Carthage-Issues running for iOS

### ISSUE THREAD

**Issue by Pinny3** [Polidea/react-native-ble-plx#585]
Hi there,

I am running into the problem that

`react-native run-ios` 

leads to 

`Failed to read file or folder at [...]/node_modules/react-native-ble-plx/ios/BleClientManager/Carthage/Build/iOS/BleClientManager.framework
Command PhaseScriptExecution failed with a nonzero exit code`

I have carthage installed with brew and it's accessible.

I tried the following:

1. rm node-modules -> npm install
2. react-native unlink react-native-ble-plx -> react-native link react-native-ble-plx

Nothing helped.

My dependencies within the package.json looks like this:

```
  "dependencies": {
    "react-native-ble-plx": "^1.1.0",
    "base64-arraybuffer": "^0.1.5",
    "react": "16.8.3",
    "react-native": "0.59.10",
    "react-native-gps-state": "^2.0.3",
    "react-native-modal-overlay": "^1.0.1",
    "react-native-svg": "^9.13.3",
    "react-native-timer": "^1.3.6",
    "styled-components": "^3.3.3"
  }
```

The directory

`[...]/node_modules/react-native-ble-plx/ios/BleClientManager`

never contains any Carthage directory. 

What might be the problem? How can I solve this? BTW: For Android everything is working fine.

**Comment by dariuszseweryn** [comment]
Carthage is not used since `0.10.0`. Check the changelog and new integration instructions
