### ISSUE TITLE
Support autolinking > 0.60

### ISSUE THREAD

**Issue by ScreamZ** [Polidea/react-native-ble-plx#588]
Hi,

Did you saw that and is it planned ?
```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-ble-plx (to unlink run: "react-native unlink react-native-ble-plx")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
```

Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

Regards

**Comment by Cierpliwy** [comment]
There are plans to release version 2.0, which will target RN 0.60+ and use autolinking feature as far as I know. There are no API changes planned for 2.0.

**Comment by thibaultdewit** [comment]
So it is fine to disregard the instructions regarding unlinking this package at the moment?

**Comment by nsantacruz** [comment]
Yes. Manual linking still works currently.

**Comment by RANGELJ** [comment]
So autolinking does not work yet?

**Comment by azuxx** [comment]
any updates about this? Warning still exists so I think I have to keep it manual still.

**Comment by dariuszseweryn** [comment]
There is version 2.0.1. Current linking process is described in readme.

**Comment by azuxx** [comment]
> There is version 2.0.1. Current linking process is described in readme.

@dariuszseweryn Thank you, I have already have  "react-native-ble-plx": "^2.0.1" in my package.json but then I followed the wrong guide here:  
<img width="1077" alt="Screenshot 2020-07-30 at 11 30 16" src="https://user-images.githubusercontent.com/16132913/88906785-251f8880-d258-11ea-90c3-dfd3e10c8b77.png">

there is no mention about autolinking here.

**Comment by dariuszseweryn** [comment]
[Automatic linking is the first two steps](https://reactnative.dev/docs/linking-libraries-ios#automatic-linking). There are additional steps related to BLE feature and the way this library is implemented on each platform and are obligatory.

**Comment by azuxx** [comment]
> [Automatic linking is the first two steps](https://reactnative.dev/docs/linking-libraries-ios#automatic-linking). There are additional steps related to BLE feature and the way this library is implemented on each platform and are obligatory.

@dariuszseweryn  I have updated to RN 0.63.2 and I don't have those stuff in my xCode project. Anyhow my podfile looks like this and your library at the moment is working properly, it was just about that warning I was having when running npx react-native run-ios.

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '10.0'


target 'XXXReactNative' do

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  pod 'react-native-ble-plx', :path => '../node_modules/react-native-ble-plx'

  #target 'XXXReactNativeTests' do
    #inherit! :complete
    # Pods for testing
  #end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

#target 'XXXReactNative-tvOS' do
  # Pods for XXXReactNative-tvOS

  #target 'XXXReactNative-tvOSTests' do
  #  inherit! :search_paths
    # Pods for testing
  #end
#end

```
