### ISSUE TITLE
Latest device manufacturerData

### ISSUE THREAD

**Issue by WilliamAlexander** [Polidea/react-native-ble-plx#591]
## Prerequisites

On latest ver of package

## Question

I have data in the device.manufacturerData that I need to read at certain intervals (often as possible really).
I cannot connect to the devices. 
Is there a way to ask a non-connected device for the manufacturerData or is there a way to increase the rate at which devices are scanned? (I already use LowLatency) 

The scan rate on iOS devices are higher compared to Android. I guess it's a battery saving measure.

**Comment by dariuszseweryn** [comment]
> Is there a way to ask a non-connected device for the manufacturerData

There is no other way than scanning it.
> is there a way to increase the rate at which devices are scanned? (I already use LowLatency)

Low latency is the best you can get. Scan frequency of a given peripheral can be different on different hardware. YMMV

Best regards
