### ISSUE TITLE
Fetching scan response data

### ISSUE THREAD

**Issue by jayhardee9** [Polidea/react-native-ble-plx#602]
## Question

Is it possible to retrieve scan response data with this library? My device sends an extra scan response packet with some data that I would like to read while scanning.

**Comment by Cierpliwy** [comment]
Unfortunately library only passes advertisement data records, which are accessible on the iOS platform. List is here: https://developer.apple.com/documentation/corebluetooth/cbcentralmanagerdelegate/advertisement_data_retrieval_keys?language=objc.
