### ISSUE TITLE
[iOS] JS thread freezes when turning on or off bluetooth

### ISSUE THREAD

**Issue by sweebee** [Polidea/react-native-ble-plx#604]
## Expected Behavior

App should not freeze JS thread

## Current Behavior

JS thread freezes and to interaction is possible

### Steps to Reproduce

1. Open app
2. Go to settings and enable or disable bluetooth
3. Go back to the app 
4. JS thread is now frozen and does not respond

### Context

Library: 1.1.0
Expokit: 36.0.1
Platform: iOS

**Comment by VasuZangula** [comment]
same

**Comment by Cierpliwy** [comment]
Can you give me a trace from remote debugging? I would like to know what code was executed before a freeze happened.
