### ISSUE TITLE
manufacturerData of first returned peripheral record is null

### ISSUE THREAD

**Issue by rk85097** [Polidea/react-native-ble-plx#605]
## Prerequisites
- [ YES] I am running the latest version
- [YES ] I checked the documentation and found no answer
- [YES ] I checked to make sure that this issue has not already been filed - I have found another similar issue but it is not my case: https://github.com/Polidea/react-native-ble-plx/issues/346

## Expected Behavior
manufacturerData should not be null, regardless. When scanning for peripherals, then reading their manufacturerData, I expect it not to be null.

## Current Behavior
When allowDuplicates scanOption is true, startDeviceScan will return multiple peripherals records of the same pheripheral and sometimes the first record will have manufacturerData null, which means ble-plx returns a peripheral on scanOption before getting initial scan response from peripheral causing manufacturerData to be empty.

### Steps to Reproduce
1. Scan for peripherals (startDeviceScan with allowDuplicates true)
2. While scanning, read manufacturerData of first peripheral record

**Comment by rk85097** [comment]
**UPDATE**: I have found that when `allowDuplicates` `scanOption` is `true`, `startDeviceScan` will return multiple peripherals records of the same pheripheral and sometimes the first record will have `manufacturerData` null, which means ble-plx returns a peripheral on `scanOption` before getting initial scan response from peripheral causing `manufacturerData` to be empty. This is a bug IMO.

**Comment by rk85097** [comment]
**TEMP-SOLUTION** - Always take last peripheral record coming from startDeviceScan to insure manufacturer data is not empty.

**Comment by Cierpliwy** [comment]
This can happen. Very often advertisement data is split into two packages and OS may report both of them after another without merging them. I'm talking about `ADV_IND` and `SCAN_RSP`. What you can do on firmware side is to make sure that manufacturer data is moved to the first packet `ADV_IND` and move less important advertisement data to the second one.

Another option is to wait for last record as you mentioned. It should have merged properties.
