### ISSUE TITLE
Found issue in Discovering the characteristics - Version 1.1.0 and above

### ISSUE THREAD

**Issue by ApurvMahesh** [Polidea/react-native-ble-plx#607]
Using BLE-PLX Library for Scanning and Connecting to BLE devices

Did check your reference implementation as provided at - https://www.polidea.com/blog/ReactNative_and_Bluetooth_to_An_Other_level/

used the below code block to discover all services - 

```
 device
          .connect()
          .then(device => {
            this.info('Discovering services and characteristics');
            return device.discoverAllServicesAndCharacteristics();
          })
          .then(device => {
            this.info('Setting notifications');
            return this.setupNotifications(device);
          })

```

The issue i found, is the device has no service UUIDs list even when the libraries like 

> react-native-ble-manager as successfully scanning and discovering services and characteristics

Attaching the screenshot of device properties - after scanning and discovering services - 
![image](https://user-images.githubusercontent.com/29753654/73473306-8acaaf00-43b2-11ea-9b3d-6311e8fec44b.png)

Kindly resolve the above issue as i am using your library in one of my project as initially i found it more better and easy to use. Kindly fix the bug as soon as possible, will be helpful.

**Comment by dariuszseweryn** [comment]
I believe you have not read [wiki regarding service discovery](https://github.com/Polidea/react-native-ble-plx/wiki/Device-Service-Discovery)

**Comment by ApurvMahesh** [comment]
> I believe you have not read [wiki regarding service discovery](https://github.com/Polidea/react-native-ble-plx/wiki/Device-Service-Discovery)

May be i am not getting what you want to convey, but i am using the same method as it is described - device.discoverAllServicesAndCharacteristics(): Promise<Device>

Kindly let me know, your views on this.

**Comment by dariuszseweryn** [comment]
This part:

> When the service discovery was already performed after the connection has been established it is possible to retrieve the cached services by calling:
> ```
> device.services(): Promise<Service[]>
> ```
> or
> ```
> bleManager.servicesForDevice(deviceIdentifier: DeviceId): Promise<Array<Service>>
> ```

**Comment by ApurvMahesh** [comment]
> This part:
> 
> > When the service discovery was already performed after the connection has been established it is possible to retrieve the cached services by calling:
> > ```
> > device.services(): Promise<Service[]>
> > ```
> > 
> > 
> > or
> > ```
> > bleManager.servicesForDevice(deviceIdentifier: DeviceId): Promise<Array<Service>>
> > ```

Hi @dariuszseweryn I checked the api doc and what you say is correct, but still i am having issue in discovering any services or characcteristics for the BLE device. 

Below am posting the screen shot of the response which i got from 

> device.services()

Kindly refer to the screen shot for more information.
![image](https://user-images.githubusercontent.com/29753654/73481801-8f975f00-43c2-11ea-9616-131440584371.png)

**Comment by eliasws** [comment]
I have the same Problem. Even on scanning more information is shown:

Scanning:

![image](https://user-images.githubusercontent.com/19492473/73484901-6d8de480-43a2-11ea-8c3e-6e65e1d59e2f.png)

After discovering (same for after connecting): 

![image](https://user-images.githubusercontent.com/19492473/73484986-9910cf00-43a2-11ea-935b-0f1b25941870.png)

**Comment by dariuszseweryn** [comment]
@ApurvMahesh You may be facing an Android OS bug but I cannot really tell without native logs as per bug report template
@eliasws these are correct as most of the data is available only during a scan

**Comment by ApurvMahesh** [comment]
> @ApurvMahesh You may be facing an Android OS bug but I cannot really tell without native logs as per bug report template
> @eliasws these are correct as most of the data is available only during a scan

@dariuszseweryn I am facing the same issue as eliasws posted and it's not an Android specific issue as the screenshots i posted are related to iOS device.

**Comment by Ajaykumar02** [comment]
@dariuszseweryn, I am also facing the same issue.
when tested on NRF connect application i am able list down the characteristics and services but the same thing will return null response for service[]. same on both Android as well in IOS.

pls can you look into this issue

**Comment by Cierpliwy** [comment]
Ok. Let me clarify. Device has multiple properties:
```
▸ id
▸ name
▸ rssi
▸ mtu
▸ manufacturerData
▸ serviceData
▸ serviceUUIDs
▸ localName
▸ txPowerLevel
▸ solicitedServiceUUIDs
▸ isConnectable
▸ overflowServiceUUIDs
```
We can group them into explicit categories:
Read-only (stable) values:
```
▸ id
```
Properties, which can be modified, when the new Device object is fetched from the API (Device by itself is immutable and "snapshot" of it at the moment of the call):
```
▸ name
▸ mtu
```
Properties, which are fetched during the scanning procedure from the advertisement data (they are always null outside device scanning):
```
▸ rssi
▸ manufacturerData
▸ serviceData
▸ serviceUUIDs
▸ localName
▸ txPowerLevel
▸ solicitedServiceUUIDs
▸ isConnectable
▸ overflowServiceUUIDs
```
Therefore if you want to get services of the device (not services advertised during scanning procedure) you have to call sequentially `device.iscoverAllServicesAndCharacteristics()` and then `device.services()`. The result of the last call should return `Array<Service>`. I guess that's what you expect.

Why all of the properties are in one bag? That's just a mistake during early development, which we left as it is to keep backward compatibility (it's so important for me in this crazy JS world).

**Comment by ApurvMahesh** [comment]
@Cierpliwy Thanks a lot for your response. I tried the same as you suggested. It is working and i am able to get the list of services and characteristics. Thanks a lot. Hereby closing the issue, as it was invalid. @dariuszseweryn thanks a lot for your help bro.

**Comment by Ajaykumar02** [comment]
@Cierpliwy, cool i have not used the device.services(). Thank you for clarification.
