### ISSUE TITLE
disconnecting without known identifier

### ISSUE THREAD

**Issue by fgrs** [Polidea/react-native-ble-plx#612]
Is it possible to disconnect from the device without an ID using cancelDeviceConnection? I just found out that while connected if I then wipe out all the app data on Android device and reopen the app the connection to the bluetooth device stays open and the only way to disconnect is to restart bluetooth device.

**Comment by Cierpliwy** [comment]
You can use [`manager.connectedDevices`](https://polidea.github.io/react-native-ble-plx/#blemanagerconnecteddevices) function call to get list of connected devices. Additionally when you define `restoreStateIdentifier` and `restoreStateFunction` inside [`BleManagerOptions`](https://polidea.github.io/react-native-ble-plx/#blemanageroptions), you can get list of connectied devices, when application launches.
