### ISSUE TITLE
How to get updated rssi?

### ISSUE THREAD

**Issue by SimoneCarnio** [Polidea/react-native-ble-plx#621]
I'm populating an array with scanned device and if already present, I  update the rssi value, but some devices is scanned every second, other after a lot of seconds.
How to get "near to realtime" rssi values for all scanned devices (not connected)?

To understand, I would like to replicate a list like the main page of LightBlue where rssi is updated every in realtime for every row

![IMG_2DE6730042EB-1](https://user-images.githubusercontent.com/8537252/75368119-8b773800-58c1-11ea-84eb-f9a75b67891e.jpeg)

**Comment by diegogurpegui** [comment]
You will need to ping that value every X seconds (or any time frame that makes sense for you).
You can create your own subscription-like functions.

**Comment by SimoneCarnio** [comment]
thank, will try tomorrow

**Comment by Cierpliwy** [comment]
Closing for now. Please reopen if there are any issues.
