### ISSUE TITLE
My device can be discovered too?

### ISSUE THREAD

**Issue by tal987** [Polidea/react-native-ble-plx#626]
hey I just wondering if its possible that while im scanning my device can be discovered by other scanner?
I mean other device can see my device around (android and iPhone)
in different words im trying to advertise while im scanning, is that possible?

Thank you

**Comment by Cierpliwy** [comment]
Advertising is different feature using different APIs under the hood: `CBPeripheralManager` (iOS) and `BluetoothLeAdvertiser` (Android). This library don't support them.
