### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ParshantArora** [Polidea/react-native-ble-plx#637]
Hi my need is to get static Bluetooth id during scanning. So that  i can differentiate a particular persons iphone/ipad  based on that id . But as you know apple provide us UUID which is not constant or static  which changes during every session.

On android we are getting static MAC address
In short i need a constant id that is throughout the app or phone in iOS

**Comment by Harneetk** [comment]
Hi
I also have same requirement in my application. Is there any method in library which gives advertising packet from where unique ID can be fetched? Sample code will be highly appreciated here. Thanks

**Comment by Cierpliwy** [comment]
It's not possible on iOS. What you can do is to insert your own unique value inside `Manufacturer Data` record, put unique service UUID or service data (on peripheral side).

**Comment by ParshantArora** [comment]
Yes Solved the problem by setting service UUID data in advertising data
