### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ParshantArora** [Polidea/react-native-ble-plx#638]
Hi 
I just want to calculate the distance between the targeted BLE devices and the source scanning device .  
Some people gave solution over internet  to use rssi and txvalue for calculating the same 
But i am not getting Tx power value in case of every device. 

Can Any one help me out on this ? Need a solution on thew immediate basis

**Comment by Cierpliwy** [comment]
> But i am not getting Tx power value in case of every device.

You can't do anything about it. It's not required to put TX power value in an advertisement data.

**Comment by ParshantArora** [comment]
Yes @Cierpliwy Do you another way to calculate the distance between  targeted BLE devices and the source scanning device?
 .
