### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ParshantArora** [Polidea/react-native-ble-plx#639]
Hi 
I need to check whether the scanned Bluetooth device is Car Bluetooth , iphone or or watch or band 
Basically my need is to check the deviceType of the scanned Bluetooth device.

It would be appreciated if anyone provides a solution on this

**Comment by Cierpliwy** [comment]
This library handles only Bluetooth Low Energy devices. I think you are looking for normal Bluetooth Classic functionality.

**Comment by ParshantArora** [comment]
Yes my requirement is with the both BLE as well as with classic . Just want to identify whether its car bluetooth , watch or iphone
