### ISSUE TITLE
Runtime Error: SIGABRT on fileprivate var connectedDevices = Dictionary<UUID, Peripheral>()

### ISSUE THREAD

**Issue by watadarkstar** [Polidea/react-native-ble-plx#64]
I get this runtime error `Runtime Error: SIGABRT` on `fileprivate var connectedDevices = Dictionary<UUID, Peripheral>()` in `BleClientManager`:

![screen shot 2017-05-03 at 3 19 12 pm](https://cloud.githubusercontent.com/assets/3059371/25677466/10d434dc-3014-11e7-9ab5-3fd77f358ea6.png)

My code is:

```
class BluetoothList extends Component {
    componentWillMount() {
        this.manager = new BleManager(); // <------ HERE
        this.manager.onStateChange((newState) => {
          console.log("State changed: " + newState)
        })
        console.log('will mount test');
    }

    componentWillUnmount() {
        this.manager.destroy();
        delete this.manager;
    }

    render() {
       ...
    }
}
```

I am running on my device using [Expo](https://expo.io/) as a detached app. My dependencies are:

```
"dependencies": {
    "expo": "16.0.0",
    "react": "16.0.0-alpha.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-16.0.0.tar.gz",
    "react-native-ble-plx": "^0.4.0",
    "react-native-elements": "^0.11.2"
  },
```

**Comment by seanadkinson** [comment]
FYI, I was having the same issues, and fixed it by rebuilding all carthage artifacts.  I think this issue occurs if you have upgraded xcode, and still had artifacts built from a previous version.

**Comment by watadarkstar** [comment]
@seanadkinson I actually did upgrade xcode recently while dealing with these issues. What do you mean by rebuilding all carthage artifacts? How do I do that exactly?

**Comment by seanadkinson** [comment]
For me:

    $ cd ios
    $ rm -Rf Carthage
    $ carthage bootstrap --platform iOS

**Comment by Cierpliwy** [comment]
Alternatively from root of your project you can execute below commands

```bash
cd node_modules/react-native-ble-plx/
./build_ios_frameworks.sh
```

to force rebuild of native libraries. Let me know if it helped.

**Comment by watadarkstar** [comment]
@Cierpliwy Yup that worked! Thank you.
