### ISSUE TITLE
Issue finding header

### ISSUE THREAD

**Issue by CaptainJeff** [Polidea/react-native-ble-plx#641]
This issue is a little weird. I was trying to build some custom logic and was inheriting an Objective-C protocol but when I inherit the protocol my build fails immediatley with. Does anyone know what would cause this or a possible solution?  Maybe creating a new header or changing a build setting?

<img width="703" alt="Screen Shot 2020-04-05 at 6 39 56 PM" src="https://user-images.githubusercontent.com/2991673/78512890-0ad81100-7776-11ea-9130-b3ae72ec086b.png">

~~
<img width="701" alt="Screen Shot 2020-04-05 at 6 40 05 PM" src="https://user-images.githubusercontent.com/2991673/78512891-0ad81100-7776-11ea-930c-e3442f66dc57.png">

~~

<img width="424" alt="Screen Shot 2020-04-05 at 7 42 51 PM" src="https://user-images.githubusercontent.com/2991673/78512892-0ad81100-7776-11ea-9297-d82fadc05c82.png">

**Comment by Cierpliwy** [comment]
Recently released version 2.0.0 made changes to the building process and you don't need to have `react-native-ble-plx-swift` dependency anymore.
