### ISSUE TITLE
[IOS]-I can't can't run my device

### ISSUE THREAD

**Issue by serdargun** [Polidea/react-native-ble-plx#650]
I can connect to my device. I can even write characteristic to my device without an error. In android, everything is working correctly, my device is running but in iOS, something is wrong. I can't run my device although I wrote same characteristic that is in android.  The crazy part is there is no error I see. Do you have any idea about this?

**Comment by dariuszseweryn** [comment]
My crystal ball says — no. For future — please be as specific about your problem as possible
