### ISSUE TITLE
Id of an already connected peripheral device

### ISSUE THREAD

**Issue by shubhnik** [Polidea/react-native-ble-plx#66]
Is it possible to get the Id of a bluetooth peripheral device connected from bluetooth settings in the phone?

**Comment by Kacper20** [comment]
Hello @shubhnik 
Unfortunately - no. You could do it for example by using this app: https://itunes.apple.com/us/app/sniffator/id1147266354?ls=1&mt=8
It's example project for the library and is built using it.

Hope it answers your question,

Kacper
