### ISSUE TITLE
Detecting connection status doesn't seem to work

### ISSUE THREAD

**Issue by kowalski** [Polidea/react-native-ble-plx#670]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior

* When running `bleManager.isDeviceConnected(deviceId)` I should be getting true/false. 
* When subscribed using `bleManager.onDeviceDisconnected(device.id, callback)` the callback should be called when device is disconnected.

## Current Behavior

* isDeviceConnected() is returning me the follwing response regardless if the device is connected or not `{"_40": 0, "_55": null, "_65": 0, "_72": null}`

* `callback` is never called when device disconnects

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Both JS and platform logs can be enabled via [setLogLevel](https://polidea.github.io/react-native-ble-plx/#blemanagersetloglevel) function call. 

* Library version: 2.0.0
* Platform: Android.
* Platform logs (logcat):
* JS logs:
* Contents of the `package.json` file:

```
  "dependencies": {
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-ble-plx": "^2.0.0",
    "react-native-push-notification": "^3.4.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^1.0.0",
    "@types/jest": "^24.0.24",
    "@types/react-native": "^0.62.0",
    "@types/react-native-push-notification": "^3.0.9",
    "@types/react-test-renderer": "16.9.2",
    "@typescript-eslint/eslint-plugin": "^2.27.0",
    "@typescript-eslint/parser": "^2.27.0",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "prettier": "^2.0.4",
    "react-test-renderer": "16.11.0",
    "typescript": "^3.8.3"
  },
```
* Android version: 10
* Phone: SM-G986B/DS (Galaxy S20+ 5G)

**Comment by dariuszseweryn** [comment]
Hello. It seems that on `I checked the documentation and found no answer` you have missed the truth as you would see that
```
bleManager.isDeviceConnected() with partially filled arguments.
isConnected(): Promise<boolean>
Returns
Promise<boolean>: Promise which emits true if device is connected, and false otherwise. 
```
Does return a Promise. And this is what you have printed.
As for `bleManager.onDeviceDisconnected(device.id, callback)` I cannot verify because you did not filled the logs in the report as the issue template asks you to do. Please add the missing info and maybe there is something I could do.
Best regards
