### ISSUE TITLE
Help me with writeCharacteristic

### ISSUE THREAD

**Issue by fabio-C** [Polidea/react-native-ble-plx#671]
I am a BLE noob, and using this library it is extremely difficoult for me.

I need to send a simple string from my app to a HC-08 module.
I was able to list all devices and connect with my module, but I stuck with writing data.

I suppose I should use this function:
**_writeCharacteristicWithoutResponseForService(serviceUUID, characteristicUUID, valueBase64, transactionId)_**

My questions are:
1) What is a Service UUID and how I can get one from my module.
2) What is a Characteristic UUID and how I can get one from my module.
3) Does exist a repo with an app example built with this library? I didn't found anything.
4) Does exist a tutorial?

**Comment by Cierpliwy** [comment]
There are a lot of examples present on Github. One semi-official one is `SensorTag` and you can find a minimal description of how to use the library [here](https://polidea.github.io/react-native-ble-plx/).

Answering questions:
1. Service UUID is an entity that can be discovered once you are connected to the device. Most of the devices have a static set of services with already known UUID, which can be used.
2. The same as above, but Characteristic UUID is a part of the service.
3. Answered above.
4. Answered above.

I would suggest finding a platform-agnostic tutorial about Bluetooth Low Energy to get a grasp of the basics as well.
