### ISSUE TITLE
[iOS] Cannot read characteristics after update to 2.0.0

### ISSUE THREAD

**Issue by sabba88** [Polidea/react-native-ble-plx#674]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior

Read data from device in readeable characteristics.

## Current Behavior

What is the current behavior?
I have error: Operation was rejected

### Steps to Reproduce

The system works properly with the 1.1.0 version. After the update to 2.0.0 this error appear.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Both JS and platform logs can be enabled via [setLogLevel](https://polidea.github.io/react-native-ble-plx/#blemanagersetloglevel) function call. 

* Library version: 2.0.0
* Platform: both Android/iOS.
* JS logs:
This is the scenario.
I have a peripheral with 3 services.
![image](https://user-images.githubusercontent.com/43341781/82613580-eae59b00-9bc5-11ea-80d5-0201763c3c1c.png)
To read and write I use the third service. The service has 2 characteristics, the first one is used to write the second is used to read.
![image](https://user-images.githubusercontent.com/43341781/82613668-254f3800-9bc6-11ea-89c1-0ed20b982ec2.png)

After the connection to the device I write in the Write service, and everithing is fine. But when I read from the other characteristics the error "Operation was rejected" appear:
![image](https://user-images.githubusercontent.com/43341781/82613785-8119c100-9bc6-11ea-827f-6212f4091cbc.png)

* Platform logs (logcat/XCode): Flipper
This is the log that I see in Verbose mode with Flipper. The problem seems that the characteristic is not recognized as readable.
![image](https://user-images.githubusercontent.com/43341781/82613857-b0303280-9bc6-11ea-9641-49c195705cc1.png)

* Contents of the `package.json` file:
```json 
"dependencies": { 
    "@react-native-community/async-storage": "^1.6.1",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.3.3",
    "@react-navigation/native": "^5.2.3",
    "@react-navigation/stack": "^5.2.18",
    "prop-types": "^15.7.2",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-animatable": "^1.3.3",
    "react-native-base64": "^0.0.2",
    "react-native-ble-plx": "^2.0.0",
    "react-native-connectivity-status": "^1.5.1",
    "react-native-dialog-input": "^1.0.7",
    "react-native-fs": "^2.16.6",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-localization": "^2.1.6",
    "react-native-orientation": "^3.1.3",
    "react-native-reanimated": "^1.8.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.7.0",
    "react-native-share": "^3.3.0",
    "react-native-svg": "^9.11.1",
    "react-native-svg-charts": "^5.3.0",
    "react-native-swipe-list-view": "^2.0.0",
    "react-native-swiper": "^1.5.14",
    "shortid": "^2.2.14"
  },
```
* Formatted code sample or link to a repository:

```js
        console.log('READ - characteristic', this.characteristicR);
        const read = await this.characteristicR.read();
        const receivedAddress = read.value.charAt(2) + read.value.charAt(3);
        console.log('Address Read Sent', sentAddress);
        console.log('Address Read Received', receivedAddress, read.value);
```

In version 1.1.0 everything works fine.

Do you have any suggestion?
Thanks in advance,
Samuele

**Comment by sabba88** [comment]
Someone can help me?

**Comment by dariuszseweryn** [comment]
It would be easier to help you if you would conform to the issue template and not delete most of the sections. They are there for a reason. Could you go back and provide requested logs?

**Comment by sabba88** [comment]
Hi @dariuszseweryn,
I edit the original post. I hope it could be ok now.
Thanks in advance,
samuele

**Comment by dariuszseweryn** [comment]
Native logs are needed. You have also [this wiki page](https://github.com/Polidea/react-native-ble-plx/wiki/=-FAQ:-I-got-a-BleError.-Now-what%3F). Please attach native logs and print the full error object

**Comment by sabba88** [comment]
Hi @dariuszseweryn,
thanks for your reply. I update the first with more detailed information, using Verbose loglevel. I hope there will be enough.

Thanks in advance,
Samuele

**Comment by dariuszseweryn** [comment]
Could you print object `this.characteristicR`?

**Comment by sabba88** [comment]
It'already printed in the last screen ho js log. Just over the error. READ - Characteristic.

**Comment by sabba88** [comment]
Hi,
when will be released this fix?
Thank you for your work,

Samuele

**Comment by dariuszseweryn** [comment]
I hope for the end of this week

**Comment by sabba88** [comment]
Hi,
any news about this fix?
Thanks in advance,

Samuele

**Comment by dariuszseweryn** [comment]
You could try using `react-native-ble-plx: git://github.com/Polidea/react-native-ble-plx.git#387e4f080f953b0476faa9c06cdd448aa7a1a1b4` and tell me if it works for you.

I think that next week we will have a npm released version

**Comment by sabba88** [comment]
Hi @dariuszseweryn,
it works with that fix. However, I see that the fix is only for Android, but the problem is also into Ios version.
Thanks,
Samuele

**Comment by Cierpliwy** [comment]
Is it an issue on iOS? As you have two characteristics with the same UUID, make sure to call functions directly from `Characteristic` object (e.g. `characteristic.read()`). Otherwise, first matching characteristic will be selected for an action (writable in your case).

**Comment by sabba88** [comment]
Hi @Cierpliwy ,
the issue is in both platform. With the previous fix of Darius the android environment works fine. WIth iOS still get the error.
This is where I setup the characteristics.
`
    const characteristics = await service.characteristics();
    this.characteristicW = characteristics[0];
    this.characteristicR = characteristics[1];
`

And this is how read the characteristic

`
        console.log('READ - characteristic', this.characteristicR);
        const read = await this.characteristicR.read();
        const receivedAddress = read.value.charAt(2) + read.value.charAt(3);
        console.log('Address Read Sent', sentAddress);
        console.log('Address Read Received', receivedAddress, read.value);
`

In the first post you can check all details.

Thanks,
Samuele

**Comment by dariuszseweryn** [comment]
Could you print both characteristics? i.e. 
```
console.log(JSON.stringify(characteristicR));
console.log(JSON.stringify(characteristicW));
```

**Comment by nriccar** [comment]
Any news on iOS?

**Comment by sabba88** [comment]
Hi,
sorry for the delay.
I "restart" the app from 0 re-insalling every package with the last version and everything works fine.

Thanks,
Samuele

**Comment by nriccar** [comment]
With react native 0.63.0?

Thanks for the info Samuele

**Comment by sabba88** [comment]
No with 0.62.2

These are all my dependencies.

`
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/checkbox": "^0.4.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/picker": "^1.6.3",
    "@react-navigation/bottom-tabs": "^5.5.2",
    "@react-navigation/native": "^5.5.1",
    "@react-navigation/stack": "^5.5.1",
    "prop-types": "^15.7.2",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-animatable": "^1.3.3",
    "react-native-base64": "^0.0.2",
    "react-native-ble-plx": "^2.0.0",
    "react-native-connectivity-status": "^1.5.1",
    "react-native-dialog-input": "^1.0.7",
    "react-native-fs": "^2.16.6",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-localization": "^2.1.6",
    "react-native-orientation": "^3.1.3",
    "react-native-reanimated": "^1.9.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.8.0",
    "react-native-share": "^3.3.3",
    "react-native-svg": "^9.11.1",
    "react-native-svg-charts": "^5.3.0",
    "react-native-swipe-list-view": "^2.0.0",
    "react-native-swiper": "^1.5.14",
    "shortid": `"^2.2.14"``

**Comment by nriccar** [comment]
For me is not working, I have an iPhone Xs and iOS 13.6. 

Same same, new project, with your same versions packages. 

Any guess?
