### ISSUE TITLE
Does not scan smartphones.

### ISSUE THREAD

**Issue by ShubhamBalgujar** [Polidea/react-native-ble-plx#681]
- Plugin version:2.0.0

- Platform: iOS or Android

- React Native version: 0.60.6

Context
The library does not scan smartphones. Sometimes it logs the devices which is not even shown in available devices of bluetooth. I have installed the app on both smartphones(android) but no output.

 componentDidMount() {
const subscription = this.manager.onStateChange((state) => {
            if (state === 'PoweredOn') {
                console.log( state)
                    this.scanDevice();
                    subscription.remove();
            }
        }, true);
}

    scanDevice() {
            this.manager.startDeviceScan(null, null, (error, device) => {
                console.log(device)         
                let deviceId = device.id
                console.log('ble device ID', deviceId, 'ble device name ', device.name, ' local name', 
 device.localName)
                if (error) {
                    console.log('ble error', error)
                }
            })
        }

**Comment by dariuszseweryn** [comment]
You want to google about BLE roles: central and peripheral. What advertising and scanning is. This library will only scan what is advertising (with some limitations regarding beacons on iOS).
