### ISSUE TITLE
Pair devices

### ISSUE THREAD

**Issue by Deboracgs** [Polidea/react-native-ble-plx#684]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [x ] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active) or on our [Gitter](https://gitter.im/RxBLELibraries/react-native-ble) channel.

## Question

I'm trying a few weeks connect mi band 3 and 4, but every I try read heart rate I receive this message below, my question is with this library is possible to do pair connection? Because I used another package and I got a pair and get a heart rate, but I wanna use that library.

![image](https://user-images.githubusercontent.com/12396210/83067380-7ba4f680-a05e-11ea-948b-a4d6b8ce21c2.png)

**Comment by dariuszseweryn** [comment]
OS should perform pairing/bonding on its own if your peripheral is correctly setup (you can google how Android does it). Libraries have nothing to do here.
