### ISSUE TITLE
How to speed up handling of data?

### ISSUE THREAD

**Issue by Charanor** [Polidea/react-native-ble-plx#685]
Hello! I have a simple question regarding download speed / handling of data.

First, terminology: I use _processing speed_ to refer to the effective speed of _downloading_ + _saving data to memory_.

When downloading a file from a BLE device I observe a processing speed of about 7Kbyte/s. The packet size is 240 and the phone I'm using is Bluetooth 4.2. So my first question: **Is 7Kbyte/s in the range of "normal" download speed for Bluetooth 4.2 with 240 packet size on React Native?**

I'm guessing the answer to the above question is **no**. Because of this I assume the low processing speed is because of how I'm handling the data after it being received by the app. So here is my second question: **How can I speed up the handling of the data after it has been recieved?**

Currently I'm handling the data like below (pseudocode-ish). I'm download from up to 4 devices, but it doesn't seem to matter if I download from one device at a time or all at once.

```typescript
this.device.monitorCharacteristicForService(SERVICE, DATA_CHARACTERISTIC, (error, characteristic) => {
    const packet = Buffer.from(characteristic.value, "base64");
    this.packetList.push(packet);
    if ( time since last package >= 1 second ) {
        // Updates a progress bar. Components subscribe to this. 
        // This is the only time a state update happens.
        this.listeners.forEach(listener => listener(amount of data received since last time);
    }
});
```
Summary
- **Packet size**: 240 bytes
- **Bluetooth version (Android phone)**: 4.2
- **ConnectionPriority**: High (sets interval to 9/12).
- **Effective processing speed**: 7Kbyte/s.

Thank you all for your help, I'm really scratching my brain over this.

**Comment by dariuszseweryn** [comment]
There are several things that influence the throughput: Connection Interval, MTU but also PDU, what are capabilities of both server and client (what is the maximum connection window, how many packets can be accepted, if payload data extension is used). Your result may be inside of what is considered normal.
