### ISSUE TITLE
Having problems with getting services for connected device

### ISSUE THREAD

**Issue by paulsoh** [Polidea/react-native-ble-plx#69]
```js
class App extends React.Component {
  ...
  componentDidUpdate = (prevProps, prevState) => {
    if (prevState.connectedDevice !== this.state.connectedDevice) {
      this.tryConnectToDevice(this.state.connectedDevice);
    }
  }

  tryConnectToDevice =(device) => {
    if (device.connect) { // check if it is actual bluetooth device
      device.connect()
        .then((device) => {
            return device.discoverAllServicesAndCharacteristics()
        })
        .then((device) => {
          this.setState({
            services: device.serviceUUIDs,
          })
          return Promise.resolve();
        })
        .catch((error) => {
          this.setState({
            error: error,
          })
        });
    }
  }
  ...
}
```

I am trying to get all the serviceUUIDs for a `connectedDevice` so I wrote it as above. It's pretty straight forward but when I run it it somehow shows the following error.

```
console.error. "Unhandled promise rejection", {"line":1494, "column": 30, "sourceURL":"file:///var/containers/Bundle/Application/.../Blefirst.app/main.jsbundle"}
```

Can anyone take a look at my code and figure out what may have went wrong?

Thanks in advance!

p.s. Thanks for the great open source!

**Comment by Cierpliwy** [comment]
Device's `serviceUUIDs` field is part of advertisement data which may not be available. Basically it may be used by BLE devices to broadcast which services are available before connecting to it.

You should use `services` function to retrieve real services after connection and discovery step:
https://polidea.github.io/react-native-ble-plx/class/react-native-ble-plx/src/Device.js~Device.html#instance-method-services

**Comment by paulsoh** [comment]
Thanks!
