### ISSUE TITLE
reading temperature reading from a BLE device when isReadable is false

### ISSUE THREAD

**Issue by sofian-sunny** [Polidea/react-native-ble-plx#690]
I'm trying to get temperature reading from a BLE device.
I read the document produced by the BLE device vendor.

    Characteristics UDID：2A1C
    Properties: Indicate
    Characteristics Name:Temperature Measurement
    Data Format: 0xFE000D97 (34.79 Celsius)
i can't read data first time as isReadable is false and i monitored Characteristic but not received any call 

Can anyone tell me how to get the data or provide some sample code?
 have to keep track of the data. i.e. I need to update the temperature measurement by monitor(). However, now I can't even get the first reading....

**Comment by dariuszseweryn** [comment]
If the monitoring has started then you need to check documentation of your peripheral or ask the manufacturer what else is needed.
