### ISSUE TITLE
onDisconnected even is not firing immediately once connection lost(If switch off the ble device)

### ISSUE THREAD

**Issue by priyanka-Sadh** [Polidea/react-native-ble-plx#692]
I am using as version below.
react-native": "0.62.2",
"react-native-ble-plx": "^1.1.1"

I want know and fix ->there should not be a delay in calling `onDisconnected` method.
Scenario : In mobile app scanning, gets connected with device, Once I switch off ble device, onDisconnected method take 4-5 seconds to call. I want it should be immediately disconnect. Is it possible ?

**Comment by dariuszseweryn** [comment]
Yes and no. Yes if the peripheral you turn off will send "connection end" signal before switching off. No if it won't — then a Bluetooth Supervision Timeout needs to kick in which is platform dependant and there is no direct control over it from the app side.

**Comment by priyanka-Sadh** [comment]
Thanks for comment
