### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sniperyan** [Polidea/react-native-ble-plx#694]
I have got a string from blood pressure characteristics notify message as below:
HpwA/wf/B+MHCAkNGDX/BwAQAA==
what exactly is it?

Thanks
Frank

**Comment by dariuszseweryn** [comment]
[FAQ](https://github.com/Polidea/react-native-ble-plx/wiki/=--FAQ:-Passing-And-Retrieving-Of-Characteristic-Value)
