### ISSUE TITLE
[Bug Report] It cannot get ble indicate info rightly

### ISSUE THREAD

**Issue by shangzuoyan** [Polidea/react-native-ble-plx#696]
## Expected Behavior

I supposed that it would get the ble indicate info
for example:
"00002a35-0000-1000-8000-00805f9b34fb": [Object],
Blood Pressure Measurement
org.bluetooth.characteristic.blood_pressure_measurement

## Current Behavior

It missed the ble indicate everytime.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Connect to a a blood pressure ble device.
2. Perform a check
3. No ble indicate result

Thanks
Roy

**Comment by dariuszseweryn** [comment]
Hello,

Thank you for using the library.
Your post seems to be a bug report but it lacks some crucial information. Could you edit to contain information according to the [issue template](https://github.com/Polidea/react-native-ble-plx/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)?

Best Regards

**Comment by dariuszseweryn** [comment]
Closing due to lack of information and inactivity of the original poster.

When more data will be available—feel free to add that information and reopen this issue.

Best Regards

**Comment by shangzuoyan** [comment]
Thanks a lot.
This issue was fixed. I register a callback for that notification characteristic.

**Comment by dariuszseweryn** [comment]
Glad to hear that. 👍  More often than not these kind "bug reports" are questions on how to properly use BLE. Cheers!
