### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by 3abitlok** [Polidea/react-native-ble-plx#702]
Help please, when I use "expo eject" I get this error :
![go](https://user-images.githubusercontent.com/49039315/85938515-0307b300-b906-11ea-8a08-f5107261b216.PNG)

then I use "expo start" i get this error on my phone:
![Screenshot_2020-06-28-06-21-51](https://user-images.githubusercontent.com/49039315/85938762-f8e6b400-b907-11ea-885b-b7017403d993.png)

**Comment by dariuszseweryn** [comment]
Hello @3abitlok 
It seems that you have an issue with ejecting `expo` — you should ask for help there as we are no experts in this topic. Perhaps you should read [a guide on how to eject](https://docs.expo.io/expokit/eject/)?
Best regards
