### ISSUE TITLE
How set default service uuid for multiple mobile devices running same app, so that it will scan only those devices only? 

### ISSUE THREAD

**Issue by rohantanwar94** [Polidea/react-native-ble-plx#710]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [x] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active) or on our [Gitter](https://gitter.im/RxBLELibraries/react-native-ble) channel.

## Question

Please describe the question.

**Comment by dariuszseweryn** [comment]
> How set default service uuid for multiple mobile devices running same app, so that it will scan only those devices only?

To scan only devices that advertise a particular UUID one needs to add it as a parameter. `bleManager.startDeviceScan([uuid], ...)`
