### ISSUE TITLE
[Android] can send files to connected devices?

### ISSUE THREAD

**Issue by y132459960** [Polidea/react-native-ble-plx#711]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I have an app_x
- [x] app_x was connrcted a deive

Expected Behavior
I hope that app_x can send a file to device, can do this?

**Comment by dariuszseweryn** [comment]
Sending a file is sending data. This library allows for sending data. You would need to build sending files on top of it.
