### ISSUE TITLE
How to create virtual devices 

### ISSUE THREAD

**Issue by AleeeKoi** [Polidea/react-native-ble-plx#722]
Hello,
I need to create virtual devices to emulate a BLE peripheral at run time (like lightblue app).
I have searched in documentation but I haven't found a solution.

Any advices? Thank you

**Comment by dariuszseweryn** [comment]
If you want your app to become a central then this library does not yet support this functionality

**Comment by AleeeKoi** [comment]
Ok, @dariuszseweryn do you know any other RN library to do that?
Google is not helping me so much...
Thank you

**Comment by dariuszseweryn** [comment]
No unfortunately. Nothing cross platform.

**Comment by AleeeKoi** [comment]
OK, thank you
