### ISSUE TITLE
Having trouble in reading characteristics

### ISSUE THREAD

**Issue by alexandrapersea** [Polidea/react-native-ble-plx#73]
After connecting to a device, when i read from a characteristic the promise returned an  characteristic object.

I've tried both **characteristic.read()** and **readCharacteristicForDevice** but what is being returned is an characteristic object. From what i understand what's read from the device is supposed to be a value. I don't understand how to get to that value.

My code looks something like this:

 ```characteristics = await this.manager.characteristicsForDevice(device.id,  services.uuid)
   characteristics.map((characteristic) => {
        if(characteristic.uuid === 'my uid') {
            characteristic.read()
            .then(val => console.log(val))
            this.manager.readCharacteristicForDevice(device.id,
                                                 characteristic.serviceUUID,
                                                 characteristic.uuid)
          .then(value => console.log(value))
        }
    })

**Comment by Cierpliwy** [comment]
Characteristic object is returned, so that chaining function calls is easier. You don't need to get characteristic object directly to use it:
```js
 device.readCharacteristicForService('service uuid', 'characteristic uuid')
    .then(characteristic => console.log(characteristic.value))
```

When read, characteristic object contains valid Base64 value in its value property.

**Comment by alexandrapersea** [comment]
Thank you!
