### ISSUE TITLE
BLE Permission not working on 0.63.2 with Android 10

### ISSUE THREAD

**Issue by ezranbayantemur** [Polidea/react-native-ble-plx#730]
Hello there, 

My project was on React Native 0.63.2 version and when I tried to scan ble devices couldn't see any of them. Even I asking permission and allow the location. It happens only Android 10 devices. 
When I check the error callback it says: `[BleError: Device is not authorized to use BluetoothLE]`  
This error not happens on 0.62.2 

Interesting things are:
* When I ask permission on Android 10, it's not ask "Allow Always", only "Allow While Using" and "Deny" 
* When I go to Settings => Apps => <My App> => Permissions => Location section and I select "Deny" and "Allow While Using" again, the error disappears and app can search devices properly.

Buggy versions:
``` 
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-ble-plx": "^2.0.1"
```
Working versions:
```
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-ble-plx": "^2.0.1"
```

AndroidManifest.xml permissions
```xml
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.BLUETOOTH"/>
  <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
```

It may not happens because of this package, maybe React Native itself but I found it on this package.

**Comment by dfrancio** [comment]
Hello,

same for me if I use the SDK version 29
{
        buildToolsVersion = "29.0.2"
        minSdkVersion = 18
        compileSdkVersion = 29
        targetSdkVersion = 29
}

if I go back to SDK version 28, everything is fine
{
        buildToolsVersion = "28.0.3"
        minSdkVersion = 18
        compileSdkVersion = 28
        targetSdkVersion = 28
 }

Regards,

**Comment by owav** [comment]
Hi,

I had the same issue when I updated my _targetSdkVersion_ from _28_ to _29_.

Replacing the android permission **ACCESS_COARSE_LOCATION** with **ACCESS_FINE_LOCATION** in my _AndroidManifest.xml_ and in my app's code for manually asking the user with _PermissionAndroid_ fixed it for me.

Recap of what's working for me : 
_build.gradle :_
```
buildToolsVersion = "29.0.2" 
minSdkVersion = 18 
compileSdkVersion = 29 
targetSdkVersion = 29 
```

_AndroidManifest.xml :_
```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.BLUETOOTH"/>
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
<uses-permission-sdk-23 android:name="android.permission.ACCESS_FINE_LOCATION"/>
<uses-feature android:name="android.hardware.bluetooth_le" android:required="true"/>
<uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
```

_in my app's code :_
```
const granted = await PermissionsAndroid.request(
	PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
	{
		title: 'Permission Localisation Bluetooth',
		message: 'Requirement for Bluetooth'
		buttonNeutral: 'Later',
		buttonNegative: 'Cancel',
		buttonPositive: 'OK',
	}
);
```

Hope this helps.

**Comment by dfrancio** [comment]
Hello,

I've tried the @owav 's solution and it works! Thanks for sharing.

Regards

**Comment by acasademont** [comment]
I believe this should work with COARSE location settings too, we don’t want to ask for GPS/FINE permissions to our users. Is there any way we can help you fix it?

**Comment by owav** [comment]
@acasademont this may be due to permission changes in android 10 : 
https://developer.android.com/about/versions/10/privacy/changes#location-telephony-bluetooth-wifi

So I guess we just have to say goodbye to COARSE_LOCATION.

If anyone with a broader understanding can confirm this...

**Comment by acasademont** [comment]
@owav yeah, but then RN 0.62 on Android 10 should fail too, but it works, there must be something else we’re missing on RN 0.63.

**Comment by ezranbayantemur** [comment]
@acasademont That "missing" is about RN or this package? According that, we should tell them this problem for prevent other problem

**Comment by acasademont** [comment]
We've been investigating a bit and the this library does not have any bugs. As you previously mentioned, the only issue is that RN 0.63 targets Android SDK 29, which in turn has the new permissions in place. A nice article detailing the changes can be found here:

https://developer.android.com/about/versions/10/privacy/changes

So probably the only thing that needs an update is the README & examples. We'll keep testing RN 0.63!

**Comment by zmnv** [comment]
Updated from RN 0.61 to 0.63.2... And I see that error.

That changes fixes a problem. Thanks @owav.

![image](https://user-images.githubusercontent.com/25253501/91973608-30694680-ed25-11ea-8398-9993be915987.png)

![image](https://user-images.githubusercontent.com/25253501/91973574-22b3c100-ed25-11ea-9ead-c4a91b6ac3ca.png)

ps: I don't use `uses-feature android:name="android.hardware.bluetooth_le"` and all fine.

**Comment by acasademont** [comment]
tbh, I think this issue might be closed now, it's definitely not a library bug.

**Comment by dariuszseweryn** [comment]
If you have suggestions where and how change the documentation/wiki/readme — feel free to give suggestions.

**Comment by Xenofono** [comment]
I struggled with this issue for about 6 hours, nothing worked. Then I restarted my phone and it worked immediately.

**Comment by bvanderdrift** [comment]
I haven't seen a PR yet to include this in the README, so made one: https://github.com/dotintent/react-native-ble-plx/pull/940

**Comment by dsnarwariya0102** [comment]
Hello 

My project was on react native version 0.70.3 and  buildToolsVersion = "31.0.0" when app install  on android 11 all permission work fine but when app install android 12 do not turn on device blutooth. and its throw an error and release build app crash while installing

**Comment by aamirfaisal** [comment]
@dsnarwariya0102 
Try /replace this
const granted = await PermissionsAndroid.request(
	PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
	{
		title: 'Permission Localisation Bluetooth',
		message: 'Requirement for Bluetooth'
		buttonNeutral: 'Later',
		buttonNegative: 'Cancel',
		buttonPositive: 'OK',
	}
);

instead of 

const granted = await PermissionsAndroid.request(
	PermissionsAndroid.PERMISSIONS.ACCESS_COURSE_LOCATION,
	{
		title: 'Permission Localisation Bluetooth',
		message: 'Requirement for Bluetooth'
		buttonNeutral: 'Later',
		buttonNegative: 'Cancel',
		buttonPositive: 'OK',
	}
);
