### ISSUE TITLE
Should I enforce the my app to ask for GPS permission even if the library works fine without it?

### ISSUE THREAD

**Issue by sharqawiDev** [Polidea/react-native-ble-plx#735]
Hello,
I was able to write a simple app using react-native-ble-plx that communicates with an **ESP32 device**, and monitors its characteristics to read any new incoming data.
The thing is, I was successfully able to do this **without asking for any GPS (fine location or coarse location) permissions.** The app even works **without turning on GPS on my android phone**.

Should I enforce the app to be authorized to use GPS? Or is it ok to continue working without it? 
**Note:** 
I'm using:
- the latest version of react-native-ble-plx (v2.0.1)
- react-native v0.63
- Android 9 (Galaxy S8+)

Finally, special thanks for your effort in developing this awesome library, it really made everything related to BLE easier for me.

**Comment by acasademont** [comment]
I believe the permissions are only needed if you scan the environment (thus potentially being able to locate where you are from the devices you see), if you directly connect to a known device then you don't really need them..
