### ISSUE TITLE
Connect to a smartphone advertised as beacon

### ISSUE THREAD

**Issue by marwakhalil** [Polidea/react-native-ble-plx#74]
Hi, i'm actually advertising my android phone as an iBeacon for testing the connection and i couldn't connect, will that be possible cause i've noticed that the mac id is generated, so will it be possible to connect and write to a smartphone advertised as beacon

**Comment by marwakhalil** [comment]
is there any response for my question please ?

**Comment by nathmack** [comment]
@marwakhalil did you have any luck with this?

**Comment by marwakhalil** [comment]
Nope Unfortunately, I've let that feature for the next version
