### ISSUE TITLE
The value inside the device.connect().then().catch() returns null

### ISSUE THREAD

**Issue by vagnerwentz** [Polidea/react-native-ble-plx#741]
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active) or on our [Gitter](https://gitter.im/RxBLELibraries/react-native-ble) channel.

## The value at `device.connect()` is null, but out, returns a long identifier

I created a function called `scanAndConnect()`, inside this function I called the `manager.startDeviceScan()` when the `device.name === 'MLT-BT05` I stop called `stopDeviceScan()`. Okay, it is working, but the problem are when I use `console.log()` inside the `device.connect().then(...).catch(...)`, when I try to log the `servicesUUIDs[0]` inside the `then()` the value comes as `null`, but out the `device.connect()` when I log the `servicesUUIDs`, come a long identifier, I would like to know what is happening here.

## scanAndConnect()
```
async function scanAndConnect() {
    manager.startDeviceScan(null, null, async (error, device) => {
      if (error) {
        console.log('Error at if(error): ', error);
        return null;
      }

      if (!device) {
        console.log('Error at if(device === null)');
        return null;
      }

      if (device.name === 'MLT-BT05') {
        manager.stopDeviceScan();

        /* serviceUUID = 0000ffe0-0000-1000-8000-00805f9b34fb */
        if (device.serviceUUIDs) {
          console.log(device.serviceUUIDs);
        }

        // Proceed with connection.
        device
          .connect()
          .then((d: Device) => {
            console.log('d.id: ', d.id);
            console.log('d.name: ', d.name);
            if (d.serviceUUIDs) {
              console.log('d.servicesUUIDs[0]: ', d.serviceUUIDs[0]);
            }
            if (d.solicitedServiceUUIDs) {
              console.log(
                'd.solicitedServiceUUIDS: ',
                d.solicitedServiceUUIDs[0],
              );
            }
          })
          .catch((err) => {
            console.log(err);
          });
      }
    });
  }
```
# Repository
`src/pages/Home/index.tsx`
https://github.com/vagnerwentz/bluetooth-lad

**Comment by Telluris** [comment]
@vagnerwentz  Did you find any solution for it?

**Comment by mikolak** [comment]
There are actually two entities in play here. One is the scan result, the other is the peripheral. Scan result contains all the advertisement data - advertised local name, advertised services, manufacturer data. 

Scan results are not cached by the library, since there could be a lot of them and the library wouldn't know when to clean such cache.

The second entity, peripheral, the abstracted BLE device does not know what its advertisement data was. If you care about it, you need to remember it yourself. This second entity does not know any services unless you've ran discovery.

**Comment by ELBEQQAL94** [comment]
StartScan always return null
