### ISSUE TITLE
Problem in decoding Characteristic value.

### ISSUE THREAD

**Issue by mhkasif** [Polidea/react-native-ble-plx#748]
## Question

Please describe the question.
I've simulated BLE peripheral using bleno.
below I'm attaching the pictures which show the onReadRequest function to which some value is sent to the device.
![Screenshot 2020-09-22 at 12 15 19 AM](https://user-images.githubusercontent.com/30750191/93811671-f3c8a500-fc69-11ea-890b-07076758db86.png)

what is want in return is "800400000000" this value which is being shown by lightblue app.

![Screenshot 2020-09-22 at 12 22 06 AM](https://user-images.githubusercontent.com/30750191/93811858-37231380-fc6a-11ea-9a24-ce4de3bb625a.png)

I'm getting a base64 decoded value which I tried a lot to convert back to the original value but yet unsuccessful.

kindly tell me how to resolve this problem.

**Comment by mhkasif** [comment]
Issue resolved by myself.
thanks

**Comment by TwoTenPvP** [comment]
How did you resolve it? Doesn't seem documented anywhere

**Comment by hungdev** [comment]
I have the same question, how did you resolve it?
