### ISSUE TITLE
Can't disconnect from device (Android)

### ISSUE THREAD

**Issue by kinber95** [Polidea/react-native-ble-plx#75]
Hello 
I want to disconnected from my Android device. I used following code:
First 
`  cancelDevice(id) {
    this.manager.cancelDeviceConnection(id)
      .then((device) => {
        console.log('Connection lost: ' + device.isConnectable + " with " + device.name);
      }, (error) => {
        console.log('cancel: ' + error);
      }) 
  }`

Second
`  cancelDevice() {
      this.device.cancelConnection()
        .then((device) => {
          console.log('Connections cancel: ' + device.name + ' ' + device.id);
        })
  }`

The manager disconnect and I cant use other functions of my code because, I am disconnected from my device according to the manager, but I can see on my Android device thats still a connection.

Any solutions ?

**EDIT**

I test my functions on two different devices, on my Motorola G all work fine and on my ZTE I can't disconnect

**Comment by nejcet** [comment]
+1

**Comment by Cierpliwy** [comment]
Please check on version 0.5.0 as it has updated Android dependency.

**Comment by Cierpliwy** [comment]
Please retest with latest version of library and reopen if needed.

**Comment by miawils** [comment]
Hi I am currently having this issue with the Google Pixel 2.
