### ISSUE TITLE
I cannot maintain bluetooth connection when navigation to another interface

### ISSUE THREAD

**Issue by MedRaid** [Polidea/react-native-ble-plx#751]
Thanks for this real awesome library

I have a questions about maintaining BLE connection while going from a page to another 

  async scanAndConnect() {
        this.setState({connection: false})
        console.log("---- in scanAndConnect ----")
        this.manager.startDeviceScan(null, {
            allowDuplicates: true
        }, (error, device) => {
            if (error) {
                this.setState({ errorOnce: this.state.errorOnce + 1 })
                if (this.state.errorOnce < 1) {
                    Toast.show("Scanning " + error.message, Toast.LONG, [
                        'UIAlertController',
                    ]);
                    this.addToLogFile(error.message)
                } else { 
                    return
                }
            }
            Toast.show("Info: " + "A la recherche du Olem, verifiez si Olem est allumé et proche de vous", Toast.LONG, [
                'UIAlertController',
            ]); 

            setTimeout(() => {
                this.manager.stopDeviceScan();
             }, 7000);
 
            this.state.myDevice = device
            if (device != null && device != undefined ) {
            console.log("name", device.name)
            console.log("id", device.id)

                if (device.name == "robot") {
                    console.log('It is our BLE ');
                    this.manager.stopDeviceScan();

                    device.connect()
                        .then((device) => {
                            console.log("Connected to BLE", device);
                            return device.discoverAllServicesAndCharacteristics();
                            //return device.services();
                        })
                        .then((device) => {
                            console.log("Connected services : " + device);
                            console.log(JSON.stringify(device.services()));
                            return device.services();
                        })

                        .then((services) => {
                            console.log('Services Length : ' + services.length);
                            this.setState({ ServicesLength: services.length })
                            for (let userObject of services) {
                                console.log("UUID --------->" + userObject.uuid);
                            }
                            return services[0].characteristics();

                        }).then((characteristics) => {
                            console.log(characteristics)
                            console.log('Characteristics Length : ' + characteristics.length);
                            this.setState({ CharacteristicLength: characteristics.length })

                            this.setState({ CharacteristicUUID: characteristics[1].uuid })
                            this.setState({ isReadable: characteristics[1].isReadable })

                            console.log('Characteristic UUID : ' + characteristics[0].uuid + "--" + characteristics[1].uuid);
                            console.log('Characteristic Value : ' + characteristics[0].value);

                            this.setState({ deviceID: device.id })
                            console.log('Device ID : ' + device.id);
                            console.log('___STATE___ ' + this.state.myCarac); 
                            this.setState({ connection: true })
                        })

                        .catch((error) => {
                            this.setState({ connection: false })

                            Toast.show("Connexion: " + error.message, Toast.LONG, [
                                'UIAlertController',
                            ]);
                        });             
                }
            } else {
                console.log('Scanning' + error);
                this.setState({ connection: false })
               return
            }
        });

    }

Does any one has any suggestions about this ? 

Thanks!

**Comment by dariuszseweryn** [comment]
Hello,

Try decoupling lifecycle of your BLE related code from the lifecycle of your UI components. This is an architecture problem and there are quite a few approaches to that. There are some good articles to be found via Goggle I guess.

Best regards
