### ISSUE TITLE
Causing the build to fail 

### ISSUE THREAD

**Issue by tarunkishore2303** [Polidea/react-native-ble-plx#757]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior

Give me the successful build when I run `react-native run-android`

## Current Behavior

Causing my build to fail. And the build is successful when I uninstall the `react-native-ble-plx` package

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
    Install the latest version of react native and Android studio
2. step 2
    Install `react-native-ble-plx` and run the command `react-native run-android`
3. Step 3
    You will get errors in the terminal

When the `npm` package is installed:
![image](https://user-images.githubusercontent.com/53224551/96405108-267aa480-11fa-11eb-8ab1-87094cbc87ed.png)

Testing in : Android
Platform OS : Windows 10 Home

**Comment by Mhde96** [comment]
i have the same problem

**Comment by tarunkishore2303** [comment]
My bad ! Didn't change the `minSdkVersion` and those extra stuff !
