### ISSUE TITLE
How to Print Pictures or Images To Bluetooth Printer with React Native Ble Plx

### ISSUE THREAD

**Issue by FazilMuhammed** [Polidea/react-native-ble-plx#758]
RN version 0.63.3
IOS Platform
React-Native-Ble-Plx 2.0.1

How can Print Images or Picture  To Bluetooth Printer Anyone knows Please help...

**Comment by Johnsonzhangc** [comment]
I want to know as well

**Comment by TheSinding** [comment]
Bump - I'd also like to know
