### ISSUE TITLE
Possible Unhandled Promise Rejection

### ISSUE THREAD

**Issue by marwakhalil** [Polidea/react-native-ble-plx#76]
Hello, I'm trying to write on my mac advertised as beacon and i'm not able to i keep on getting this warning meanwhile i'm connected to the advertised mac, 
![18676366_1705375692820843_17978517_o](https://cloud.githubusercontent.com/assets/15096458/26310027/9573dd7e-3eff-11e7-81a8-562cffea8ea6.png)

My code looks something like this : 
 

` scanAndConnect() {
        this.manager.startDeviceScan(null, null, (error, device) => {
            if (error) {
                console.log("error");
                return;
            }

            console.log("device id est : "+device.id);
            console.log("device name est : "+device.name);
            console.log("base 64 encoding : " + encoded);
     if (

                device.name === 'MacBook Pro'    ||
                device.id === '6C:40:08:AE:7A:19'

            ) {
                console.log("this is it");
                this.manager.stopDeviceScan();

                // Proceed with connection.
                device.connect()
                    .then((device) => {
                        return "those are all characteristics"+ device.discoverAllServicesAndCharacteristics();

                    })
                    .then((device) => {
                        console.log(device.manager);
                    })
                    .catch((error) => {
                        // Handle errors
                    });

                device.writeCharacteristicWithResponseForService('6b401f54-6fca-4dbf-bb9c-b15bb7ab0958',null ,encoded,'1' );

            }
        });

    }`

**Comment by Cierpliwy** [comment]
I have never worked with iBeacons. If you give me hints how to setup environment for this then I will try to help. Please also check that your device.isConnectable - if value is missing then we are not sure.

**Comment by marwakhalil** [comment]
i'm currently advertising my mac using BeaconOsX app : that i got it from here https://github.com/falkorichter/BeaconOSX/releases
and for device.isConnectable the value is null but when i downloaded the Sniffator example from play store i got a connection between my android phone and my mac as beacon, 
hope you can help

**Comment by marwakhalil** [comment]
@Cierpliwy  any ideas ?
