### ISSUE TITLE
bleManager is not restored after application is closed on IOS

### ISSUE THREAD

**Issue by shalvagelenidze** [Polidea/react-native-ble-plx#760]
I am able to connect to BLE device from App, however I want to maintain the connection to device once the APP is closed. 

According to [documentation](https://github.com/Polidea/react-native-ble-plx/wiki/Background-mode-(iOS)) the bleManager should be able to restore its state (it should maintain connection even after app is closed with BLE device) and once the APP opens, it should restore its state (restoredState.connectedPeripherals). However each time I close the App and then start it over the restoredState is always null.

```
const bleManager = new BleManager({
  restoreStateIdentifier: 'BleInTheBackground',
  restoreStateFunction: restoredState => {
    if (restoredState == null) {
      // BleManager was constructed for the first time.
    } else {
      // BleManager was restored. Check `restoredState.connectedPeripherals` property.
    }
  },
});
```

I am using React Native and do not want to use Native Modules to implement the functionality I want to achieve. 
I did the implementation as it is described in documentation.

**Comment by dariuszseweryn** [comment]
It is restoring the state if the iOS chooses to kill the app. If the user closes the app by swiping it off (kills it manually) then the process cannot take place.
Best regards.
