### ISSUE TITLE
 not detecting all nearby devices

### ISSUE THREAD

**Issue by Mhde96** [Polidea/react-native-ble-plx#761]
i have 2 device Samsung galaxy a30 and there are Bluetooth Low Energy supported

and i can't find him when used react-native-ble-plx manager.startDeviceScan

and i have 2 laptops 

first laptop windows 10 just i find id and  the device name is shown as null and when Restart Bluetooth the addres bluetooth is changed 

seconde laptop macbook pro and i can't find id or any thing

 

and this is my code 

  ```
  export const App = () => {
        const manager = new BleManager();
 
        manager.startDeviceScan(null, { scanMode: 2, }, (error, device) => {
            if (error) {
                console.log('error', error)
                return
            }

            if (device !== null) {
                  console.log(device)
            }
        }
    }
```

i had edit my android/app/src/main/AndroidManifest.xml

   

>  <uses-permission android:name="android.permission.BLUETOOTH"/>
>     <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
>     <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
>     <uses-permission-sdk-23 android:name="android.permission.ACCESS_FINE_LOCATION"/>
>     <uses-feature android:name="android.hardware.bluetooth_le" android:required="true"/>

i used 

 

> 
>      "react": "16.13.1",
>      "react-native": "0.63.3",
>      "react-native-ble-plx": "^2.0.1",
>

**Comment by dariuszseweryn** [comment]
Hello,
This is not a bug. Not all devices are advertising themselves. They can change advertised MAC addresses. They may not advertise their names.
Best regards
