### ISSUE TITLE
scan devices and get refresh rssi data without connection

### ISSUE THREAD

**Issue by ammiladi** [Polidea/react-native-ble-plx#765]
Hi,
I try use react-native-ble-plx to scan and get refreshed distance every 5s.
1- There's a way to get refreshed rssi values without connect to devices?
2- How can i get the value of txPower?
3- How can i continue scan devices on background? Is t possible to scan even application is closed?

Thanks for help

**Comment by dariuszseweryn** [comment]
> There's a way to get refreshed rssi values without connect to devices?

Scan results are giving you that
> How can i get the value of txPower?

Tx Power is not yet exposed in the API
> How can i continue scan devices on background? Is t possible to scan even application is closed?

You need to keep the app working on Android (goggle Foreground Services) — for iOS [check wiki](https://github.com/Polidea/react-native-ble-plx/wiki/Background-mode-(iOS)).
