### ISSUE TITLE
How long the application will get connected in background?

### ISSUE THREAD

**Issue by priyanka-Sadh** [Polidea/react-native-ble-plx#772]
I want to know if the application goes into background mode, Then how long app will get connected to Bluetooth device and and syncing data process will work how long time after placed in background.

**Comment by dariuszseweryn** [comment]
Hello,
The answer is: it will continue to work until the system allows it to work. YMMV as this is subject to OS updates/changes. There is [a wiki page](https://github.com/Polidea/react-native-ble-plx/wiki/Background-mode-(iOS)) describing what happened in iOS some time back.

**Comment by priyanka-Sadh** [comment]
Thanks @dariuszseweryn :)
