### ISSUE TITLE
Could not find jar files

### ISSUE THREAD

**Issue by n-maiya** [Polidea/react-native-ble-plx#775]
I just added the library to my react native project using _npm install --save react-native-ble-plx_
My RN version is 0.63.3
On building the app after adding **import { BleManager } from 'react-native-ble-plx';** I'm getting this error.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugJavaResource'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find rxandroidble-1.7.1.jar (com.polidea.rxandroidble:rxandroidble:1.7.1).
     Searched in the following locations:
         https://jcenter.bintray.com/com/polidea/rxandroidble/rxandroidble/1.7.1/rxandroidble-1.7.1.jar

Do I need to add the jar file manually?  Also, my build.gradle has maven { url 'https://www.jitpack.io' } under repositories.

**Comment by dariuszseweryn** [comment]
Could you share what repositories you have set in your build.gradle file?
