### ISSUE TITLE
Multiline charachteristic response

### ISSUE THREAD

**Issue by foundationx** [Polidea/react-native-ble-plx#783]
I am using device.writeCharacteristicWithResponseForService and getting the characteristic.value response and decoding it, but I only get the first line of what I should be getting.
when I test using a third party application( Serial Bluetooth Terminal ) application I get the expected 2 line response. I cant figure out why.  Should the response include all lines of the response or would the library only return 1 line?
Thanks

**Comment by dariuszseweryn** [comment]
It depends on your peripheral and how it does send the data. I don't know. I guess you should consult the documentation of your peripheral or Serial Bluetooth Terminal protocol.
