### ISSUE TITLE
framework not found BleClientManager for architecture arm64

### ISSUE THREAD

**Issue by microwavesafe** [Polidea/react-native-ble-plx#79]
I started by trying to install it automatically.

```npm install react-native-ble-plx```
```react-native link```

which works, but does through up some warnings when running the build script. The warning seems to suggest it can't open Rx.playground in workspace Rx.xcworkspace. Although I have verified that at least the files exist, and the build never fails.

I then tried to follow the manual steps. I noticed that ```Always Embed Swift Standard Libraries``` was set to no and it didn't have the Run Script Phases, so I added those, rebuilt the project but same outcome.

The exact error I get is
```ld: framework not found BleClientMagaer for architecture arm64```
```clang: error: linker command failed with exit code 1```

I'm more familiar with Android so I'm struggling to debug this. Is there something obvious I'm missing?

**Comment by Cierpliwy** [comment]
There is a note in documentation that regardless of 
```
npm install react-native-ble-plx
react-native link
```
you have to continue manual installation setup from step 7.
Did you do that?

**Comment by microwavesafe** [comment]
I knew it would be simple when I could see it! I thought I had, but it looks like I actually didn't do 7.
