### ISSUE TITLE
Question: Missing notifications on iOS

### ISSUE THREAD

**Issue by ramos-lucas** [Polidea/react-native-ble-plx#802]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active) or on our [Gitter](https://gitter.im/RxBLELibraries/react-native-ble) channel.

## Question

**Some notifications are not received on iOS**
I'm monitoring a characteristic which responds approximately 80 times per second.  Its response is converted to an array of bytes. I split this array into 3 other arrays which are the values I need. Since I'm using a test hardware, I know exactly how the values should be. 
On android it works, but on iOS I'm missing some notifications on the way.

Example: 
On Android I received:
- notification 1: 6.934.875, 6.950.625, 6.963.375
- notification 2: 6.972.750, 6.978.000, 6.978.625
- notification 3: 6.974.125, 6.964.375, 6.948.750
- notification 4: 6.927.375, 6.900.000, 6.866.375
- notification 5: 6.826.750, 6.781.125, 6.729.500

On iOS, I only received notifications 1 and 4. Is there anything else that needs to be done?

```
manager.monitorCharacteristicForDevice(
      connectedDevice.id,
      serviceUUID,
      characteristicUUID,
      (error, characteristic) => {
        if (error) {
          console.log(error);
        } else {
          const arrayBuffer = ByteBuffer.fromBase64(
            characteristic.value || '',
          );
          // get result
        }
      },
    );
```

**Comment by dariuszseweryn** [comment]
I expect that your test hardware/firmware is dropping packets because it assumes a specific connection speed.

**Comment by dariuszseweryn** [comment]
Closing due to lack of information and inactivity of the original poster.

When more data will be available—feel free to add that information and reopen this issue.

Best Regards
