### ISSUE TITLE
Why i can not connect to some devices?

### ISSUE THREAD

**Issue by dhruvwo** [Polidea/react-native-ble-plx#804]
# Mobile Device Environment
## iOS
Device: iPhone6s
OS: iOS14.3

## Android
Device: Redmin Note 7 Pro
OS: Android 10

# Application Environment
React Native version: v0.63.3
react-native-ble-plx: 2.0.2

# Issue
I am trying to connect nearby devices using this library.

I am able to connect to some BLE devices (i.e. Smartwatch/ Band/ MAC mini), but I can not connect to devices like (windows PC & PC with debian install)

If I am not wrong, to connect the device both app needs to support BLE.

I have used [this](https://winaero.com/how-to-check-if-your-pc-supports-bluetooth-4-0/) to check if my windows 10 Laptop supports BLE or not and it is supported.

# When I try to connect I am getting the following error:-
Android: "Disconnected from 98:7B:F3:B0:D7:9D with status 133 (GATT_ERROR)"
iOS: It does not return anything but after adding timeout I get a timeout error 

# Questions
- [ ]  Am I doing something wrong?
- [ ]  is it even possible to connect windows/debian PC with this or any other library?

Thanks for your help.

**Comment by dariuszseweryn** [comment]
> Am I doing something wrong?

You may be trying to devices that are not allowing you to do so — they may have obscure ways for pairing

> is it even possible to connect windows/debian PC with this or any other library?

Consult Windows/Debian documentation regarding BLE. In my opinion there should be no reason for this library to connect to any BLE device that allows connections*.

/* that is every device that OS allows — e.g. iOS does not allow to connect to iBeacons using CoreBluetooth and the user needs to use CoreLocation framework which has different API.
