### ISSUE TITLE
onDisconnected never triggered

### ISSUE THREAD

**Issue by nicolas-wl** [Polidea/react-native-ble-plx#809]
When turning off Bluetooth or physically disconnecting my device "onDisconnected" is never fired 

Platform: iOS
Version: 2.0.2

Simplified code:
```
const connect = async(deviceID) => {
let connectedDev = await manager.connectToDevice(deviceID);
if (connectedDev) {
       connectedDev.onDisconnected((error) => {
            console.log(error);
       });
}
}
```

**Comment by ThomasStubbe** [comment]
Having similar issues on Android with Version 2.0.2: If the device is disconnected and turned on quickly afterwards, the device is disconnected, but the onDisconnected event is never thrown.

**Comment by nicolas-wl** [comment]
Edit: Issue solved, wasn't a bug. Just bad storing of the BLEManager instance
