### ISSUE TITLE
writeCharacteristicWithResponseForDevice not firing in Release Build

### ISSUE THREAD

**Issue by nicolas-wl** [Polidea/react-native-ble-plx#811]
My project features connect, read and write implementations with ble. Everything works properly in debug mode however when running a release build everything works EXCEPT all "writeCharacteristicWithResponseForDevice" commands. They seem to be ignored / not getting executed at all.

Platform: iOS
iOS version: 14.1
Version: 2.0.2

**Comment by aanjan123** [comment]
@nicolas-wl have you fixed it? 
I am having similar issue.
