### ISSUE TITLE
Permission Issue for iOS/iPad Os

### ISSUE THREAD

**Issue by larry-cherry** [Polidea/react-native-ble-plx#831]
I had an error that I was working through that caused me some problems when initially setting up this library in my app. It was causing the app to crash as soon as I tried to use anything from react-native-ble-plx. Below is a screenshot of the error I had from xcode.

![Screen Shot 2021-03-10 at 9 00 00 AM](https://user-images.githubusercontent.com/22753964/110653279-b8bc1e80-8182-11eb-90f2-3cc6fd0a09d4.png)

The solution was simple once I found out the error I just needed to add the proper permission for bluetooth. Example below.
![Screen Shot 2021-03-10 at 9 30 30 AM](https://user-images.githubusercontent.com/22753964/110653940-51eb3500-8183-11eb-9ede-2fe6f26510be.png)

My request is that this information gets added to the documentation for initial setup so everyone is aware they need to add this permission to use this library in iOS/iPad.

**Comment by Krizzu** [comment]
Hey, it seems like it's already mentioned as [step six for iOS setup in README](https://github.com/Polidea/react-native-ble-plx#ios-example-setup).

**Comment by larry-cherry** [comment]
My mistake then.
