### ISSUE TITLE
Question Is it possible to use this library for building macOS apps?

### ISSUE THREAD

**Issue by kennieluv** [Polidea/react-native-ble-plx#834]
## Question for macOS

I've made ios and android app using this library. It works fine.
However, I need to make another one which works on macOS. 
When I tried to pod update the console says that it does not support macOS.
So is it completely blocked? or is there a way to use this library also for macOS apps?

I saw the previous issue macOS #6 but i couldnt find build_io_frameworks.sh

**Comment by webdevbyjoss** [comment]
hey, @kennieluv were you able to build `react-native-ble-plx` for the macOS desktop? have you found a solution to this issue?
