### ISSUE TITLE
write characteristic get BleGattException status= 19

### ISSUE THREAD

**Issue by kinber95** [Polidea/react-native-ble-plx#88]
On some off my android device I get this error when I want to write a characteristic for a service:

`Error: BleGattException{status=19, bleGattOperation=BleGattOperation{description='CONNECTION_STATE'}}
    at createErrorFromErrorData (NativeModules.js:115)
    at NativeModules.js:78
    at MessageQueue.__invokeCallback (MessageQueue.js:296)
    at MessageQueue.js:120
    at MessageQueue.__guard (MessageQueue.js:218)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:119)
    at debuggerWorker.js:71`

On other Android device there are no problems

**Comment by Cierpliwy** [comment]
This is an `GATT_RSP_EXEC_WRITE` error which might suggest that your device is not sending response to Android in time. Please check if this behaviour also occurs in nRF Connect application.

**Comment by kinber95** [comment]
@Cierpliwy  no in nRF Connect I can send my characteristic value to my ble device.

Should I use writeCharateristicWithoutResponse() ?

**Comment by DohaBasem** [comment]
@kinber95 did you find a solution to this issue or got any source that could elaborate more?

**Comment by kinber95** [comment]
@DohaBasem use writeCharacteristicWithoutResponse() and when you get the 19 error retry the write command.

BLE on Android sucks, especially on Motorola or Sony devices. We don‘t use rn for Android any more. Go back to the roots and use Java. Its sucks also  but  less than rn.

Cheers
