### ISSUE TITLE
uint8 read and writing comes out as uint16

### ISSUE THREAD

**Issue by JanErikFoss** [Polidea/react-native-ble-plx#89]
I'm developing an IoT device, so bytes are scarce. 
When reading or writing the byte 0b11111000, which is encoded as w7g= in base64,
it comes out as 76CA.
That is equivalent to the same value in 16 bits. This happens for any 8 bit value I want to send.

Is there anything I can do to force uint8?
I would rather avoid having to do manual translation of values before writing and after reading, as I've got values of many different lengths. If they all have to be translated from another data type, that is a lot of logic that could go wrong

**Comment by Cierpliwy** [comment]
Binary `11111000` is encoded in Base64 as `+A==`, conversion in other direction leads to 1 byte: `0xF8`. I am not sure how did you get these values.

**Comment by JanErikFoss** [comment]
Hi, this is embarrassing. I guess the binary to base64 converter I used was bugged or something. Thank you for your answer!
