### ISSUE TITLE
Execution failed for task ':react-native-ble-plx:compileReleaseAidl'.

### ISSUE THREAD

**Issue by inev** [Polidea/react-native-ble-plx#90]
When I try to add the library to an existing `ignite` project and try to run via `react-native run-android` I get `Execution failed for task ':react-native-ble-plx:compileReleaseAidl'.`

I looked around and the common suggestion is to upgrade the build tools version but react native wants that fixed.  Any suggestions?

**Comment by mhyousefi** [comment]
I have the same issue!
* What went wrong:
Execution failed for task ':react-native-icons:compileReleaseAidl'.
> java.lang.IllegalStateException: aidl is missing

**Comment by Cierpliwy** [comment]
Please retest with latest version and reopen if needed.

**Comment by PradeepNedun** [comment]
@Cierpliwy  I am still getting the same error with the latest version too. Please re-open this if not fixed.
