### ISSUE TITLE
How to get local bluetooth address?

### ISSUE THREAD

**Issue by biks152207** [Polidea/react-native-ble-plx#92]

**Comment by Cierpliwy** [comment]
What do you mean by local bluetooth address? On Android `Device.id` field will be a MAC address of a device and on iOS it will be autogenerated UUID. However this value on iOS is not guaranteed to be persistent.

**Comment by sooxiaotong** [comment]
@Cierpliwy any ideas how to fix non-persistent UUID?

**Comment by Cierpliwy** [comment]
You could put your device's unique ID in advertisement data under [manufacturer data (0xFF)](https://www.bluetooth.com/specifications/assigned-numbers/generic-access-profile) if you want to detect your device without connecting. Another option is to advertise you device's specific service UUID (0x07).
