### ISSUE TITLE
'react-native link' unrecognized

### ISSUE THREAD

**Issue by rpiwetz** [Polidea/react-native-ble-plx#98]
Started with a new project:
`react-native init appName`
`cd appName`
Verified that `react-native link` works.  Successful
Added react-native-ble-plx:
`npm install --save react-native-ble-plx`
Tried `react-native link`, receive error:
"Command `link` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project."

"dependencies": {
		"react": "16.0.0-alpha.12",
		"react-native": "0.45.1",
		"react-native-ble-plx": "^0.6.0"
}

**Comment by Cierpliwy** [comment]
I did the same thing as you and `react-native link` command resulted in:
```
Scanning 558 folders for symlinks in /Users/cierpliwy/git/appName/node_modules (5ms)
rnpm-install info Linking react-native-ble-plx android dependency 
rnpm-install info Android module react-native-ble-plx has been successfully linked 
rnpm-install info Linking react-native-ble-plx ios dependency 
rnpm-install info iOS module react-native-ble-plx has been successfully linked
```

**Comment by inev** [comment]
I have the same issue. I was able to get around it by deleting `node_modules` and typing `yarn`.

**Comment by rpiwetz** [comment]
@inev, thank you, that fixed it for me.  Tried with brand new RN app again and ran into the issue, so deleted node_modules and ran yarn...so had to sit through the building of all those framework files twice, but at least it works now.

**Comment by sakettawde** [comment]
Thanks, @inev had the same problem, repeated the same steps, deleted node_modules folder and ran 'yarn' command and then ran 'react-native link', seemed to work then.

**Comment by hhff** [comment]
same!  yarn FTW~

**Comment by jonrh** [comment]
Fell victim to this. My mistake was that I ran `react-native link` inside the wrong folder. I was in the `android/` folder. For `react-native link` to work you need to be located at the root of your React Native project.

This is because the command `react-native` only has the command `init` available globally. All other commands, for example `link`, rely on the React Native version you have installed in `node_modules`.

**Comment by Cierpliwy** [comment]
I'll add note to README file about it. I was also confused about it.

**Comment by volkansahin45** [comment]
Make sure your folder name and package.json name are equals. I used that mistake, I accidently changed the name in the package.json

**Comment by Cierpliwy** [comment]
About which folder name are you talking about @volkansahin45?

**Comment by volkansahin45** [comment]
@Cierpliwy the application folder

**Comment by sangampandey** [comment]
I believe this happens after you add any new library merely run yarn install after adding any library and later react-native link should definitely work

**Comment by rastogitech** [comment]
`react-native link` can not be used in "create-react native-app" projects.

**Comment by mayankzen123** [comment]
npm install native-base --save
npm install
react-native link

This sequence worked for me

**Comment by rastogitech** [comment]
Did it work in expo un-detached project?

**Comment by naxir** [comment]
@sangampandey thanks your solution worked for me

**Comment by bashirpour** [comment]
i run the `npm install`
and my problem was solved

**Comment by zero1world** [comment]
no one solution is running for me

**Comment by ZeldaYuan** [comment]
Me too, none of them works for me.

**Comment by TheBlackHacker** [comment]
`npm install` inside the project folder solved the problem.

**Comment by SL-A-SH** [comment]
No of the solutions work for either. 

- Removed node_modules folder.
- Installed yarn
- Typed 'yarn' and then 'react-native link react-native-vector-icons'

Still got the error **_Command `link` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project._**

I am on a Linux machine.

**Comment by Usamaliaquat123** [comment]
this no solution worked for me ...!

**Comment by Memexp** [comment]
Me neither, it still says:

bash: react-native: command not found

**Comment by shusain** [comment]
@Memexp you need to install react-native globally for the command to be found in your path `npm install -g react-native` or `yarn add global react-native`

**Comment by rinardmorais** [comment]
npm install react-native-firebase work!

**Comment by shusain** [comment]
Correction on what I said above (will edit as well) the globally installed package should be `react-native-cli` not `react-native`( this one should just be installed with a regular npm install in your project not globally) this will make the `react-native` commands available to use anywhere (assuming node module globals bin is in your system path)

**Comment by kest-cloud** [comment]
it really worked.....remove node_modules and run Yarn....worked perfectly. thanks so much

**Comment by daminduLiyanage** [comment]
This should work: 

`npm install --save react-native-firebase`
`react-native link react-native-firebase`

**Comment by matheusfaggi** [comment]
I try remove node_modules then run yarn, but does not work. I was adding dependencies directly on package.json. Now i try add each dependecies using yarn add, and work it.

**Comment by zacdemi** [comment]
In my case I was using npx create-react-app my-app instead of npx create-react-native-app

**Comment by kirbi96** [comment]
if you want add fonts, for react native 0.69 run
npx react-native-asset

**Comment by Zontex** [comment]
> if you want add fonts, for react native 0.69 run npx react-native-asset

Saved my life.

**Comment by TravisHi** [comment]
> if you want add fonts, for react native 0.69 run npx react-native-asset

Do we still have to configure the `react-native.config.js`?

**Comment by mothy900** [comment]
> if you want add fonts, for react native 0.69 run npx react-native-asset

Saved my life 2222 Thanks!!!!!!!

**Comment by Zhouwenli** [comment]
> `react-native link`不能用于“create-react native-app”项目。

为什么？

**Comment by hannan228** [comment]
no need for react-native link now
[https://reactnative.dev/blog/2022/09/05/version-070#android-auto-linking-for-new-architecture-libraries](android auto link update)
